### ISSUE TITLE
Add metadata fields as suggested by language of OPEN Government Data Act

### ISSUE THREAD

**Issue by hkdctol** [DOI-DO/dcat-us#10]
Hyon Kim
Data.gov
GSA

## Requirement(s)

The OPEN Government Data Act has provisions about require metadata. (See screenshots). Some are already in the existing schema at https://resources.data.gov/resources/dcat-us/ but others will require addition of new fields.

## Problem Statement

Look through the text of OPEN Government Data Act, and determine which fields are already covered in current schema, and what new fields need to be added

## Target Audience / Stakeholders

Public, agency dataset owners, agency data POCs, Data.gov

Required fields:
- [ ] description of the dataset/current schema already requires description https://resources.data.gov/resources/dcat-us/#description
- [ ] name/title of dataset/current schema requires title https://resources.data.gov/resources/dcat-us/#title
- [ ] indication of whether agency has determined or can determine whether dataset is aa) open government dataset bb) subject to disclosure under FOIA cc) public dataset dd) a dataset not subject to open format or license due to restrictions OR agency has not made that determination (this would have to be addressed by a NEW field)
- [ ] any determination made under 44 USC [3582](https://www.law.cornell.edu/uscode/text/44/3582) if available (this would have to be addressed by a NEW field)
- [ ] description by which public can request access to a dataset (this is not specifically addressed by current schema, would require a NEW field)
- [ ] date dataset was most recently updated/current schema requires modified date https://resources.data.gov/resources/dcat-us/#modified - there was one suggestion in old repository on this at https://github.com/project-open-data/project-open-data.github.io/issues/527
- [ ] agency responsible for maintaining dataset/current schema requires a publisher https://resources.data.gov/resources/dcat-us/#publisher
- [ ] owner of the dataset (is this same as agency/publisher, or is it a point of contact, which in current schema is https://resources.data.gov/resources/dcat-us/#contactPoint
- [ ] to the extent practicable, any restriction on use/potentially could be handled by the existing field "rights" https://resources.data.gov/resources/dcat-us/#rights
- [ ] location of the dataset (unclear what this means, but perhaps access or download URL?) https://resources.data.gov/resources/dcat-us/#distribution-accessURL or https://resources.data.gov/resources/dcat-us/#distribution-downloadURL
- [ ] any other metadata necessary to make data useful to agency or public, or as determined by OMB Director
<img width="786" alt="Screen Shot 2023-05-26 at 4 56 06 PM" src="https://github.com/DOI-DO/dcat-us/assets/3236989/0990fa3a-c909-4118-82f6-9d9f0a7dae4d">
<img width="602" alt="Screen Shot 2023-05-26 at 4 56 33 PM" src="https://github.com/DOI-DO/dcat-us/assets/3236989/4dcc8b36-ba24-46af-9268-dd415b57ea43">

**Comment by hkdctol** [comment]
On the concept of "owner" of dataset--cross referencing the issue from Project Open Data repository at https://github.com/project-open-data/project-open-data.github.io/issues/630

**Comment by fellahst** [comment]
All these requirements have been in the current specification.
