### ISSUE TITLE
Specify `creators` i.e., the organization(s) responsible for producing the dataset 

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#102]
**Creator Name:** John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

Metadata must specify a dataset’s `creators’ i.e.,  the *organization(s)* responsible for producing the dataset (distinct from the dataset ‘publisher’ role). 

NOTE: listing individual persons as creators is less useful than the organization they’re affiliated with but may be inevitable (e.g., in a formal citation).

**Comment by fellahst** [comment]
John,

In response to your requirement, we recommend the use of the optional property **dct:creator** to reference the creator of the dataset. The range for **dct:creator** is **foaf:Agent**, which provides the flexibility to represent different types of agents involved in the creation of the dataset. This can include a **foaf:Person**, an **org:Organization**, or even a software agent, all of which are subclasses of f**oaf:Agent**.

This approach allows for a broad range of entities to be accurately represented as creators, from individual persons to organizations. While we acknowledge your note about the lesser utility of listing individual persons compared to their affiliated organizations, this structure provides the necessary flexibility to accommodate various scenarios, including those where individual attribution may be inevitable, such as in formal citations.

We believe that this solution will effectively address your requirements and enhance the clarity and usability of our metadata specifications.

**Comment by ShaferAC** [comment]
+1

**Comment by mrratcliffe** [comment]
+1
