### ISSUE TITLE
Metadata supports references to zero or more standards describing a Dataset and/or Distribution resource

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#103]
**Creator Name:**  John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

Metadata must support _zero or more_ references to existing standards "used to indicate the model, schema, ontology, view or profile that the resource content conforms to" per [DCAT3 VOCAB] `dct:conformsTo` property.

NOTE: DCAT-US vocabulary explicitly restricts multiplicity to 0,1.  DCAT2/DCAT3 vocabularies do not indicate usage either way. GeoDCAT-AP 2.0.0 specifies multiplicity 0..n. 

## Problem Statement
If `dct:conformsTo` is used to specify standards, models, schema, ontologies (or all of these), then more than 1 must be validly specified.

## Target Audience / Stakeholders

**User1**: Data Steward/ Data Owner/ Data Creator. 
**User2**: Data Consumer

## Intended Uses / Use Cases
 
List all standards, models, schema, vocabs that describe the dataset or its distributions .

**Comment by fellahst** [comment]
Updated [Distribution metadata guideline](https://doi-do.github.io/dcat-us/#distribution-guideline) addressing this issue.
