### ISSUE TITLE
Metadata references any (and many) "conforms to" standards for Dataset and Distribution resources

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#104]
**Creator Name:** John Davidson
**Creator Affiliation:**  Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

Allow any and many standards to be referenced/linked to Dataset and Distribution resources _and_ to be  differentiated in the metadata. Metadata must support organization and/or community and/or domain-specific vocabularies of standards to be specified (e.g., specific standards defined/managed by each bureau if they have different standards they define/require.) i.e., do not limited the vocabularies of standards (models/schema/ontologies) that can be specified for a Dataset or Distribution resource to just one USG-wide list of standards. 

## Problem Statement

Bureau-specific, community-specific and/or subject-matter specific standards may need to be linked to Dataset and Distribution resources.  
-> Implication: Do not attempt to define and mandate use of a universally comprehensive and coherent reference vocabulary of USG "standards" for use across the Federal Government and for all Federal data resources.

## Target Audience / Stakeholders

**User1**: Data Steward/ Data Owner/ Data Creator
**User2**: Data Consumer/SME/Data Analyst

## Intended Uses / Use Cases

**Use Case 1**: Data Creator specifies the standards/models/schema/ontologies that describe the content of the data including its meaning, structure, and quality.
**Use Case 2**: Data Consumer searches for all data resources that "conform to" a particular domain-specific standard

**Comment by fellahst** [comment]
Updated [Distribution metadata guideline](https://doi-do.github.io/dcat-us/#distribution-guideline) addressing this issue.
