### ISSUE TITLE
Indicate the category of data content of a dataset resource

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#105]
**Creator Name:** John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

Indicate the “type” of data content (e.g., geospatial, statistical, structured, unstructured, tabular, time-series, multi-dimensional, graph, coverage, image, collection, series, etc.) using a property grounded to a controlled vocabulary of such Concepts. Akin to [DCMI Type vocabulary](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#section-7) [[DCTERMS](https://www.w3.org/TR/vocab-dcat-3/#bib-dcterms)] but more specific to types of data content.

NOTE: This is a different semantic than [dcterms:format](http://purl.org/dc/terms/format) or IANA [dcterms:MediaType](http://purl.org/dc/terms/MediaType). It is also a different semantic than [dcat:theme](http://www.w3.org/ns/dcat#theme), 

## Problem Statement

Can't find and discern datasets of interest by the type or category of content (the physical or conceptual phenomena represented) and representation (structure)

## Intended Uses / Use Cases

1. To determine fitness-for-use, I want to discern datasets by their content type 
2. To find candidate datasets I want to search/filter the catalog of datasets to those of a particular content type or data structure of interest.

## Existing Approaches - *Optional*

1. DCAT2 [dcterms:type](http://purl.org/dc/terms/type) and specifically [DCMI Type vocabulary](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#section-7) [[DCTERMS](https://www.w3.org/TR/vocab-dcat-3/#bib-dcterms)]
2. GeoDCAT-AP 2.0.0 specifies `dct:type` as value one of the URIs of the "Resource types" code list operated by the INSPIRE Registry [[INSPIRE-RT](https://semiceu.github.io/GeoDCAT-AP/releases/2.0.0/#bib-inspire-rt)] ...
 
## Additional context, comments, or links - *Optional*
A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by fellahst** [comment]
Requirement is addressed in [Resource Classification](https://doi-do.github.io/dcat-us/#resource-classification) usage guideline
