### ISSUE TITLE
Support data collections/ product series with "whole-part" relationships between dataset resources 

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#107]
**Creator Name:** John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)
 
Metadata represents “whole-part” relationships of target dataset to other datasets (e.g.,  dataset collections or product series). 

## Problem Statement

*Mandatory statement of the current situation, including:*
- *a description of the problem*
- *the stakeholders experiencing the problem*
- *what the stakeholder(s) are expected to supply (i.e. what contextual knowledge are they expected to have available) and/or receive to resolve the problem they are experiencing.*

## Existing Approaches - *Optional*

1. DCAT-US 1.1 defines [isPartOf](https://resources.data.gov/resources/dcat-us/#isPartOf)
2. DCAT3 defines [hasPart](https://www.w3.org/TR/vocab-dcat-3/#Property:resource_has_part)
3. DCAT3 defines [inSeries](https://www.w3.org/TR/vocab-dcat-3/#Property:dataset_in_series)
4. DCAT3 defines [DatasetSeries](https://www.w3.org/TR/vocab-dcat-3/#Class:Dataset_Series)

## Additional context, comments, or links - *Optional*

A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by fellahst** [comment]
This requirement is addressed in DCAT-US 3.0. See [DatasetSeries](https://doi-do.github.io/dcat-us/#dataset-series-guidance) usage guide.
