### ISSUE TITLE
Ensure that our new ISO metadata is compliant in terms of USDA-specific, Data.Gov and GeoPlatform.Gov requirements.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#108]
**Creator Name:** Rick Mueller
**Creator Contact Affiliation:** Section Head, Spatial Analysis Research Section, rick.mueller@usda.gov 
**Creator Affiliation:** USDA/NASS

## Requirement(s)

USDA NASS is responsible for the Cropland Data Layer (CDL) which is a NGDA. We currently maintain the metadata using the FGDC-1998 standard and are working on transitioning to the newer ISO 19115-3 standard. We want to ensure that our new ISO metadata is compliant in terms of USDA-specific requirements, as well as any additional Data.Gov and GeoPlatform.Gov requirements.  The CDL product is openly shareable and released into the public domain.

## Problem Statement

We are a small unit lacking updated metadata guidance.  Our issues are related to not having clear and concise guidance on the various formats ISO or DCAT json and how to create templates for those as well as updating our metadata archive to these newer standards.  To date we have nearly 900 metadata records that need updating.  Additionally, we do not have a valid entry posted on Geoplatform.gov. 

## Target Audience / Stakeholders

We create metadata to provide our customer base with technical documentation and in compliance with federal regulations and requirements.  Cropl and CROS dissemination portal resource page:  https://pdi.scinet.usda.gov/portal/apps/sites/#/cropcros 
 
## Intended Uses / Use Cases

We intend to make our metadata ready for ingestion into Data.Gov and Geoplatform.gov.  Coaching/guidance would be useful for established data standard. 

## Existing Approaches - *Optional*

Our current FGDC-1998 metadata is located at https://www.nass.usda.gov/Research_and_Science/Cropland/metadata/meta.php. 

## Additional context, comments, or links - *Optional*

Original email submission: 
[DCAT-US-3-Requirements-USDA - NASS.docx](https://github.com/DOI-DO/dcat-us/files/12028790/DCAT-US-3-Requirements-USDA.-.NASS.docx)

Our greatest need is for guidance and formal training designed specifically for these metadata formats and their creation.

**Comment by fellahst** [comment]
The approach of DCAT-US in leveraging existing standards like ISO 19115, as indicated by the available crosswalk, is aimed at streamlining metadata for search discovery purposes. This methodology focuses on retaining essential information that enhances dataset findability while omitting details that are less pertinent to this goal. However, it's important to note that DCAT-US still accommodates references to the complete, original metadata documents. This is achieved through the `dcat-us:metadataDistribution` property, which allows users to access the full breadth of metadata, including those comprehensive details outlined in standards like ISO 19115. This dual approach ensures that while the metadata presented in search and discovery tools is concise and focused, the comprehensive metadata, adhering to standards like ISO 19115, remains accessible and linked for those requiring more detailed information. The current specification provides a [usage guideline](https://doi-do.github.io/dcat-us/#usage_guideline) that will refine and augmented with additional training materials with during the implementation phase
