### ISSUE TITLE
DCAT-US Attribute Program Code requires an up-to-date, accurate, and authoritative list of agency program codes.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#109]
**Creator Name:** Kathleen Donelson-Westover

**Creator Contact Affiliation:** **Title**: IT Specialist (Data Architect/Data Engineer), **Email**: Kathleen_Donelson-Westover@fws.gov

**Creator Affiliation:** U.S. Fish and Wildlife Service, Information Resources and Technology Management, Enterprise Data Management Team

## Requirement(s)

DCAT-US Attribute Program Code requires an up-to-date, accurate, and authoritative list of agency program codes.

## Problem Statement

Program Code is a mandatory attribute in the DCAT-US Schema V1.1 and requires the use of program codes from the Federal Program Inventory.1 However, the Federal Program Inventory list provided at the Project Open Data DCAT-US-V1.1 website indicates the list was current as of Fiscal Year 2013. As a result, the Federal Program Inventory list does not represent all program codes in each federal agency. At this point, in the Department of the Interior there is a lack of consensus about how to extend program codes that are not in the Federal Program Inventory. Bureau representatives expressed reluctance to maintain Program Codes internally, preferring to rely on authoritative lists maintained by a recognized Federal government entity, like the Office of Personnel Management (OPM).

## Target Audience / Stakeholders

User 1. Agency data catalog providers.

## Intended Uses / Use Cases

Use 1. Associate data and information assets or investments with specific agency programs.

## Existing Approaches - *Optional*

Currently, if a bureau requires a program code that is not in the Federal Program Inventory, the recommendation is to use a “bogus code” as a placeholder, as data.gov validates only on the presence of the Program Code, and not the content, for all metadata designated as ‘federal’ data. However, this is not a valid long-term solution for bureaus that want to differentiate data assets and investments by program.

## Additional context, comments, or links - *Optional*

Data.gov can leverage the existing Federal Program Inventory to provide a current and accurate list of agency programs.

Original Email Submission:
[20230630_FWS-DMT_DCAT-US-3_Response_ProgramCode.docx](https://github.com/DOI-DO/dcat-us/files/12028951/20230630_FWS-DMT_DCAT-US-3_Response_ProgramCode.docx)

**Comment by fellahst** [comment]
Deprecated, See #110
