### ISSUE TITLE
Metadata version reference via relation field

### ISSUE THREAD

**Issue by jbrown-xentity** [DOI-DO/dcat-us#11]
**Creator Name:** James Brown
**Creator Affiliation:** GSA/data.gov

## Requirement(s)

Provide roadmap for extending relationship types to other resources, to allow for future building and flexibility. Utilize the super property `relation` [defined in DCAT-3](https://www.w3.org/TR/vocab-dcat-3/#Property:resource_relation), and implement a relation type that references other metadata files.

## Problem Statement

*Mandatory statement of the current situation, including:*
- Current data providers often feel it necessary to provide metadata in both DCAT-US and ISO, to satisfy data.gov and geoplatform
- DOI, USGS, NASA, etc...
- Current workaround is documented here: https://github.com/GSA/ckanext-datajson/tree/main/ckanext/datajson/tests/datajson-samples#geospatial-full-metadata-link-example

## Target Audience / Stakeholders

*Establish who the intended audience/stakeholders of the requirement are, and who will be impacted by this requirement.  When the describing the intended audience or stakeholder, please be as specific as possible (avoid using the term: user).*

Metadata experts, when mapping other metadata standards to DCAT

## Intended Uses / Use Cases

*The intended uses expected for the requirement, usually in the form of an imperative sentence starting with a verb each describing an individual task in order to solve the stated problem.*

- Use 1. Provide simpler and more integrated implementation for linking to different metadata standards for the same dataset record.
- Use 2. Provide path for extending DCAT more sustainably, and aligning with expected DCAT-3 standards

## Existing Approaches - *Optional*

https://github.com/GSA/ckanext-datajson/tree/main/ckanext/datajson/tests/datajson-samples#geospatial-full-metadata-link-example

## Additional context, comments, or links - *Optional*

Since Geoplatform doesn't currently accept or work with DCAT-US, we need something like this to connect these different metadata files representing the same dataset record in a long term, well defined, sustainable way...

**Comment by TDabolt** [comment]
@doi-jschlagel believe this is similar to FGDC requirement.

**Comment by fellahst** [comment]
This requirement has been addressed. See [Related Resources](https://doi-do.github.io/dcat-us/#related-resources) usage guideline section.
