### ISSUE TITLE
Link dataset resource to agency "program", "funder"and "investment"  

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#110]
**Creator Name:** John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

1. Specify links/citations to programs (zero or more _activities_) responsible for _owning/producing_ the data asset's creation/ maintenance. Similar to DCAT-US 1.1 [programCode](https://resources.data.gov/resources/dcat-us/#programCode) field but the range is a link (a URI identifier as a namespace-qualified code that is unique, meaningful and manageable) or citation to the program(s) responsible for the collection, generation, and/or maintenance of the dataset. 
NOTE:  Recommend that each bureau designate and manage and publish their own program codes as a publicly accessible  controlled vocabulary of programs (where the confederation of bureau-specific program lists can be periodically aggregated into a centralized vocabulary of relevant USG programs).
2. Specify links/citations to organization(s) (zero or more _agents_) responsible for _funding_ the data creation/ maintenance (or, indirectly, the primary `program`).  The range of "funder" must be a link (URI identifier, a namespace-qualified code that is  unique, meaningful and manageable) or a citation to the organization responsible for funding the collection, generation, and/or maintenance of the dataset. 
3. Specify links/citations to investment(s) (zero or more _activities_) primarily responsible for _funding and tracking_ the production and/or maintenance of the data. Similar to the DCAT-US 1.1 [primaryITInvestmentUII](https://resources.data.gov/resources/dcat-us/#primaryITInvestmentUII) field but the range is a link (a URI identifier as a namespace-qualified code that is unique, meaningful and manageable reference) or citation to the investment activity(ies) responsible for funding/tracking the collection, generation, and/or maintenance of the dataset.
NOTE: Recommend that each bureau designate and manage and publish their own investment codes as a publicly accessible controlled vocabulary (where the confederation of bureau-specific investment lists can be periodically aggregated into a centralized  vocabulary of relevant USG investments).

## Problem Statement

Cannot associate a dataset resource with government activity, mission, line of business or funding source. Having this contextual information directly supports FAIR principles for findability and reuseability.
 
## Target Audience / Stakeholders

1. Data Producer/ Data Owner/ Data Steward
2. Data Consumer/ SME/ Business Analyst

## Intended Uses / Use Cases

**UseCase-1**: As a data producer, I know which program the dataset is being created for and need to provide this information about the dataset so "downstream" consumers of the data do too.
**UseCase-2**: As a data owner, I know which agencies and investments have funded the generation and/or maintenance of the data asset and need to provide this valuable contextual information so "downstream" consumers of the data do too.
**UseCase-3**: As a data consumer, I want to find data assets by the program activities or investments indicating the purpose and use of the data asset (business rationale for the creation and use of the data asset)  
**UseCase-4**: As a data consumer, I want to find data assets by the organization or investment that funded them  (distinct from the organizations or activities that created, contributed to, or published them).

## Existing Approaches - *Optional*
 
1. See DCAT-US 1.1 [programCode](https://resources.data.gov/resources/dcat-us/#programCode)
2. See DCAT-US 1.1 [primaryITInvestmentUII](https://resources.data.gov/resources/dcat-us/#primaryITInvestmentUII) 
3. DCAT2/3 define relationships between data assets and agents using `prov:qualifiedAttribution`

## Additional context, comments, or links - *Optional*

A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by TDabolt** [comment]
Recommend dropping the requirement until required by statute or government wide policy to streamline implementation
