### ISSUE TITLE
DCAT-US Attribute that represents if a catalog record represents a geospatial or a spatial data asset.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#111]
**Creator Name:** Kathleen Donelson-Westover
**Creator Contact Information:** Title: IT Specialist (Data Architect/Data Engineer), Email: Kathleen_Donelson-Westover@fws.gov
**Creator Affiliation:** U.S. Fish and Wildlife Service, Information Resources and Technology Management, Enterprise Data Management Team

## Requirement(s)

DCAT-US Attribute that represents if a catalog record represents a geospatial or a spatial data asset. (Required for Data.gov catalog records published to GeoPlatform.gov).

## Problem Statement

The Department of the Interior (DOI) publishes geospatial catalog records to data.gov, which makes them available to Geoplatform for selection and ingest. The Geospatial Platform is a cross-agency collaborative effort and shared service that provides geographically enriched data. When DOI developed their DOI-DCAT-US 1.1 Application Profile, neither the Department, data.gov, the Federal Data Strategy, nor the DCAT-US 1.1 standard had defined a formal theme vocabulary. In the absence of a formal implementation of a theme vocabulary, a decision was made for GeoPlatform.gov to utilizing this field to identify data assets that are explicitly spatial in nature, and that may reference geospatial services of interest to GeoPlatform users. As a result of this decision, to publish to Geoplatform requires a catalog record to have the value of the Theme attribute to be “geospatial” to allow Geoplatform to identify a catalog record for ingestion. The DOI DCAT-US 1.1 Metadata Standard implemented this requirement in the Category/Theme/Genre attribute by requiring a “geospatial” or “not geospatial” Theme value.

A Department of the Interior enterprise data inventory software vendor raised concerns that using the Theme attribute to indicate a geospatial data asset incorrectly interpreted the W3C DCAT V2 Recommendation for the Theme attribute. The W3C DCAT Recommendation defines the attribute as a main category of the resource and assigns the RDF property dcat:themeTaxonomy. The W3C Recommendation advocates the use of a simple knowledge organization system (SKOS) used to classify the resources documented in the catalog.

## Target Audience / Stakeholders

User 1. Data consumers who require knowledge of and access to agency geospatial data assets published to GeoPlatform.gov.

## Intended Uses / Use Cases

Use 1. Agencies that publish geospatial data asset records to GeoPlatform.gov.

## Existing Approaches - *Optional*

There are two potential approaches to address this issue:

1) Create an authorized controlled vocabulary for property dcat:theme that has two values of “geospatial” and “non-geospatial”. This would satisfy the requirement for publishing to GeoPlatform.gov through the dcat:theme property. Additionally, this option would address an enterprise data inventory software vendor’s concern that the DCAT-US Application Profile incorrectly interprets the W3C DCAT V3 Recommendation for the Theme attribute. Of course, the DCAT working group must perform due diligence to ascertain if this option would affect GeoPlatform.gov’s ability to harvest geospatial data asset catalog records from data.gov.

2) Extend the DCAT-US Application Profile by adding an attribute with a controlled vocabulary consisting of the terms “geospatial” and “non-geospatial”. As this attribute requires a controlled vocabulary, it could use the property dcat:theme, instead of dcat:keyword. As previously mentioned, the DCAT working group must perform due diligence to ascertain how this option would affect GeoPlatform.gov.

## Additional context, comments, or links - *Optional*

GeoPlatform.gov can continue to identify and harvest geospatial records from Data.gov.

Original Email Submission: 
[20230630_FWS-DMT_DCAT-US-3_Response_Theme.docx](https://github.com/DOI-DO/dcat-us/files/12029016/20230630_FWS-DMT_DCAT-US-3_Response_Theme.docx)

**Comment by fellahst** [comment]
`Use the property dcterms:type` to classify the category of the dataset. See [Resource Classification ](https://doi-do.github.io/dcat-us/#resource-classification) guideline. Implementation phase will have to come out with a taxonomy of well-defined resource categories available from a registry.
