### ISSUE TITLE
Provide new elements to link a more robust metadata record and indicate the standard used to format the more robust metadata

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#112]
**Creator Name:** Vaishal Sheth
**Creator Contact Information:** Vsheth@contractor.usgs.gov
**Creator Affiliation:** Federal Geographic Data Committee (Support Team), National Geospatial Data Asset (NGDA) Community

## Requirement(s)

Provide new elements for:

- ‘comprehensive metadata’ - URL - to link a more robust metadata record
- ‘comprehensive metadata format’ - codelist – to indicate the standard used to format the more robust metadata, e.g., ISO 191**, CSDGM, MARC, EML, etc.

## Problem Statement

Many organizations use DCAT as a ‘discovery-level’ metadata record for publication to data catalogs but maintain more comprehensive metadata to support data fitness for use assessment and the application/use of the data or produce metadata in compliance with policy and practice, e.g., mandate to produce geospatial metadata for publication to the GeoPlatform

## Target Audience / Stakeholders

Scientific and geospatial data producers obligated to create comprehensive metadata that conforms to a community standard

## Intended Uses / Use Cases

- FAIR – Reuse - Identify relevant, available, scientific and geospatial data resources that can support a specific scientific initiative or endeavor
- FAIR – Reuse – Effectively and appropriately apply available, existing, geospatial and scientific data resources

## Existing Approaches - *Optional*

GeoPlatform currently requires publishers to document comprehensive geospatial metadata, published as either ISO 19115* or the CSDGM standard, by populating a DCAT ‘distribution’ element and [specifying specific content for the ‘conformsTo’, downloadURL, mediaType, and format fields](https://kb.geoplatform.gov/gp-faq/iso-csdgm-dcat.html). This requirement is extremely specific and non-intuitive and, therefore, often not fulfilled correctly.

## Additional context, comments, or links - *Optional*

OTHER Highly Relevant Recommendations Submitted the DOI-DO / DCAT-US Github Comment Repository:
- [11](https://github.com/DOI-DO/dcat-us/issues/11) - Metadata version reference via relation field (James Brown GSA/Data.gov)  
Provide roadmap for extending relationship types to other resources, to allow for future building and flexibility. Utilize the super property relation [defined in DCAT-3](https://www.w3.org/TR/vocab-dcat-3/#Property:resource_relation), and implement a relation type that references other metadata files.
    - Problem:
        - Current data providers often feel it necessary to provide metadata in both DCAT-US and ISO, to satisfy data.gov and geoplatform
        - DOI, USGS, NASA, etc... 
        - Current workaround is documented here: https://github.com/GSA/ckanext-datajson/tree/main/ckanext/datajson/tests/datajson-samples#geospatial-full-metadata-link-example
    -  Intended Uses:
        - Provide simpler and more integrated implementation for linking to different metadata standards for the same dataset record. 
 > Comment – Addresses same issue as the NEW recommendation above but this approach is simpler and more likely to be published by users 
- [21](https://github.com/DOI-DO/dcat-us/issues/21) - Make our open data sets compatible with Data.gov and other online harvesting or searching tools 
Provide an easy-to-use, flexible, and specific schema that makes our open data sets compatible with data.gov and other online harvesting or searching tools, and can be used to increase the SEO.

Content Suggestions 
- [24](https://github.com/DOI-DO/dcat-us/issues/24) - Identify the following data assets (and potential new data fields for the following data assets
- Identify the following data assets (add potential new data fields for the following data assets)
     - priority data assets 
     - Covid-related data assets 
     - data assets that support Artificial Intelligence research 
     - high-value geospatial data act investment-related data assets  
     - data assets that relate to interagency wildland fire fuels data management 
> Comment – Creates an opportunity to clearly identify National Geospatial Data Assets and to tag these as ‘geospatial’
- [18](https://github.com/DOI-DO/dcat-us/issues/18) - Conforms to field – set values
- Bringing in old issue -- should conforms to field have common values? 
- See [project-open-data/project-open-data.github.io#497](https://github.com/project-open-data/project-open-data.github.io/issues/497) 
     - References early request by Phil Ashlock (2015/Data.gov) 
          - Let's provide some kind of registry of common values to use for conformsTo ([#362](https://github.com/project-open-data/project-open-data.github.io/issues/362))
> Comment – interpreting this to mean that GeoPlatform ‘conformsto’ metadata standard reference requirements could be added to a registry of values. Would help to standardize content and facilitate Data.gov to GP publication 

Let's provide some kind of registry of common values to use for conformsTo ([#362](https://github.com/project-open-data/project-open-data.github.io/issues/362))

#### Other Relevant Recommendations Submitted the DOI-DO / DCAT-US Github Comment Repository: 
Alignment Issues 
- [13](https://github.com/DOI-DO/dcat-us/issues/13) - Consider work underway in OGC on standardizing GeoDCAT  
OGC has just started a new Standards Working Group (SWG) to create a GeoDCAT Standard. This SWG starts work on Monday, 5 June 2023. Interested parties may attend the meeting as part of the larger OGC Member Meeting by registering at meet.ogc.org. 
     - Response: GeoDCAT has been taken into consideration for the DCAT-US profile to represent spatio-temporal information of datasets and services. We will provide feedback to your effort.

Content Suggestions 
- [10](https://github.com/DOI-DO/dcat-us/issues/10) - Add metadata fields as suggested by language of OPEN Government Data Act 
The OPEN Government Data Act has provisions about require metadata. (See screenshots). Some are already in the existing schema at https://resources.data.gov/resources/dcat-us/ but others will require addition of new fields.
> Comment – Hyon Kim (Data.gov)  provides a great mapping of Open Government Data Act requirements 
- [15](https://github.com/DOI-DO/dcat-us/issues/15) - How to address Collections issue? (Hyon Kim)  
How do we deal with collections? Current schema reference https://resources.data.gov/resources/dcat-us/#isPartOf. Also bringing in existing issue in Project Open Data at [project-open-data/project-open-data.github.io#530](https://github.com/project-open-data/project-open-data.github.io/issues/530) A lot of opinions on this issue
> Comment – Inventory.Data.gov published recommendations for associating dataset parent/child relations using ‘isPartOf’ 

**Additional Comments:**  
Since this new standard supports geo/stats/other data types, does it attempt to include information that could be used to automate the process of identifying geo datasets (with feature geometry) and non-spatial datasets (statistical, other without feature geometry) in a way that will enable a machine or user to find data sets that can be used to spatially join the data?  This process helps bring geo and other Fed data types closer, and supports the GDA requirement of an NSDI goal, 2804. NSDI, that “(B) that geospatial data are designed to enhance the accuracy of statistical information, both in raw form and in derived information products”. This requires those data to be used together, where possible. 

Having a machine readable method to search coincidently for Fed data that has, for example, 1) geo address data, and 2) a flat table with addresses that can be used to map their locations (and therefore their spatial relationship to other variables like distance to service/client, etc.), will need to be developed and it seems this standard may be an initial way to begin enabling that by ensuring required labels and geotags are applied. 

The TOPICS field in the in many search engines featuring geospatial data do not enable users to access comprehensive or meaningful search results. The current DCAT revision process is the perfect opportunity to elevate and address the topic areas and improve keyword searches and results for both Data.gov and other portals, e.g., GeoPlatform. 

**General recommendations:** 
- ALL data: Provide an authoritative list of Bureau and program codes and IDENTIFIERS for data delivered and coded by federal agencies with Geospatial Data Collections. This standard list can ensure that agencies and bureaus have quick access to the geospatial collection of data delivered by their organization and for there to be a consistent implementation at all levels for every kind of data, i.e., all of the USGS, Census Bureau data. Geospatial data collections can be searched by agencies with globally unique IDENTIFIERS.  
- For all geospatial Data/NGDAs: The schema should include KEYWORDS and TAGS that are associated with the Data Themes topics that are searchable within the NGDA metadata. Consider adding NGDAIDs and theme names to the KEYWORD fields for Geospatial data collections. Provide guidance for searching, filtering, tracking to find the NGDAs within the data collection is needed. 
- Harmonize metadata with recommended improvements and metadata field guidance in the DCAT schema to enable datasets within an agency’s designated geospatial data collection to be more accessible through both the Data.gov and the GeoPlatform’s search engine. 

Original Email Submission:
[06302023_DCAT-US-3-Requirements-RFI_NGDA Theme_FGDC_Support Team.docx](https://github.com/DOI-DO/dcat-us/files/12029337/06302023_DCAT-US-3-Requirements-RFI_NGDA.Theme_FGDC_Support.Team.docx)

**Comment by fellahst** [comment]
This requirement has been addressed by introducing the propery `dcat-us:metadataDistribution`. See [Related Resources](https://doi-do.github.io/dcat-us/#related-resources) usage guideline section.
