### ISSUE TITLE
Update the CSDGM to POD, ISO 19115-2 to POD crosswalks to map to DCAT-US-3 rather than POD, and Create a crosswalk for ISO 19115-1 to DCAT-US-3

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#114]
**Creator Name:** Kathy Martinolich
**Creator Contact Affiliation:** Metadata Specialist/Research Associate, NOAA Affiliate
**Creator Affiliation:** Mississippi State University/Northern Gulf Institute

## Requirement(s)

Update the CSDGM to POD, ISO 19115-2 to POD crosswalks to map to DCAT-US-3 rather than POD. 

Create a crosswalk for ISO 19115-1 to DCAT-US-3

## Problem Statement

POD includes a crosswalk to CSDGM and to ISO 19115-2. This will need to be updated for the transition to ISO 19115-2 and for changes in the way that member organizations formulate their metadata.

## Target Audience / Stakeholders

Intended users are metadata project leads at various agencies. Also, metadata tool developers could use the crosswalks for transforms and other tools to convert metadata from another standard to the POD/DCAT standard.

## Intended Uses / Use Cases

Metadata standards can crosswalk to each other. However, the crosswalks can vary just as the
implementation of the various metadata standards differ. A crosswalk can help identify were standards
are similar and where they are different

## Existing Approaches - *Optional*

It would be helpful to have a downloadable Excel style spreadsheet of this product. The current
implementation is a table in the POD information. The table is a bit wonky because of the length of the
field entries.

## Additional context, comments, or links - *Optional*

It may be helpful to review this with the previous team members for feedback and suggestions, aka a retrospective.

Original Email Submission:
[DCAT-US-3-Requirements-martinolich-noaa-mwg.pdf](https://github.com/DOI-DO/dcat-us/files/12029505/DCAT-US-3-Requirements-martinolich-noaa-mwg.pdf)

**Comment by fellahst** [comment]
Duplicate with #77
