### ISSUE TITLE
Controlled Vocabularies for Keywords (GCMD, WORMS, ITIS, ICES, ISSCFG, etc)

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#115]
**Creator Name:** Brianna Key
**Creator Contact Affiliation:**  Data Manger; Brianna.key@noaa.gov
**Creator Affiliation:** NOAA/NOS

## Requirement(s)

Controlled Vocabularies for Keywords 
- GCMD 
- WORMS 
- ITIS 
- ICES 
- ISSCFG 
- etc. 

## Problem Statement

Currently, keywords are included in DCAT but not in controlled vocabularies. Controlled vocabularies increase the FAIRness of datasets.  

All users and submitters to data.gov are experiencing this issue. 

## Target Audience / Stakeholders

Everyone who uses data.gov for specific research and have experience with keywords. 

## Intended Uses / Use Cases

FAIRness of data 

## Existing Approaches - *Optional*

- ISO 19115-2 
- CSDGM 

## Additional context, comments, or links - *Optional*

Original Email Submission:
[DCAT-US-3-Requirements_Controlled Vocab.docx](https://github.com/DOI-DO/dcat-us/files/12029546/DCAT-US-3-Requirements_Controlled.Vocab.docx)

**Comment by fellahst** [comment]
The requirement is addressed in DCAT-US 3.0 using SKOS controlled vocabularies. See the [resource classification usage guideline](https://doi-do.github.io/dcat-us/#resource-classification) section in the spec.
