### ISSUE TITLE
Restrict each `Distribution` to a single access method _and_ explicitly indicate the `Distribution` method

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#116]
**Creator Name:**  John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

1. Constrain each `distribution` instance to a single access method property i.e., `accessURL` , `downloadURL` , `accessService` , other 
2. Explicitly indicate the type or method of a `distribution` instance with a 1st class property (e.g., `Distribution.method`)  

## Problem Statement

Humans and software cannot distinguish the type of distribution (indirect access, direct download, API, web page, etc.) and therefore how to use them (or which are most appropriate for their needs). Software has to "introspect" each distribution instance for existance of the relevant property (accessURL, downloadURL, accessService) to determine the kind of distribution method.

Linking to a DCAT "access service" metadata (https://www.w3.org/TR/vocab-dcat-3/#Property:distribution_access_service) is awkward and, from real-world experience, won't be (consistently) implemented because (among other reasons):
1. the organizations responsbile for producing the metadata for a dataset are different than those responsible for producing/ maintaining services, 
2. the dataset and related services have different lifecycles and governance/management processes.
3. data services are rarely documented with metadata, their endpoint URLs change  (sometimes frequently), and the services change independently of the dataset resource

## Target Audience / Stakeholders

**Actor1**: Data consumer/ SME/ Analyst
**Actor2**: Application software

## Intended Uses / Use Cases

**UseCase1**: Application software needs to know how to handle different methods of dataset distributions (indirect access, direct access, API, web page) in order to present them to users via UI and then how to present/handle them after a user selects one.
 
## Existing Approaches - *Optional*

1. DCAT3 provides only vague (confusing) guidance how to distinguish/ use the various methods of distributions
 
## Additional context, comments, or links - *Optional*
A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by fellahst** [comment]
Updated [Distribution metadata guideline](https://doi-do.github.io/dcat-us/#distribution-guideline) addressing this issue.
