### ISSUE TITLE
Indicate when an agency has not made an open government data asset determination

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#119]
**Creator Name:** Chief Data Officer Council (CDOC)
**Creator Affiliation:** 

## Requirement(s)

Add a new domain value for the DCAT-US 1.1 `accessLevel` property, such that agencies may indicate when they have not made an open government data asset determination.

## Problem Statement

Determining the level of access is a process the responsible agency must implement and includes updating the metadata to indicate the determination. There is currently no way to indicate that a determination has not been made.

**Comment by fellahst** [comment]
The `accessLevel` property is no longer in use and has been replaced by [dcat-us:AccessRestriction](https://doi-do.github.io/dcat-us/#properties-for-access_restriction). The [restrictionStatus](https://doi-do.github.io/dcat-us/#access_restriction-restriction_status) property now utilizes a range of [skos:Concept ](https://doi-do.github.io/dcat-us/#properties-for-concept) from NARA, including options such as [restricted-full, restricted-partial, restricted-possible, undetermined, unrestricted]. These code lists are represented as SKOS concepts, detailed in the [NARA restriction vocabulary](https://www.archives.gov/research/catalog/lcdrg/elements/access.html#:~:text=Use%20%22Restricted%20%2D%20Partly%22%20if,restrictions%20on%20the%20archival%20materials.) available here: [NARA Restriction Vocabulary](https://github.com/DOI-DO/dcat-us/blob/main/vocabularies/nara-restrictions.ttl).

**Comment by TDabolt** [comment]
The NARA restriction vocabulary clearly includes "undetermined which satisfies the requirement.   - Resolved
