### ISSUE TITLE
Fully embed the approved metadata format within the data and Provide GIS data users with origin and appropriate use information

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#120]
**Creator Name:** Amos Desjardins
**Creator Contact Information:** Geospatial Governance Lead, [amos.desjardins@hq.dhs.gov](mailto:amos.desjardins@hq.dhs.gov)
**Creator Affiliation:** Department of Homeland Security, Geospatial Management Office 

## Requirement(s)

Adopted metadata standards should be fully compatible with industry-standard geospatial formats for vector and raster-based datasets. The ability to fully embed the approved metadata format within the data is critical to ensure the lineage, usability, and authenticity of data sets.  

Updates to the DCAT-US profile should include all the geospatial components of the current ISSO standards. This should include but is not limited to the following. 

- Geoprocessing History 
  - When processed 
  - Methods used for data processing 
  - Data lineage 
- Spatial Data Representation 
  - Reference system 
  - Vector 
    - geometry type 
    - bounding coordinates 
    - collection method 
  - Raster 
    - resolution  
    - bounding coordinates 
    - collection method 

In addition to geometry and spatial referencing information, new metadata standards should also include. 

- Security Classification 
  - Security Classification  
  - Classifying Agency  
  - Security Handling Description 
  - Distribution Information  
  - Derivative classification information 
- Collection standards 
  - Collection Methodology  
  - AI Generated/Processes  
- ISO Data Quality attributes 
  - Gridded data positional accuracy 
  - Relative Internal positional accuracy 
  - Non qualitative attribute accuracy 
  - Qualitative attribute accuracy 
  - Temporal consistency 
  - Absolute external positional accuracy 
  - Accuracy of a time measurement 
- ISO Time Period attributes 
  - Begin position 
  - End position 
  - Duration 
  - Time interval 
  - Data expiration (Adding) 

To provide a detailed list of all data fields needed to meet the needs of DHS components more time would be needed. DHS GMO staff would need to complete a full survey of all data being collected within the agency and pertinent fields needed by data users. 

## Problem Statement

New geospatial standards being created for the purpose of cataloging metadata should be comprehensive and include all metadata fields needed by geospatial professionals to ensure the usability and authenticity of the data. To ensure all data is usable within the federal government the ability to embed data standards within datasets is critical. Ensuring orphaned data can be accounted for and used is foundational to developing metadata standards. Data users should be able to access information on how data was collected, who collected the data, when it was collected, and any alterations done to the data set should be documented in the metadata. Metadata should also include basic information on the type of data, data accuracy and how the data was collected. Foundational geometry data including reference systems, projections and data accuracy are also critical for data end users. New metadata standards should be compatible with IT system infrastructures. 

## Target Audience / Stakeholders

User 1.  Providers of Data to HIFLD  
- Commercial vendors 
- State and local government 
- Federal agencies 
- Non-Governmental organizations 
- Tribes and territories 
- Crowdsourced 

User 2.  Consumers of DataServices/APIs 
- Homeland Security enterprise 
  - State and local government 
  - Federal agencies 
  - Non-Governmental organizations 
  - Tribes and territories 
- Private sector 
- Public 
- Educational institutions 

## Intended Uses / Use Cases

- Ensure Metadata is embedded within datasets and cannot be separated thereby rendering the data unusable or at risk of misuse. 
- Provide GIS data users with origin and appropriate use information to ensure data is handled appropriately in accordance with licensing agreements and handling instructions. 
- Provide users with source and contact information so that data owners can be contacted for questions and concerns regarding data. 

## Existing Approaches - *Optional*

DCAT 3.0 Should include all applicable geospatial related metadata currently within ISO standards.

## Additional context, comments, or links - *Optional*

Original Email Submission:
[DCAT-US-3-Requirements-DHS GMO.docx](https://github.com/DOI-DO/dcat-us/files/12112117/DCAT-US-3-Requirements-DHS.GMO.docx)

**Comment by fellahst** [comment]
Thank you for your detailed input regarding the adoption of metadata standards compatible with industry-standard geospatial formats for vector and raster-based datasets. Your emphasis on embedding approved metadata formats within datasets to ensure lineage, usability, and authenticity is well-noted.

While the embedding of DCAT metadata directly within all dataset formats may not be feasible, we recognize the critical importance of ensuring that geospatial datasets, in particular, carry comprehensive metadata that is accessible and usable. To address this, the following approaches have been adopted:

1. **Adherence to Industry Standards:**
   - Updates to the DCAT-US profile aims to align with current ISO standards, encompassing aspects such as classification, history, spatial data representation, security classification, distribution information, and ISO data quality attributes.

2. **External Metadata Files:**
   - For data formats where embedding metadata directly is not feasible, we recommend the use of external metadata files linked to the datasets. These files should adhere to a standardized format, ensuring comprehensive and accessible information.
