### ISSUE TITLE
Ensure fields for Metadata/Provider source, dataset title, date/time information, storage volume, and useful hyperlinks are present

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#121]
**Creator Name:** Brianna Key
**Creator Contact Information:** Data Manger; Brianna.key@noaa.gov
**Creator Affiliation:** NOAA/NOS

## Requirement(s)

- Source of the metadata, or the provider 
- Dataset Title 
- Date/Time information 
- Storage volume - so users know how much data is available 
- Useful Hyperlinks 

## Problem Statement

These are common metadata fields, that reside in most metadata records I've seen for NOAA 

## Target Audience / Stakeholders

Everyone  

## Intended Uses / Use Cases

- ISO 19115-2 
- CSDGM 

## Additional context, comments, or links - *Optional*

Original Email Submission: 
[DCAT-US-3-Requirements_Fields.docx](https://github.com/DOI-DO/dcat-us/files/12254185/DCAT-US-3-Requirements_Fields.docx)

**Comment by fellahst** [comment]
Brianna,

Thank you for reaching out with your inquiry regarding common metadata fields in the context of the DCAT-US specification. Below, I have outlined the relevant sections from the DCAT-US documentation that correspond to your requirements:

1. **Source of the Metadata / Provider**: For identifying the source or provider of the metadata, the `dct:creator` property is used in the DCAT-US specification. This property specifies an entity primarily responsible for making the resource. You can find more details in the section on [Stakeholders](https://doi-do.github.io/dcat-us/#stakeholders) and [Resource Attributions](https://doi-do.github.io/dcat-us/#resource-attributions).

2. **Dataset Title**: The dataset title can be specified using the `dct:title` property, which provides a descriptive name to the dataset. Further information is available under [Dataset Title](https://doi-do.github.io/dcat-us/#dataset-title).

3. **Date/Time Information**: To represent date/time information, the properties `dct:temporal`, `dct:issued`, and `dct:modified` are used. These fields capture relevant temporal data about the dataset. Please see [Dataset Temporal Coverage](https://doi-do.github.io/dcat-us/#temporal-metadata) for more specifics.

4. **Storage Volume**: The `dcat:byteSize` property indicates the size of the dataset's distribution in bytes, providing an estimate of the required storage volume. Details on this can be found in [Distribution Byte  Size](https://doi-do.github.io/dcat-us/#distribution-byte-size).

5. **Useful Hyperlinks**: For hyperlinks to access or download the dataset, `dcat:accessURL` and `dcat:downloadURL` are the relevant properties. These are detailed in the section on [Distribution Metadata](https://doi-do.github.io/dcat-us/#distribution-guideline).

Given your role at NOAA/NOS and the mention of ISO 19115-2 and CSDGM, it’s crucial to consider specific adaptations or mappings to align DCAT-US with these geospatial metadata standards. For a comprehensive understanding of how DCAT-US can be applied within NOAA's context, I recommend reviewing the entire DCAT-US specification, alongside any NOAA-specific metadata management guidelines.
