### ISSUE TITLE
Add Controlled Vocabulary for Congressional Policy Areas

### ISSUE THREAD

**Issue by doi-jschlagel** [DOI-DO/dcat-us#122]
Joel Schlägel
Geoplatform.gov

## Requirement(s)

ISO 19115 Topic areas are commonly used to categorize geospatial metadata.   For metadata profile that goes beyond geospatial data, a broader set of topics are needed.   As no standardized federal controlled vocabulary for topics exists, consider using https://www.congress.gov/help/field-values/policy-area.   

This would allow metadata search to be aligned to a well defined authoritative (Congressional) categorization.

From Congress.gov  "One of 32 broad policy area terms is assigned to every bill and resolution by legislative analysts in the Congressional Research Service upon the release of official text by the Government Publishing Office. The term chosen is the one that best describes the focus or predominant subject matter of each measure."

*Mandatory statement of the current situation, including:*
- *Metadata search without standard categories is ineffective *
- *all communities seeking to use federal data*

**Comment by fellahst** [comment]
DCAT-US is intentionally designed to be agnostic regarding the choice of controlled vocabularies. This flexibility allows individual communities and agencies to select the vocabularies that best suit their specific needs and domains, whether it's the Library of Congress Subject Headings, the [GCMD](https://skosmos.aeris-data.fr/gcmd/en/) for Earth Science, or any other specialized taxonomy. This should be addressed during the implementation phase See more details in [Resource Classification](https://doi-do.github.io/dcat-us/#resource-classification) usage guideline
