### ISSUE TITLE
Consider using Library of Congress Subject Heading as "Subject" for DCAT-US

### ISSUE THREAD

**Issue by doi-jschlagel** [DOI-DO/dcat-us#123]
Joel Schlegel 
Geoplatform.gov

## Requirement(s)

Consider using Library of Congress Subject headings as controlled vocabulary.    Over 400,000 concepts are defined and available as linked data for inclusion within federal systems.

https://id.loc.gov/search/?q=cs:http://id.loc.gov/authorities/subjects

for example:  https://id.loc.gov/authorities/subjects/sh2003005458.html

see:  

Term Name: subject
--
URI | http://purl.org/dc/terms/subject
Definition | A topic of the resource.
Comment | Recommended practice is to refer to the subject with a URI. If this is not possible or feasible, a literal value that identifies the subject may be provided. Both should preferably refer to a subject in a controlled vocabulary.
Type of Term | Property
Subproperty of | Subject (http://purl.org/dc/elements/1.1/subject)

https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#subject

**Comment by ungricht** [comment]
This will not work for us.  The LCSH could be referenced by the agencies that need to use it, but for us it will be overly burdensome if we use the DCAT-US schema.

**Comment by fellahst** [comment]
Joel,

Absolutely, you've highlighted a key aspect of the DCAT-US framework. DCAT-US is intentionally designed to be agnostic regarding the choice of controlled vocabularies. This flexibility allows individual communities and agencies to select the vocabularies that best suit their specific needs and domains, whether it's the Library of Congress Subject Headings, the [GCMD](https://skosmos.aeris-data.fr/gcmd/en/) for Earth Science, or any other specialized taxonomy. This should be addressed during the implementation phase
