### ISSUE TITLE
Take into consideration a granular way to forbid crawlers from indexing/harvesting select resources

### ISSUE THREAD

**Issue by jqnatividad** [DOI-DO/dcat-us#125]
**Name:**  Joel Natividad

**Affiliation:** datHere, Inc.

**Type of issue:**  **General Comment**

**Issue:** 
The rich machine-readable metadata exposed by the spec will be a gold-mine for crawlers - not only for search engines, but for training data for AI models as well.

It'd be great if there is a granular way that data publishers can have the ability to mark select resources as **NOT** harvestable/crawlable for indexing/inferencing purposes.

As it happens, Google is convening a discussion on exactly this topic.

> As new technologies emerge, they present opportunities for the web community to evolve standards and protocols that support the web’s future development. One such community-developed web standard, [robots.txt](https://www.rfc-editor.org/rfc/rfc9309.html), was created nearly 30 years ago and has proven to be a simple and transparent way for web publishers to control how search engines crawl their content. We believe it’s time for the web and AI communities to explore additional machine-readable means for web publisher choice and control for emerging AI and research use cases.

https://blog.google/technology/ai/ai-web-publisher-controls-sign-up/

I recall when [schema.org was announced in June 2011](https://developers.google.com/search/blog/2011/06/introducing-schemaorg-search-engines) by Google, Bing and Yahoo days before the Semantic Technology Conference and most [attendees were caught by surprise](http://strangelove.netlabs.org/2011/06/schema-org-not-too-impressive/) by the development as the [spec was developed largely outside the usual standards groups](https://www.dataversity.net/semtechs-schema-org-panelists-talk-openness-adoption-interoperability/).

Since then, schema.org has been more transparent and worked with the community to evolve the spec. And sure enough, it has become the de facto standard for semantic markup on the web.

**Recommended change(s):**
IMHO, DCAT-US v3 is certain to be used outside of traditional open data/government data interoperability use-cases as it aims to "_provide a **single metadata standard** able to support most requirements for documentation of business, technical, statistical, and geospatial data consistently_" and it'd be prudent to actively engage the search engine and AI firms who I'm certain will harvest the metadata at scale.

**Comment by jqnatividad** [comment]
Even with the judicious use of [`AccessRestriction`](https://doi-do.github.io/dcat-us/#properties-for-access_restriction) and [`UseRestriction`](https://doi-do.github.io/dcat-us/#properties-for-use_restriction) using [NARA](https://www.archives.gov/research/catalog/lcdrg/elements/access.html) [standards](https://www.archives.gov/research/catalog/lcdrg/elements/use.html), a lot of information can still be inferred from other mandatory fields.

Consider adding best practice guidelines and perhaps, adding additional controls specifically for Search Engine/AI crawlers when the Implementation Guidance is created.

**Comment by fellahst** [comment]
Joel,

Thank you for your submission regarding the potential use of DCAT-US metadata by web crawlers and AI models. While your suggestion to include a mechanism for publishers to mark resources as non-harvestable is insightful, it falls outside the scope of the DCAT-US specification. DCAT-US primarily focuses on defining a standard for data documentation and interoperability, particularly in government and open data contexts. Issues related to the control of data indexing and its use by emerging technologies, though important, pertain more to broader web standards and protocols, such as those discussed in the context of schema.org and similar initiatives. We recommend addressing these concerns through forums specifically dedicated to web publishing and AI interaction standards.  A usage guideline has been provided for [Legal Metadata](https://doi-do.github.io/dcat-us/#legal-metadata) in the spec.
