### ISSUE TITLE
Rewrite "Application Areas" section for readability/clarity

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#126]
**Name:**  John Davidson

**Affiliation:** Image Matters

**Type of issue:**  Editorial 

**Issue:** 
Link to section: https://doi-do.github.io/dcat-us/#area-of-application 
Bad grammar. Rewrite for understandability/clarity.

**Recommended change(s):** _[enter your recommended changes to correct the issue below]_
Change entire section to read:

> The DCAT Application Profile for data portals in the United States (DCAT-US) is an Application Profile of the DCAT vocabulary.
> * The “Data Catalog Vocabulary” (DCAT) is a semantic language for describing data by means of an RDF vocabulary. It allows for a decentralized and interoperable approach for publishing and finding data by use of a common language for describing data.
> * DCAT is a generic language that can be applied in various contexts. An Application Profile applies the DCAT vocabulary to a specific domain, context, or application, with the goal of facilitating data discovery, access, and sharing. The DCAT-US application profile addresses specific requirements of the U.S. Government (laws, regulations, and policies) and other needs of U.S. data producers and consumers.
> * The DCAT-US Application Profile provides the guidance needed for data publishers to specify their data catalogs and for data portal managers to process data catalogs. DCAT-US specifies the schema for metadata -- data describing data that can be validated for correctness and completeness.  Metadata is by definition secondary information about the data: when and by whom were they published, which usage conditions apply, how often are they updated, whom to contact about them, and where and how can they be accessed.

**Comment by fellahst** [comment]
Done
