### ISSUE TITLE
Consider adding specific guidance to encourage usage of the Census GEOID as a controlled vocabulary for geospatial metadata

### ISSUE THREAD

**Issue by jqnatividad** [DOI-DO/dcat-us#128]
**Creator Name:**  Joel Natividad
**Creator Affiliation:**  datHere, Inc.

## Requirement(s)

In [16.6.4 Other controlled vocabularies](https://doi-do.github.io/dcat-us/#other-controlled-vocabularies), for geospatial metadata:

> the working group has identified the following additional vocabularies:
> 
> ### Geographic identifiers:
> 
> **For marine regions:**
> 
> * Marine Regions http://www.marineregions.org/
> 
> * SeaVoX salt and fresh water body gazetteer - https://www.bodc.ac.uk/data/codes_and_formats/seavox/
> 
> **General:**
> 
> * DBpedia for Geographic Placenames - http://dbpedia.org/about
> 
> * National gazetteer vocabularies where feasible
> 
> * SeaVoX salt and fresh water body gazetteer for ‘marine geonames’ - https://www.bodc.ac.uk/data/codes_and_formats/seavox/
>

For the "National gazetteer vocabularies where feasible", perhaps, specifically call out using [GEOIDs](https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html) for US places?

Better yet, consider making it one of the Controlled vocabularies to be used in [16.6.3](https://doi-do.github.io/dcat-us/#controlled-vocabularies-to-be-used ) for `dct:spatial`?

## Problem Statement

GEOIDs are already universally used by the US Census and other statistical agencies for their data products. By making it a controlled vocabulary for `dct:spatial`, mapping/cross-walking geospatial datasets from other organizations against Census data would be much easier.

## Target Audience / Stakeholders

Everyone.

## Intended Uses / Use Cases

From the [Census GEOID page](https://www.census.gov/programs-surveys/geography/guidance/geo-identifiers.html):

> ### Why Are GEOIDs Important?
> GEOIDs are very important for understanding and interpreting geographic and demographic data and their relationship to one another. Data users rely on GEOIDs to join the appropriate demographic data from censuses and surveys, such as the American Community Survey (ACS), to various levels of geography for data analysis, interpretation and mapping. Without a common identifier among geographic and demographic datasets, data users would have a difficult time pairing the appropriate demographic data with the appropriate geographic data, thus considerably increasing data processing times and the likelihood of data inaccuracy.

**Comment by TDabolt** [comment]
Thank you for the suggestion and feedback.  We will discuss this with the Federal Geospatial Community and consider it applicability for future releases.
