### ISSUE TITLE
Consider Semantic Versioning for Datasets

### ISSUE THREAD

**Issue by jqnatividad** [DOI-DO/dcat-us#129]
**Creator Name:** Joel Natividad
**Creator Affiliation:** datHere, Inc.

## Requirement(s)

In [section 6.14 Versioning](https://doi-do.github.io/dcat-us/#versioning):

> DCAT relies on established vocabularies, including the versioning section of the PAV ontology and terms from [[PAV](https://doi-do.github.io/dcat-us/#bib-pav)], [[DCTERMS](https://doi-do.github.io/dcat-us/#bib-dcterms)], [[OWL2-OVERVIEW](https://doi-do.github.io/dcat-us/#bib-owl2-overview)], and [[VOCAB-ADMS](https://doi-do.github.io/dcat-us/#bib-vocab-adms)].

which is well and good as they are robust and widely adopted. However, the version numbers by themselves do not have meaning.

In the software industry (which produces the bulk of the datasets we're cataloging), [Semantic Versioning](https://semver.org) is widely used.

Semantic Versioning 2.0 specifies:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backward compatible manner
> PATCH version when you make backward compatible bug fixes
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format. 

Perhaps, the team can adapt a **Semantic Versioning variant for Data?**  This could well be:

 Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make **incompatible SCHEMA changes**
MINOR version when you make **SCHEMA changes in a backward compatible manner** (i.e. add additional columns) 
PATCH version when you make **DATASET CONTENT corrections** (e.g. Data Quality issues - typos, erroneous data, missing data, etc.)
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

Examples using the [Manufactured Housing Survey Public Use File published by the US Census](https://www.census.gov/data/datasets/2021/econ/MHS/puf.html):
* puf2022-v0.1.0.xls - initial internal draft, with the schema and some sample entries
* puf2022-v0.5.0.xls - internal draft 5 minor versions later, with each minor version adding additional columns and entries
* puf2022-v1.0.0-alpha.xls - alpha version of dataset for internal departmental review
* puf2022-v1.0.0-beta.xls - beta version of data for internal departmental review
* puf2022-v1.0.0-rc1.xls - first release candidate for public release awaiting approval for release
* puf2022-v1.0.0.xls - first public release of dataset
* puf2022-v1.0.1.xls - first corrected version of the public release (several typos found)
* puf2022-v1.1.0.xls - first amended version of the public release, adding several columns
* puf2022-v2.0.0.xls - v2 of the dataset with breaking schema changes, renaming several columns

## Problem Statement

Schemes like PAV focuses on provenance and the hierarchy of precedent and subsequent versions. The version numbers themselves do not have intrinsic meaning.  With this versioning scheme, users can decipher the version of a dataset file at a glance.

Further, if this versioning scheme is extended to a file naming convention:

 `[file-stem name]-v[data-semantic-version].[file-extension]`

Users can quickly know the version of a dataset from its file name, should they not have access to the version metadata.

## Target Audience / Stakeholders

Everyone.

## Intended Uses / Use Cases

* Catalog users, by the time they get access to the data, often handle the data at the file level, where they often do not have access to the metadata, never mind, the version metadata. Adding a standard file naming convention with embedded semantic versioning should help.
* Data ingestion pipelines could leverage the semantic version in the file name to screen files before ingestion (e.g. if a breaking schema change is indicated by the major version, do not even start ingestion)
* Data production pipelines can automatically produce datasets using the semantic versioning file naming convention.
* Data Cataloging software can automatically generate or nudge Data Publishers to name the datasets per the standard. Data exports can also automatically be named using the convention.

## Existing Approaches 
There is some prior art here - https://medium.com/data-architect/semantic-versioning-for-data-products-2b060962093

**Comment by fellahst** [comment]
This issue has been addressed in the [Versioning](https://doi-do.github.io/dcat-us/#versioning) usage guideline
