### ISSUE TITLE
Consider work underway in OGC on standardizing GeoDCAT

### ISSUE THREAD

**Issue by ogcscotts** [DOI-DO/dcat-us#13]
Submitter: Scott Simmons, Open Geospatial Consortium (OGC)

OGC has just started a new Standards Working Group (SWG) to create a GeoDCAT Standard. This SWG starts work on Monday, 5 June 2023. Interested parties may attend the meeting as part of the larger OGC Member Meeting by registering at meet.ogc.org.

More information on GeoDCAT can be found here:
https://inspire.ec.europa.eu/good-practice/geodcat-ap

and here:
https://portal.ogc.org/files/?artifact_id=82475

**Comment by fellahst** [comment]
Scotts,

Thank you for your interest and your pointers. GeoDCAT has been taken into consideration for the DCAT-US profile to represent spatio-temporal information of datasets and services. We will provide feedback to your effort.
