### ISSUE TITLE
Provide specific guidance on how Workbook spreadsheets are populated

### ISSUE THREAD

**Issue by jqnatividad** [DOI-DO/dcat-us#131]
**Creator Name:** Joel Natividad
**Creator Affiliation:** datHere, Inc.

## Requirement(s)

Spreadsheets are a popular data format in wide use in data catalogs. Spreadsheet workbooks support multiple sheets. Data owners/publishers often use these sheets to organize and partition their data for human consumption. These often results in non machine-readable data.

Specify sheet usage and naming conventions, so the flexibility of spreadsheets is retained, while preserving its machine-readability.

A possible convention could be:
The first sheet is human-readable and can have all the formatting and decorations afforded by the spreadsheet software.

The last sheet, perhaps labeled with a standard name (e.g. "machine-readable"), will have the machine-readable version of the data in the preceding sheets.

There are even existing mechanisms in spreadsheet software that can be easily leveraged to automatically copy just the values to this "machine-readable" sheet.

## Problem Statement

Data owners/publishers often take advantage of spreadsheet features to format, annotate and calculate values for their main human customers.

However, these often make the spreadsheet not machine-readable.

## Target Audience / Stakeholders

Everyone.

## Intended Uses / Use Cases

* with one spreadsheet file, Data Publishers can attend to the needs of both human and machine customers.
* when spreadsheets are downloaded/distributed from Catalog systems, the last "machine-readable" sheet can be automatically/optionally added by the system if its not present

**Comment by fellahst** [comment]
@jqnatividad,

Thank you for your detailed suggestion regarding the use of spreadsheets in data catalogs and the proposal to standardize sheet usage for both human-readable and machine-readable data within the DCAT-US framework. Your idea to utilize the first sheet for human-readable content and a final sheet labeled "machine-readable" for data consumption by automated systems is innovative and acknowledges the practical challenges faced by data publishers and users.

However, after careful consideration, we must inform you that this specific proposal falls outside the scope of the DCAT-US effort. The DCAT-US specification primarily focuses on providing a vocabulary for describing datasets in data catalogs. It aims to enhance discoverability and interoperability of datasets across different platforms and does not extend to prescribing data formatting or storage methodologies within individual data files, such as spreadsheets.

That said, your suggestion highlights a significant aspect of data publishing — balancing the needs of human users with the requirements of machine processing. While DCAT-US itself does not set standards for data file formats or internal organization, it encourages data publishers to consider the accessibility and machine-readability of their data, adhering to best practices and industry standards where applicable.

We recognize the value in your proposal for organizations and data publishers to consider as part of their internal data management and publishing strategies. Such conventions could indeed improve the usability of spreadsheet data for diverse audiences. We suggest this concept might be more appropriately explored in forums or working groups dedicated to data publishing best practices or specific data format standards.

Thank you for your engagement and for sharing your ideas. We appreciate your efforts to enhance the utility and accessibility of data published in data catalogs. Please feel free to reach out if you have further suggestions or questions related to the DCAT-US specification.

**Comment by jqnatividad** [comment]
Thank you @fellahst for your thorough review and consideration of our suggestion.

Having been involved in the deployment of dozens of portals across all levels of government in the US since 2012, I've personally seen how spreadsheets are widely used and oftentimes, even preferred by both publishers and end-users, as it is easily more understandable and digestible than machine-readable formats like CSV and JSON.

At the same time, I understand why this specific suggestion is outside the scope of DCAT-US, and even DCAT in general.

Per your suggestion, we will pursue this spreadsheet publishing convention with interested communities of practice we're currently involved in.

We will also create a reference implementation and ensure the "machine-readable" sheet hews closely to the DCAT-US specification.

**Comment by fellahst** [comment]
Thanks for your response. Please keep us updated about your progress.
