### ISSUE TITLE
Provide guidance for a standard way to sign datasets to ensure their authenticity

### ISSUE THREAD

**Issue by jqnatividad** [DOI-DO/dcat-us#132]
**Creator Name:**  Joel Natividad
**Creator Affiliation:**  datHere, Inc.

## Requirement(s)

Provide a standard way to sign and authenticate dataset packages/distributions. [NIST's FIPS 186-5](https://csrc.nist.gov/pubs/fips/186-5/final) (published February 3, 2023) is a perfect candidate for this.   

In this way, there will be a universal, standard way to authenticate datasets.

## Problem Statement

[Section 5.32 Provenance Statement](https://doi-do.github.io/dcat-us/#properties-for-provenance-statement) currently is set as free text (xsd:String).

Apparently, this is so as to afford flexibility to publishers per 5.32's Rationale.

However, even the Rationale anticipates the use of structured data for this property.

> Introducing [dcterms:ProvenanceStatement](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#terms_Provenance%20Statement) in DCAT-US 3.0 enhances dataset transparency and trustworthiness. It allows **_data publishers to provide structured information_** about significant changes in ownership and custody, aligning with international data quality and provenance standards. This flexibility ensures greater confidence in dataset authenticity and interpretation, promoting responsible data usage within DCAT-US. (highlight mine)

Providing best practice guidance on how data publishers who do opt to sign their datasets, can do so in a standard, machine-readable way. Perhaps, by using a prescribed JSON structure in the free text that is both machine and human-readable.

## Target Audience / Stakeholders

Everyone.

## Intended Uses / Use Cases

* Users can verify that the dataset is authentic
* When harvesting other DCAT-US 3 compliant catalogs, the datasets can be automatically verified

**Comment by hkdctol** [comment]
P2
