### ISSUE TITLE
Clarify definition of Liability Statement

### ISSUE THREAD

**Issue by hmaier-fws** [DOI-DO/dcat-us#136]
**Name:**  Hilmar Maier

**Affiliation:** U.S. Fish and Wildlife Service, Alaska Region

**Type of issue:** **Schema** (class definition)

# Issue:

Clarify definition of [Liability Statement](https://doi-do.github.io/dcat-us/#properties-for-liability_statement)

A "liability statement" is a disclaimer intended to avoid being held "legally responsible" for some action (see: https://www.law.cornell.edu/wex/disclaimer, https://www.law.cornell.edu/wex/liability). The current definition is overly broad and conflates existing use restrictions/constraints with legal liability issues. For example, the "usage notes" indicate that the liability statement should provide information regarding several properties including:

  - The accuracy or completeness of the dataset and
  - Limitations on how the dataset may be used

The above properties are more appropriate for inclusion in the proposed "[UseRestriction](https://doi-do.github.io/dcat-us/#properties-for-use_restriction)" class, which is described as: "..._a set of rules, guidelines, or legal provisions that dictate how a particular resource, asset, information, or object can be utilized_".

Essentially, the "liability statement" should be used to say that if you don't read the "use restrictions", don't blame use for your problems! 

# Recommended change(s):

Restrict the definition to properties that relate directly to a limitation of legal liability. Proposed definition change

**from**: A formal declaration accompanying a dataset [**delete:** *which outlines the responsibilities and limitations of the data provider in terms of the accuracy, completeness, and potential use of the data. It often serves*] `intended` to limit the legal exposure of the data provider by [**delete:** *defining the scope of allowed uses and*] disclaiming warranties or guarantees.

**to**: A formal declaration accompanying a dataset intended to limit the legal exposure of the data provider by disclaiming warranties or guarantees.

This would also better align DCAT-US with the widely used CSDGM and ISO 19115-series of metadata standards. Import of metadata from those standards could then be accomplished without the need to concatenate and/or map existing metadata elements to multiple DCAT-US elements (e.g. "[liability statement](https://doi-do.github.io/dcat-us/#properties-for-liability_statement)" and "[useRestriction](https://doi-do.github.io/dcat-us/#properties-for-use_restriction)). Both CSDM and ISO contain distinct elements that describe "use constraints" or restrictions, e.g.:
  - CSDGM [useconst](https://www.fgdc.gov/csdgmgraphical/ideninfo/usecon.htm): _These include any use constraints applied to assure the protection of privacy or intellectual property, and any special restrictions **or limitations on using the data set**_
  - CSDGM [purpose](https://www.fgdc.gov/csdgmgraphical/ideninfo/descr/purpose.htm): _a summary of the intentions with which the data set was developed_
  - ISO [Constraint class](https://schemas.isotc211.org/19115/-1/mco/1.3/) which includes
    - [useLimitation](https://github.com/ISO-TC211/XML/blob/517cab30e2c2a176f6f00a651bf9e6cf4fb4219e/standards.iso.org.annotated/iso/19115/-3/mco/1.0/constraints.xsd#L26-L28): _limitation affecting the fitness for use of the resource or metadata. Example, "not to be used for navigation"_
    - [accessConstraints](https://github.com/ISO-TC211/XML/blob/517cab30e2c2a176f6f00a651bf9e6cf4fb4219e/standards.iso.org.annotated/iso/19115/-3/mco/1.0/constraints.xsd#L76-L78): _applied to assure the protection of privacy or intellectual property, and any special restrictions or limitations on obtaining the resource or metadata_
    - [useConstraints](https://github.com/ISO-TC211/XML/blob/517cab30e2c2a176f6f00a651bf9e6cf4fb4219e/standards.iso.org.annotated/iso/19115/-3/mco/1.0/constraints.xsd#L81-L83): _applied to assure the protection of privacy or intellectual property, and any **special restrictions or limitations or warnings** on using the resource or metadata_
    - [otherConstraints](https://github.com/ISO-TC211/XML/blob/517cab30e2c2a176f6f00a651bf9e6cf4fb4219e/standards.iso.org.annotated/iso/19115/-3/mco/1.0/constraints.xsd#L86-L88): _other restrictions and legal prerequisites for accessing and using the resource or metadata_

**Comment by fellahst** [comment]
Updated and clarified definition and usage note of [Liability Statement](https://doi-do.github.io/dcat-us/#properties-for-liability_statement)

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.
