### ISSUE TITLE
Map Projection Coordinate Systems Handling

### ISSUE THREAD

**Issue by doi-jschlagel** [DOI-DO/dcat-us#137]
**Name:**   Joel Schlägel

**Affiliation:**  Gepplatform.gov

**Type of issue:** General Comment

**Issue:**  documentation explains clearly that coordinates for bounding box are lat/lon was84, but there is very little discussion of how map projections & coordinate systems are handled for geographic data sets.   We do say +dct:conformsTo and explicitly say http://www.opengis.net/def/crs/EPSG/0/ under controlled vocabularies which answers the question, but it is difficult to find in the document, and one would have to be looking for EPSG and understand the purpose of EPSG  rather than "map projections" or "coordinate systems" to know we've got it covered

**Recommended change(s):** _add discussion of support for projections under spatial metadata section and consider adding under property if that makes sense

**Comment by hkdctol** [comment]
discuss this one next meeting with Joel?

**Comment by fellahst** [comment]
Added section about[ handling of map projection and coordinate systems ](https://doi-do.github.io/dcat-us/#map-projections-coordinate-systems)in spatial metadata usage guideline
