### ISSUE TITLE
A pointer to a schema/data dictionary is necessary for better discovery and describing variables for statistical data

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#138]
**Name:**  Dan Gillman (gillman.daniel@bls.gov); Peter Meyer (meyer.peter@bls.gov); Bill Savino (william.s.savino@census.gov)

**Affiliation:** BLS, Census Bureau

**Type of issue:** : Critical Comment - Imposition of Unreasonable Burden

**Issue:**

Though this schema represents a lot of work, there is a much new detail, the metadata called for are machine actionable, and the relational structure is helpful, the continued lack of a specification or even a specific element with a pointer to a data dictionary (a structured listing of the description of the variables contained within the dataset) is a failure. It is possible with the current structure, a data dictionary could be described. It is not obvious how to do this, nor is it obvious there is only one way to do this. Interoperability requires either one way or a specific means to discover which way the data dictionary is described. We recognize that the DCAT standard addresses a catalog of data sets and is not intended to go deeper. But a catalog of data sets, especially one that purports to allow discovery of data, needs a way to find the data dictionaries of each of the data sets that require one. Discovery is incomplete if similar sets can't be distinguished at the varialbe level. A data dictionary is the means to do this. FAIRness demands that metadata at the variable level be included with the metadata for each data set. There's more that a metadata management system would attempt to do, but just having each individual variable described is a pre-requisite to do anything else. There are many standards that contain the ability to describe variables. Some do it better than others. We highly recommend, given the detail and extent the current spec goes in some areas, to include some classes for describing the underling variables, too. The submitters of this comment have significant experience with the problem of describing variables for statistical data. These problems generalize. We can easily produce a spec that can be added to this one. But as stated above, the lack of such a capability renders this approach incomplete for the problem at hand. We further note, the group the 3 of us represents, the SCOPE/Metadata inter-agency group for metadata, submitted a potential solution to this problem at least 10 years ago. This proposal was ignored. We never knew why. If this new effort were to adopt a way to describe variables, it almost certainly will become a government wide standard.

**Comment by jqnatividad** [comment]
[Section 5.16 Dataset](https://doi-do.github.io/dcat-us/#properties-for-dataset) mentions a recommended [data dictionary](https://doi-do.github.io/dcat-us/#dataset-describedBy) property with a Usage Note:

> This is used to specify a data dictionary or schema that defines fields (dimensions, measures, attributes) in the dataset.

However, the [dcat-us:describedBy](http://data.resources.gov/ontology/dcat-us#describedBy) URI is a 404 placeholder.

It'd be great if the data dictionary spec being considered is a machine-readable schema so Catalog systems can automatically generate the data dictionary.

Catalog systems can also use the data dictionary to validate Dataset updates.

**Comment by fellahst** [comment]
> Though this schema represents a lot of work, there is a much new detail, the metadata called for are machine actionable, and the relational structure is helpful, the continued lack of a specification or even a specific element with a pointer to a data dictionary (a structured listing of the description of the variables contained within the dataset) is a failure. It is possible with the current structure, a data dictionary could be described. It is not obvious how to do this, nor is it obvious there is only one way to do this. Interoperability requires either one way or a specific means to discover which way the data dictionary is described.  

**Response**: The earlier draft DCAT-US 3.0 draft specification referenced the adms:supportedSchema property as means for referencing schema/ data dictionary resources. On further review, the current draft removes adms:supportedSchema  and restores use of the DCAT-US 1.1 describedBy property but employs dcat:Distribution as its range to streamline how datasets (and their distributions) reference their data dictionaries, schemas or standards. By removing the need for the DCAT-US 1.1 describedByType property, we have enhanced the specificity and clarity of these references. This adjustment more directly connects a dcat:Dataset or dcat:Distribution to a corresponding data dictionary/ schema distribution, emphasizing formal and structured relationships. This modification is designed to boost both the interoperability and comprehensibility of dataset structures. However, we do acknowledge that this change, while significant, might not completely address every aspect of integrating data dictionaries. 

> We recognize that the DCAT standard addresses a catalog of data sets and is not intended to go deeper. But a catalog of data sets, especially one that purports to allow discovery of data, needs a way to find the data dictionaries of each of the data sets that require one.  

**Response**: We agree that for a dataset catalog, to be truly effective in enabling data discovery, must provide a means to access or at least reference the data dictionaries of the datasets it lists. This need is particularly pronounced when the datasets are complex or require detailed understanding to be used effectively.  

The refinement of dcat-us:describedBy range to dcat:Distribution in the current DCAT framework is a significant step towards offering flexibility and extensibility in data cataloging. It allows datasets to reference a wide array of standards for schema description, catering to diverse data types and requirements. This flexibility is one of the core strengths of the current implementation. 

> Discovery is incomplete if similar sets can't be distinguished at the variable level. A data dictionary is the means to do this. FAIRness demands that metadata at the variable level be included with the metadata for each data set. There's more that a metadata management system would attempt to do, but just having each individual variable described is a pre-requisite to do anything else.  

**Response**: Your comment highlights an equally important aspect — the need for a more structured approach, especially when it comes to enabling easy access to data dictionaries and detailed variable-level information. While dcat-us:describedBy provides a broad solution, it might not always offer the granularity needed for specific datasets, particularly those requiring detailed structural descriptions or specialized metadata. The challenge is to find a balance between the flexibility offered by dcat-us:describedBy and the need for more structured, detailed metadata representation. A possible solution could be the development of additional properties or a complementary framework within DCAT that specifically addresses these needs. This could involve guidelines or standardized formats for data dictionaries, ensuring they are both accessible and informative, without overcomplicating the overall schema. 

In pursuing this balanced approach, we must consider the varying capabilities and resources of different data publishers and users. The goal is to enhance the DCAT standard to be more inclusive and effective in data discovery and usage, while also keeping it manageable and “user-friendly” (e.g., implementable by a broad range of stakeholders). 

> There are many standards that contain the ability to describe variables. Some do it better than others. We highly recommend, given the detail and extent the current spec goes in some areas, to include some classes for describing the underling variables, too.  

**Response**: As we consider integrating these classes, it's essential to balance the need for detailed, useful descriptions with the complexity of the specification. Ensuring that the enhanced specification remains accessible and user-friendly, particularly for those without extensive technical expertise, is paramount. We welcome collaboration and input on structuring and integrating these classes within the existing framework. In this context, the RDF Data Cube data structure (dimension, measure, attribute) presents itself as a viable candidate, as demonstrated in StatDCAT-AP, which achieves a good balance with minimal changes to the profile. Additionally, DDI-RDF offers another avenue for variable description, contributing to a more comprehensive approach in the DCAT framework. The implementation of standardized, controlled vocabularies for describing variables, such as those based on the SDMX standard, would significantly benefit the community by enhancing consistency and clarity in data description. 

> The submitters of this comment have significant experience with the problem of describing variables for statistical data. These problems generalize. We can easily produce a spec that can be added to this one.  

**Response**: We highly value your expertise in describing variables for statistical data and are keen to see how your experience can enhance our current framework. Your offer to develop a supplementary specification is welcomed. Collaborative efforts like yours are crucial in refining and advancing standard data specifications. Please consider contributing a proposal or collaborating with the “FAIRness” project’s Core Team to define or integrate standards for data description and interoperability. 

> But as stated above, the lack of such a capability renders this approach incomplete for the problem at hand. We further note, the group the 3 of us represents, the SCOPE/Metadata inter-agency group for metadata, submitted a potential solution to this problem at least 10 years ago. This proposal was ignored. We never knew why. If this new effort were to adopt a way to describe variables, it almost certainly will become a government wide standard. 

**Response**: We acknowledge the deliberate limitations of the DCAT-US 1.1 schema and the current proposed approach, as you've highlighted. The absence of a detailed mechanism for describing variables does indeed leave a gap in addressing the full scope of the problem. Perhaps there is an opportunity to adopt a comprehensive method for describing variables as a new standard across government platforms. Such a collaboration could lead to a comprehensive and more effective standard that has the potential for widespread adoption.

**Comment by dafeder** [comment]
@jqnatividad I'd be interested in developing some examples for how to reference a data dictionary document that conforms to a properly documented standard. If you have a document a a particular URL that conforms to, say, [CSV on the Web](https://www.w3.org/TR/tabular-data-primer/#documentation) or [Data Package Table Schema](https://specs.frictionlessdata.io//table-schema/) or CKAN, what is the most straightforward way to reference this...

**Comment by jqnatividad** [comment]
Hi @dafeder , we're planning to take advantage of the new [iDataDictionaryForm interface](https://github.com/ckan/ckan/pull/8014). It stores the data dictionary in an extensible, machine-readable JSON format that can be easily used to export the Data Dictionary into standard formats like the ones you described above.

Already, CKAN infers a data dictionary on the Data Publisher's behalf. Currently, the dictionary has column name, the data type, the display label, and a description. We're extending it to add additional field/column metadata - summary statistics and frequency info as I mentioned above) and to "[automagically](https://ckan.org/events/ckan-datapusher-plus-automagical-metadata)" infer additional metadata based on the content of the dataset - targeting to prepopulate DCAT-3 fields like [geographicBoundingBox](https://doi-do.github.io/dcat-us/#dataset-geographic_bounding_box) and [PeriodOfTime](https://doi-do.github.io/dcat-us/#properties-for-period-of-time) - all to make the curation process easier.

Thus far, the Data Dictionary has primarily served as human-readable documentation.

The intent is that this machine-readable Extended Data Dictionary becomes a first class resource that Catalog users (machines included using the API) can use to get not just metadata ABOUT A DATASET PACKAGE as is the case with most catalogs, but metadata ABOUT ITS CONTENTS that Catalog Users can use to better understand datasets without necessarily having to download it first.

In the spirit of DCAT 1.1, and its readily understandable `data.json` file that led to widespread adoption. Perhaps the accessURL can be a standard one perhaps a `datadictionary.json` file - for each dataset? e.g. 
https://catalog.data.gov/dataset/electric-vehicle-population-data/datadictionary.json

**Comment by dafeder** [comment]
Thanks @jqnatividad, all very interesting info but I'm not sure my question was clear. I'm roughly familiar with how CKAN handles data dictionaries and have been following some of your work improving the inference of column-level metadata. What I'm wondering is about how to properly include such information in DCAT; it seems DCAT 3.0 gets us a little closer but its still ambiguous how this should be included. So I was looking for maybe an example Dataset JSON that linked properly to column-level metadata.

I have to say I'm a little confused why DCAT seems so resistant to support this in any way. Even `describedBy` is now unique to DCAT-US and I believe removed from core DCAT 3.0 and DCAT-AP.

**Comment by dafeder** [comment]
Thanks @jqnatividad. Clearly the biggest issue here is the lack of a good standard. I think CSV on the web is the closest thing we have, at least until the Frictionless Data Package specs provide proper context documents. I wonder if we could include an example for the docs in this repo? @fellahst would you be open to a PR that adds an example (I imagine I'd get something wrong on the first pass but willing to try)?

**Comment by dafeder** [comment]
Something like this? 

https://gist.github.com/dafeder/709a06b7e6d8e8dedf026ce5eb178578

**Comment by jqnatividad** [comment]
The problem with CSV on the Web is the lack of adoption and tooling. Things are a bit better for the Frictionless Framework, but the limited experiments I did with validation, especially of large files, is that its not performant.

That's why we're using JSONschema in qsv.

It derives a JSONSchema validation file from a "training" dataset in a performant manner. 

For example, for a sample 1 million row NYC 311 file, it derives a non-trivial JSONSchema file in just 7.7 seconds.

The same JSONschema can then be used to validate other NYC 311 files. In the benchmark, validating the same 1m row NYC 311 file took all of 1.37 seconds.

https://qsv.dathere.com/benchmarks

[JSONSchema](https://json-schema.org/) is quite robust, mature, and has a lot of available tooling and the [validation spec](https://json-schema.org/draft-07/json-schema-validation#rfc.section.7.3.1) could easily double as a data dictionary - we just need to render its contents in the UI so it looks like a typical data dictionary.

**Comment by dafeder** [comment]
I think the issue here is the proper way to describe the columns and associate that with the dataset in DCAT in a predictable, consistent way. CSV On the web has the advantage of being an established standard that can be expressed as part of RDF linked data. One could convert back and forth to other formats as their own tooling requires. How would one use JSON schema to describe a CSV inside a DCAT-US distribution object? Would it be unambiguous to another consumer how to use that metadata?
