### ISSUE TITLE
SORN - System of Records Notice - what should be the identifier

### ISSUE THREAD

**Issue by hkdctol** [DOI-DO/dcat-us#14]
Bringing in an issue from Project Open Data, at https://github.com/project-open-data/project-open-data.github.io/issues/531

Current DCAT guidance is to use Federal Register URL for the SORN https://resources.data.gov/resources/dcat-us/#systemOfRecords

but the issue filed in Project Open Data suggests otherwise

**Comment by fellahst** [comment]
Acknowledging the issue raised in Project Open Data regarding the use of Federal Register URL for the System of Records Notice (SORN) in DCAT guidance, we plan to address this during the DCAT-US specification's implementation phase. A thorough review and potential revision of our guidance will ensure alignment with best practices and user needs. We are committed to providing clear and accurate metadata guidelines, incorporating feedback from relevant stakeholders.

**Comment by TDabolt** [comment]
Flag for OMB input.  agency ID may not work well.  maybe  Roku (sp?)

**Comment by mrratcliffe** [comment]
+1
