### ISSUE TITLE
DCAT-US 3's SHACL shapes should import OWL version IRIs where available

### ISSUE THREAD

**Issue by ajnelson-nist** [DOI-DO/dcat-us#140]
**Creator Name:** [Alex Nelson](https://orcid.org/0000-0002-3771-570X)

**Creator Affiliation:** I am an employee of the [National Institute of Standards and Technology](https://www.nist.gov/). I am also a community member of the [Cyber Domain Ontology](https://cyberdomainontology.org/) (CDO) in some leadership roles. This contribution is made only by myself, and is not being made by the National Institute of Standards and Technology or any other organization. [^1]

## Requirement(s)

Have SHACL graph import specific versions of referenced OWL ontologies to designate versioned conformance.

### Description of the problem

DCAT and DCAT-US employ a wide range of vocabularies to build its annotations.  Evidence can be seen in the SHACL graph's long list of `@prefix` statements.

Some of these prefixes correspond to OWL ontologies, which have a technical capability of expressing their current version.  Some of the prefixes correspond to RDFS schemata, _which are left out of scope of this issue_.

Alongside the benefits of concept reuse, there also comes a maintenance task of knowing when backwards-incompatible changes are introduced in any of the adopted ontologies.  A downstream user adopting DCAT-US 3's SHACL could find the DCAT-US 3 shapes fall "out of sync" with some mutually-adopted ontologies, due to the "unpinned" nature of DCAT-US 3's concept references.

### Stakeholders experience the problem

This problem is an instance of a general software-versioning problem, typically addressed with discussions around version-pinning.  Any user of the DCAT-US 3 SHACL shapes in an application that supplements DCAT-US vocabularies with other development on shared imports could be affected.

For example, the CDO community has [a repository](https://github.com/casework/CASE-Corpora/) exercising DCAT-US (prior to version 3) and various ontologies that are and aren't under the community's development purview.  One ontology being exercised is [OWL-Time](https://www.w3.org/TR/owl-time/), which currently has a Candidate Recommendation Draft set to introduce deprecations.  If DCAT-US 3 had provided shapes for that ontology (it currently doesn't), without pinning to a version of OWL-Time, the shapes would likely be realized incompatible with "current" OWL-Time in unpleasant stumbling-upon scenarios where a knowledge graph imports some version of OWL-Time published after DCAT-US 3 is finalized.

### What stakeholders are expected to supply to resolve the problem themselves

On encountering incompatible shapes in DCAT-US 3's SHACL graph, stakeholders could find parts of their data being flagged as non-conformant with ontologies outside of DCAT-US's purview.  They could address the problems locally by reporting incompatibilities (to this repository?); by migrating data around the shape issues; or by deleting the specific non-conformant shapes in their applications' copies of the DCAT-US 3 SHACL graph.  The latter options would not bode well for ecosystem cross-compatibility.

## Target Audience / Stakeholders

*User 1.  Maintainers of Catalogs exercising ontologies outside of DCAT-US 3's coverage*
*User 2.  Metadata experts, when mapping other metadata standards to DCAT*

## Intended Uses / Use Cases

- *Use 1. Know whether the ontology versions referenced by DCAT-US 3 are the current versions, by reviewing the referenced version IRI and its referenced, unversioned ontology IRI (which then resolves to the latest version).*
- *Use 2. Know whether any mutually-incompatible imports are in the DCAT-US 3 coverage, so the situation can be noticed, reviewed, and mitigated.*
- *Use 3. Know whether adopting DCAT-US 3's SHACL graph induces a pinning of the shape-reviewed ontologies that is acceptable to the rest of the end user's application design.*

## Existing Approaches

OWL provides concepts to support designating when there could be breaking changes, described [here](https://www.w3.org/TR/owl2-syntax/#Ontology_IRI_and_Version_IRI):

* `owl:backwardCompatibleWith`, [used in DCAT 3's current draft](https://github.com/w3c/dxwg/blob/f58713c/dcat/rdf/dcat3.ttl#L147-L148)
* `owl:incompatibleWith`, not used in DCAT 3's current draft
* `owl:versionIRI`, [used in DCAT 3's current draft](https://github.com/w3c/dxwg/blob/f58713c/dcat/rdf/dcat3.ttl#L154)

These concepts are available for use in graphs that exercise `owl:imports`, as the DCAT-US 3 SHACL graph currently does.

If the DCAT-US maintainers think it preferable to leave versions unpinned, OWL does let `owl:imports` reference the unversioned ontology IRI instead of a value of `owl:versionIRI`.  That is another option for making explicit what retrievable graphs are the sources of class and property definitions.

## Additional context, comments, or links

DCAT 3's current draft [provides a version IRI](https://github.com/w3c/dxwg/blob/f03a6dc/dcat/rdf/dcat3.ttl#L154) that seems like something DCAT-US 3 should target with `owl:imports`.

The DCAT-exercising repository I have a hand in developing, CASE-Corpora[^1], has an [illustration](https://github.com/casework/CASE-Corpora/tree/main/reports#ontology-import-closure) of the ontology/schemata import closure induced from exercising the ontologies it does.  While the OWL import transitive closure is often left implicit, crafting this graph (which is generated from the OWL and SHACL graphs in that repository) lays explicit what the transitive closure actually extends to, for DCAT and other ontologies relevant to that repository.

[This directory](https://github.com/casework/CASE-Corpora/tree/main/shapes) contains shapes narrowly focused on each of the ontologies and schemata referenced by DCAT-US (pre-3) and other ontologies exercised in this repository.  This approach was taken to separate concerns specific to DCAT-US from concerns general to the original class and property definitions.

[^1]: Disclaimer: Participation by NIST in the creation of the documentation of mentioned software is not intended to imply a recommendation or endorsement by the National Institute of Standards and Technology, nor is it intended to imply that any specific software is necessarily the best available for the purpose.

**Comment by fellahst** [comment]
Alex,

Thank you so much for your detailed feedback. Your ticket is currently under review, and we will come back to you as soon as possible with remediation for the issue you raised. Thanks for your patience.

**Comment by fellahst** [comment]
Alex,

I've been grappling with the issue of importing OWL ontologies into SHACL shapefiles, particularly in light of the practices observed in the development of the [DCAT-AP 3.0 SHACL](https://github.com/SEMICeu/DCAT-AP/blob/master/releases/3.0.0/shacl/dcat-ap-SHACL.ttl) profiles in Europe, which notably do not incorporate ontology imports. The ambiguity surrounding best practices for OWL imports within SHACL shapefiles underscores the complexity of this issue. In this context, a cautious approach towards importing OWL ontologies appears to be the most sensible path forward. This approach not only acknowledges the unclear short-term benefits of such imports but also maintains our adaptability and responsiveness to the evolving requirements and insights that the implementation phase might reveal. By awaiting feedback from actual implementations, we aim to gain a clearer understanding of the practical use cases, which will inform our decision-making process on whether and how ontology imports could potentially improve the utility and interoperability of the DCAT-US SHACL profile, ensuring that our strategies are both effective and closely aligned with the needs of our users

**Comment by ajnelson-nist** [comment]
Thank you for your reply @fellahst .  I respect the cautious approach, as I agree that the implications are difficult to comprehend holistically.  There are interesting design issues from different semantics used to evaluate RDFS schema vs. OWL 2 DL ontologies vs. SHACL shape graphs.

For instance, it might be necessary to evaluate a SHACL shapes graph that imports an OWL ontology only using shapes that ignore much of the OWL 2 DL constraints temporarily - minimally, because SHACL doesn't define its properties as one of the 3 OWL property-types.  I've found benefit to doing specific reviewing from that kind of import, though: Because SHACL and OWL are de-coupled syntaxes, it's possible to write SHACL that constrains an `owl:ObjectProperty` to require only literal values, and this wouldn't be found out until an OWL reasoner reviews instance data and (rightly) squawks about inconsistency.

Thank you again for the consideration and discussion.  I'll be happy to let you know (probably from returning to this issue in a while) other experiential notes I have for or against this Issue.  I don't mind this issue being closed, and I can open a follow-on issue later if this team prefers not re-opening issues.

**Comment by mrratcliffe** [comment]
+1

**Comment by fellahst** [comment]
Alex,

Thank you once more for your valuable perspective. I propose we tackle this matter in the implementation phase. I'll proceed to close this issue, marking it for "revisit" so that we can ensure it's taken into account at that stage.
