### ISSUE TITLE
Add optional accrual periodicity property for dataset registration

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#142]
**Name:** Denise Warzel

**Affiliation:** NCI, Denise.warzel@nih.gov

**Type of issue:** Schema

Section # / Table #: 4.2

**Issue:**

- **Comment**: An attribute indicating how frequently the data set is updated is helpful for those wishing to establish a mechanism to stay up to date, for example a script or API that pulls a new copy when available, but seems to be missing. 

- **Rationale**: This attribute is Optional in the ISO/IEC 11179-33:2023 Standard - Metamodel for data set registration the international community felt it would be useful.

- **Proposed Disposition:** Add Accural_Periodicity:  0..1 String
Definition: The frequency at which new, revised or updated versions of this data set are made available.

**Comment by fellahst** [comment]
Thank you for providing detailed feedback on the `accrualPeriodicity` property within the DCAT-US profile. Your insights underscore a crucial aspect of dataset metadata, particularly for users who rely on consistent updates to align their systems or applications with the latest data.

We appreciate your observation regarding the potential underemphasis of the `dcterms:accrualPeriodicity` property in the DCAT-US adaptation, despite its availability in the overarching DCAT standard. To address this, we have ensured that `accrualPeriodicity` is clearly defined and accessible for both `dcat:Dataset` (as outlined in [Dataset Frequency](https://doi-do.github.io/dcat-us/#dataset-frequency)) and `dcat:DatasetSeries` (detailed in [Dataset Series Frequency](https://doi-do.github.io/dcat-us/#dataset-series-frequency)). These sections are crafted to meet the requirements you've mentioned.

Furthermore, we have recently enhanced the documentation within the [Temporal Metadata](https://doi-do.github.io/dcat-us/#temporal-metadata) section of the DCAT-US profile. This enhancement includes additional clarification and guidance on the practical application of the `accrualPeriodicity` property. Our aim is to ensure that users can effectively utilize this property in diverse data scenarios, thereby maximizing the utility and efficiency of their data management processes.

We believe these updates and clarifications will address your concerns and significantly aid users in implementing the `accrualPeriodicity` property within the DCAT-US framework. Your input is invaluable to the continuous improvement of the DCAT-US profile, and we encourage you to share any further suggestions or inquiries you may have.
