### ISSUE TITLE
Introduce a guide highlighting differences between schema versions and if the updates meet the identified issues

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#143]
**Name:** Gilberto Fragoso

**Affiliation:** NCI, fragosog@mail.nih.gov  

**Type of issue:** Editorial

**Issue:** It is difficult to discern the differences between this version and the prior versions and if the updates meet the identified issues. A guide highlighting this would be helpful.

**Comment by hkdctol** [comment]
Agree, as in other issues--mapping/guides etc. will be needed for implementation

**Comment by fellahst** [comment]
See https://github.com/DOI-DO/dcat-us/files/13603547/DCAT-US.3.Overview.pdf slides 9-12
