### ISSUE TITLE
Fix the overlap between how the ‘AccessRestriction’ (5.2), ‘UseRestriction’ (5.38) and ‘RightsStatement’ (5.36) classes are defined/intended for use

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#144]
**Name:** Mike Shallcross

**Affiliation:** ICPSR, shallcro@umich.edu

**Type of issue:** Schema, Editorial

Section # / Table #: 5.2, 5.36, 5.38

**Issue:**

- **Comment**: There appears to be some overlap between how the ‘AccessRestriction’ (5.2), ‘UseRestriction’ (5.38) and ‘RightsStatement’ (5.36) classes are defined/intended for use. For instance, 'RightsStatement' is "A statement about the intellectual property rights (IPR) held in or over a resource, a legal document giving official permission to do something with a resource, or a statement about access rights" and a UseRestriction "may encompass limitations on access."

- **Rationale**: Having classes/properties with potential overlap could confuse users and result in local conventions that prevent metadata interoperability and standardization.

- **Proposed Disposition:** Clarify the definitions or provide additional usage notes to help users understand when one class/property should be employed instead of another.

Original email submission: 
[ICPSR_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430487/ICPSR_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by hkdctol** [comment]
There appear to be multiple issues getting at the same fields--we should discuss

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.
