### ISSUE TITLE
Missing text: It should be always kept in mind that both DCAT-US primarily focus on metadata

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#146]
**Name:** Morgan Daniels

**Affiliation:** USAID, mdaniels@usaid.gov

**Type of issue:** Editorial, Administrative

Section # / Table #: [2.3 Area of application](https://doi-do.github.io/dcat-us/#area-of-application)

**Issue:**

- **Administrative Comment**: Missing text: It should be always kept in mind that both DCAT-US primarily focus on metadata

Original email submission: 
[USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx](https://github.com/DOI-DO/dcat-us/files/13430653/USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx)

**Comment by fellahst** [comment]
Removed the word both
