### ISSUE TITLE
Confusing text related to properties and their usage conforming to DCAT 3 and if they are included in DCAT-US or to DCAT if they are only included in DCAT.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#148]
**Name:** Morgan Daniels

**Affiliation:** USAID, mdaniels@usaid.gov

**Type of issue:** Editorial, Administrative

Section # / Table #: [3.1](https://doi-do.github.io/dcat-us/#provider-requirements)

**Issue:**
- **Administrative Comment**: This text was confusing: Properties not mentioned in this specification MAY be used if they are included in either DCAT 3 and their usage conforms to DCAT 3 if they are included in DCAT-US or to DCAT if they are only included in DCAT.

Original email submission: 
[USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx](https://github.com/DOI-DO/dcat-us/files/13430653/USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx)

**Comment by hkdctol** [comment]
Agree the wording is confusing--clarify language

**Comment by fellahst** [comment]
Updated section.
