### ISSUE TITLE
More comprehensive guidance is needed on the difference between these two address fields

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#149]
**Name:** Morgan Daniels

**Affiliation:** USAID, mdaniels@usaid.gov

**Type of issue:** Editorial, Administrative

Section # / Table #: [5.4](https://doi-do.github.io/dcat-us/#properties-for-address-contact_point), [5.5](https://doi-do.github.io/dcat-us/#properties-for-address-location)

**Issue:**
- **Administrative Comment**: More comprehensive guidance is needed on the difference between these two address fields

Original email submission: 
[USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx](https://github.com/DOI-DO/dcat-us/files/13430653/USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx)

**Comment by hkdctol** [comment]
If there's a simple clarification--add the information

**Comment by fellahst** [comment]
Added usage notes for address fields.

**Comment by mrratcliffe** [comment]
+1
