### ISSUE TITLE
Primary topic is a confusing property name

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#150]
**Name:** Morgan Daniels

**Affiliation:** USAID, mdaniels@usaid.gov

**Type of issue:** Editorial, Administrative

Section # / Table #: [5.9.1](https://doi-do.github.io/dcat-us/#catalog-record-mandatory-props)

**Issue:**
- **Administrative Comment**: Primary topic is a confusing property name

Original email submission: 
[USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx](https://github.com/DOI-DO/dcat-us/files/13430653/USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx)

**Comment by fellahst** [comment]
Response for GitHub Issue:

---

Dear Morgan Daniels,

Thank you for your feedback on the DCAT-US profile, specifically regarding the property name `foaf:primaryTopic` in Section [primary topic](https://doi-do.github.io/dcat-us/#catalog-record-primaryTopic)

We understand your concern about the clarity of the property name. The term `foaf:primaryTopic` is indeed defined in the  DCAT CatalogRecord specification (https://www.w3.org/TR/vocab-dcat-3/#Property:record_primary_topic). This property is used to denote the main or primary topic of a web resource, and it is a standard term within the Friend of a Friend (FOAF) vocabulary, which is commonly used in the context of Linked Data and semantic web technologies.

In the DCAT-US context, `foaf:primaryTopic` serves to provide a clear linkage between the CatalogRecord and the primary dataset or dataset series that the record describes. The use of standardized vocabularies like FOAF ensures consistency and interoperability in the representation of metadata across different systems.

While we acknowledge that the term might seem abstract or less intuitive, its usage is aligned with established practices in semantic web and data cataloging standards. We appreciate your input as it helps us improve the usability and understandability of the DCAT-US profile. Please feel free to reach out if you have further suggestions or need additional clarifications.
