### ISSUE TITLE
 Unclear how/ if CUI restriction maps to public, restricted public, non-public access levels

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#151]
**Name:** Morgan Daniels

**Affiliation:** USAID, mdaniels@usaid.gov

**Type of issue:** Editorial

Section # / Table #: [5.14 CUI Restriction](https://doi-do.github.io/dcat-us/#properties-for-cui_restriction)

**Issue:**
- **Substantive Comment**: Unclear how/ if CUI restriction maps to public, restricted public, non-public access levels

Original email submission: 
[USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx](https://github.com/DOI-DO/dcat-us/files/13430653/USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx)

**Comment by hkdctol** [comment]
A lot of issues essentially covering the same questions--we should discuss

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.
