### ISSUE TITLE
No definition or usage note is given here- it is difficult to tell how an agency would decide whether or not to use this

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#152]
**Name:** Morgan Daniels

**Affiliation:** USAID, mdaniels@usaid.gov

**Type of issue:** Editorial, Administrative

Section # / Table #: [5.22 Investment](https://doi-do.github.io/dcat-us/#properties-for-investment)

**Issue:**
- **Administrative Comment**: No definition or usage note is given here- it is difficult to tell how an agency would decide whether or not to use this

Original email submission: 
[USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx](https://github.com/DOI-DO/dcat-us/files/13430653/USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx)

**Comment by hkdctol** [comment]
For discussion--wasn't sure about this one either

**Comment by fellahst** [comment]
Remvoed from the specification. See #5
