### ISSUE TITLE
While the usage notes make the difference between Metric and Quality Measurement clear, the labels could use some disambiguation

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#153]
**Name:** Morgan Daniels

**Affiliation:** USAID, mdaniels@usaid.gov

**Type of issue:** Editorial, Administrative

Section # / Table #: [5.34 Quality Measurement](https://doi-do.github.io/dcat-us/#properties-for-quality-measurement)

**Issue:**
- **Administrative Comment**: While the usage notes make the difference between Metric and Quality Measurement clear, the labels could use some disambiguation- it also seems that more than one quality measurement could apply to a single dataset
- **Proposed Disposition**: Unit of Measurement or Measurement Unit would be a less ambiguous term

Original email submission: 
[USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx](https://github.com/DOI-DO/dcat-us/files/13430653/USAID-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_USAID.xlsx)

**Comment by fellahst** [comment]
Morgan,

Thank you for your insightful feedback regarding the use of terminology in Section [5.34 Quality Measurement](https://doi-do.github.io/dcat-us/#properties-for-quality-measurement) of the DCAT-US specification, specifically concerning `Metric` and `Quality Measurement`. Your distinction between these terms and the suggestion for disambiguation is well-noted and appreciated.

We understand that clarity in terminology is paramount in specifications like DCAT-US. In the context of the Data Quality Vocabulary [DQV](https://www.w3.org/TR/vocab-dqv/), which the DCAT-US specification aligns with, `Metric`is employed to represent the criteria or standard used to evaluate a specific aspect of data quality. In contrast, `Quality Measurement` is the result or outcome derived from applying a 'Metric' to a dataset.

Your observation about the potential overlap and confusion between these terms is an important consideration. While `Unit of Measurement` or `Measurement Unit` could be perceived as less ambiguous, these terms typically refer to the scale or dimensions used in quantification (like meters, seconds, or percentages) and may not fully encapsulate the essence of data quality evaluation as intended in the DQV context.

Regarding the application of multiple quality measurements to a dataset, the DCAT-US specification, consistent with the DQV, indeed allows for this. This flexibility is vital for comprehensive data quality assessment, given the multifaceted nature of datasets.

We will undertake a thorough review of the terminology in Section 5.34, considering your suggestions for enhancing clarity and precision and elaborate the section [Data Quality](https://doi-do.github.io/dcat-us/#data-quality) in usage guideline. Our aim is to ensure that the DCAT-US specification remains both clear, accurate and user-friendly.
