### ISSUE TITLE
Ensure that there is no potential for duplicative data if both fields are used, given that the "spatial" and "geographic bounding box" fields could share certain similarities.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#154]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.16.2](https://doi-do.github.io/dcat-us/#dataset-spatial)

**Issue:**

- **Substantive Comment**: How is the Geographic Bounding Box field different from the Spatial Coverage field?

- **Rationale**: We want to ensure that there is no potential for duplicative data if both fields are used, given that the "spatial" and "geographic bounding box" fields could share certain similarities.

- **Proposed Disposition:** Clarification of Guidance

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by hkdctol** [comment]
For discussion--is it actually the same info in both?

**Comment by fellahst** [comment]
Addressed in [Spatial metadata ](https://doi-do.github.io/dcat-us/#geographic-bounding-box) usage guideline
