### ISSUE TITLE
Clarification of Guidance on Dataset's :temporalCoverage

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#155]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.16.2](https://doi-do.github.io/dcat-us/#dataset-temporal-coverage) Dataset's :temporalCoverage property

**Issue:**

- **Substantive Comment**: Is this field best defined as a representation of time regarding the creation/upkeep of the dataset itsef? Or is this field more concerned with the research encompassed in the dataset?

- **Rationale**: We currently track when our datasets are created as well as when they receive their latest updates. Is this field a representation of that time span or something else?

- **Proposed Disposition:** Clarification of Guidance

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by fellahst** [comment]
Guidance for usage of temporal properties are been added in the Usage Guidance section: https://doi-do.github.io/dcat-us/#temporal-metadata . Let us know if that addresses your concern.

**Comment by fellahst** [comment]
Need to add clarification for temporal properties for CatalogRecord

**Comment by fellahst** [comment]
Added clarification for CatalogRecord lifecycle properties/
