### ISSUE TITLE
Clarification of Guidance on Dataset's theme category property

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#156]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.16.2](https://doi-do.github.io/dcat-us/#dataset-theme-category) Dataset's theme category property

**Issue:**

- **Substantive Comment**:What types of themes does this field tend to cover?

- **Rationale**: We're unsure of the recommended way to implement this field.

- **Proposed Disposition:** Clarification of Guidance

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by fellahst** [comment]
Issue is addressed in [Resource Classification](https://doi-do.github.io/dcat-us/#resource-classification) usage guideline
