### ISSUE TITLE
More information needed about the usage of Dataset's investment property

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#158]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.16.3](https://doi-do.github.io/dcat-us/#dataset-investment) Dataset's _**investment**_ property

**Issue:**

- **Substantive Comment**: According to the documentation, this field is marked as "TO-DO". We aren't sure what information should go within this field or how this field is supposed to be utilized.

- **Rationale**: We need more information about its usage.

- **Proposed Disposition:** Additional Guidance

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by fellahst** [comment]
The property has been removed from the specification . See #5
