### ISSUE TITLE
More documentation and full examples for Dataset's qualified relation property would help show its suggested usage.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#160]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.16.2](https://doi-do.github.io/dcat-us/#dataset-qualified-relation) Dataset's _**qualified relation**_ property

**Issue:**

- **Substantive Comment**: More documentation and full examples for this field would help show its suggested usage.

- **Rationale**: We're unsure of the recommended way to implement this field.

- **Proposed Disposition:** Clarification of Guidance

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by fellahst** [comment]
This issue has been addressed. See [Related Resources](https://doi-do.github.io/dcat-us/#related-resources) usage guideline section.
