### ISSUE TITLE
More information needed about the usage of Dataset's metadata distribution property

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#163]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.16.3](https://doi-do.github.io/dcat-us/#dataset-metadataDistribution) Dataset's _**metadataDistribution**_ property

**Issue:**

- **Substantive Comment**: According to the documentation, this field is the "distribution to 'original' metadata document". We aren't sure what information should go within this field or how this field is supposed to be utilized.

- **Rationale**: We need more information about its usage.

- **Proposed Disposition:** Clarification of Guidance

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by hkdctol** [comment]
this issue through 165 -- if it's a matter of providing some usage notes we should discuss what they should be and add them

**Comment by fellahst** [comment]
The DCAT-US 3.0 profile introduces a new [dcat-us:metadataDistribution](https://doi-do.github.io/dcat-us/#dataset-metadataDistribution) property on dcat:Dataset with range dcat:Distribution class with properties mandatory properties:

dcat:downloadURL
dcterms:title
dcat: mediaType - the encoding of the source metadata (e.g., XML, JSON, other)
dcterms: conformsTo - reference to schema specification/ standard for the source metadata

**Comment by TDabolt** [comment]
For implementation - Agencies may need to spend more time understanding new concepts introduced in DCAT 3.0
