### ISSUE TITLE
More information needed about the usage of Dataset's liability statement property

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#164]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.16.3](https://doi-do.github.io/dcat-us/#dataset-liability_statement) Dataset's _**liability statement**_ property

**Issue:**

- **Substantive Comment**: According to the documentation, this field is a "liability statement about the dataset". We aren't sure what that statement is.

- **Rationale**: We need more information about its usage.

- **Proposed Disposition:** Clarification of Guidance

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.
