### ISSUE TITLE
 Highlighting changes from DCAT-US 1.1 that require significant collection of additional information would be helpful.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#166]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.2](https://doi-do.github.io/dcat-us/#distribution-description) Distribution's _**description**_ property

**Issue:**

- **Administrative Comment**: The usage note indicates that "The description MUST be provided if the distribution contains only part of the data offered by the Dataset." This is a substantial change from DCAT-US 1.1 and should perhaps be made more obvious.

- **Rationale**: Highlighting changes from DCAT-US 1.1 that require significant collection of additional information would be helpful.

- **Proposed Disposition:** Clearer highlighting of change from DCAT-US 1.1.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by hkdctol** [comment]
Agree that highlighting differences from DCAT US 1.1 would be helpful

**Comment by fellahst** [comment]
Relaxed SHOULD to MAY in the usage note.
