### ISSUE TITLE
The link to the controlled vocabulary DATA-GOV-FT is broken and doesn't appear in a Google search.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#167]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.2](https://doi-do.github.io/dcat-us/#distribution-format) Distribution's _**format**_ property

**Issue:**

- **Substantive Comment**: The link to the controlled vocabulary DATA-GOV-FT is broken and doesn't appear in a Google search.

- **Rationale**: Clarity on documenting format metadata would be helpful.

- **Proposed Disposition:** Controlled vocabulary DATA-GOV-FT is documented.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by hkdctol** [comment]
General issue--that we should clarify when there are notional links--for content that doesn't exist yet

**Comment by fellahst** [comment]
Added [note](https://doi-do.github.io/dcat-us/#controlled-vocabularies-to-be-used) to indicate that referred vocabularies are placeholders.
