### ISSUE TITLE
Clarity on documenting format metadata would be helpful. Further description of the interaction between 'format' and 'mediaType' and/or explicit alignment with DCAT 3.0.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#168]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.2](https://doi-do.github.io/dcat-us/#distribution-format) Distribution's _**format**_ property

**Issue:**

- **Substantive Comment**: It's unclear how exactly this interacts with 'mediaType'. DCAT 3.0 seems to suggest using 'format' in cases where the distribution's media type can't be found in the IANA list of media types, whereas DCAT-US 3.0 seems to indicate using 'mediaType' where the format is unavailable (but doesn't indicate in which cases the format would be unavailable). Section 6.12.2 has more explanation but it may be inconsistent with this section.

- **Rationale**: Clarity on documenting format metadata would be helpful.

- **Proposed Disposition:** Further description of the interaction between 'format' and 'mediaType' and/or explicit alignment with DCAT 3.0.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by fellahst** [comment]
Updated [Distribution metadata guideline](https://doi-do.github.io/dcat-us/#distribution-guideline) addressing this issue.
