### ISSUE TITLE
It is unclear what the usage note "If necessary, a discussion to evaluate the adoption within the US should be launched" means.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#169]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.2](https://doi-do.github.io/dcat-us/#distribution-format) Distribution's _**format**_ property

**Issue:**

- **Substantive Comment**: It's unclear what the usage note "If necessary, a discussion to evaluate the adoption within the US should be launched" means.

- **Rationale**: Clarity on documenting format metadata would be helpful.

- **Proposed Disposition:** Clarification or removal of the sentence in question.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by TDabolt** [comment]
Proposed response - Delete - "If necessary, a discussion to evaluate the adoption within the US should be launched."
Flag for implementation concern and governance topic - maintenance / change control for future updates
