### ISSUE TITLE
Align updated schema with schema.org

### ISSUE THREAD

**Issue by hkdctol** [DOI-DO/dcat-us#17]
Hyon Kim
Data.gov 
GSA

## Requirement(s)

Updated schema should harmonize with schema.org

Including link to old discussion at https://github.com/project-open-data/project-open-data.github.io/issues/619

@philipashlock can you add specifics?

**Comment by fellahst** [comment]
As DCAT-US is based on DCAT-3, please refer to the[ alignment to schema.org ](https://www.w3.org/TR/vocab-dcat-3/#dcat-sdo) provided in the DCAT 3 specification

**Comment by TDabolt** [comment]
Important point for Implementation - just a few sentences on how by aligning w/ DCAT 3 government and users benefit since other organizations like Standards.org already map to the DCAT 3 specification.

**Comment by fellahst** [comment]
Aligning DCAT-US with DCAT 3, and consequently schema.org, significantly enhances data interoperability and usability. This alignment ensures that U.S. government datasets are consistent with global standards, facilitating international data sharing and collaboration. It also improves data discoverability and accessibility for a broader audience, as schema.org is widely recognized and used for structuring data on the web. Additionally, this move simplifies data publication for government entities, allowing them to leverage existing, widely-compatible tools and frameworks.
