### ISSUE TITLE
It's unclear how exactly Distribution's 'useRestriction' property interacts with 'accessRestriction' and 'cuiRestriction' (as well as 'rights', 'license' and 'accessRights')

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#173]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.2](https://doi-do.github.io/dcat-us/#distribution-use_restriction) Distribution's _**use restriction**_ property

**Issue:**

- **Substantive Comment**: It's unclear how exactly this interacts with 'accessRestriction' and 'cuiRestriction' (as well as 'rights', 'license' and 'accessRights').

- **Rationale**: Clarity on documenting legal metadata would be helpful.

- **Proposed Disposition:** Clarification of which fields are appropriate in which circumstances.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by fellahst** [comment]
Duplicated with #174
