### ISSUE TITLE
 It's unclear how exactly Distribution's CUI restriction property interacts with 'accessRestriction' and 'useRestriction' (as well as 'rights', 'license' and 'accessRights').

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#174]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.2](https://doi-do.github.io/dcat-us/#distribution-cui_restriction) Distribution's _**CUI restriction**_ property

**Issue:**

- **Substantive Comment**: It's unclear how exactly this interacts with 'accessRestriction' and 'useRestriction' (as well as 'rights', 'license' and 'accessRights').

- **Rationale**: Clarity on documenting legal metadata would be helpful.

- **Proposed Disposition:** Clarification of which fields are appropriate in which circumstances.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by hkdctol** [comment]
P1 for discussion

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.

**Comment by mrratcliffe** [comment]
+1
