### ISSUE TITLE
Substantial change to Distribution's title property from DCAT-US 1.1 should perhaps be made more obvious.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#175]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.2](https://doi-do.github.io/dcat-us/#distribution-title) Distribution's _**title**_ property

**Issue:**

- **Substantive Comment**: The usage note indicates that "The title MUST be given if the distribution contains only part of the data offered by the Dataset." This is a substantial change from DCAT-US 1.1 and should perhaps be made more obvious.

- **Rationale**: Highlighting changes from DCAT-US 1.1 that require significant collection of additional information would be helpful.

- **Proposed Disposition:** Clearer highlighting of change from DCAT-US 1.1.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by TDabolt** [comment]
Thank you for the feedback and we will review the documentation as well as flag for implementation documentation.

**Comment by fellahst** [comment]
Added the following note in title description: 

NOTE
Change from DCAT-US 1.1: In this version, it is mandated that the title property MUST be provided when the distribution contains only a part of the data offered by the Dataset. This is a change from DCAT-US 1.1 and aims to enhance clarity and specificity in data distribution, so it is easier for the user to distinguish roles of different distributions.
