### ISSUE TITLE
Clarification of what values appear in Distribution's representation technique property

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#176]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.3](https://doi-do.github.io/dcat-us/#distribution-representation-technique) Distribution's _**representation technique**_ property

**Issue:**

- **Substantive Comment**: It's unclear what kinds of values would be entered in this field, given that 'mediaType'/'format' (in combination with 'packageFormat' and 'compressFormat') seem to handle the "packaged/compressed file" situation.

- **Rationale**: Clarity on documenting format metadata would be helpful.

- **Proposed Disposition:** Clarification of what values appear in this field.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by fellahst** [comment]
Needs to add example for representationTechique

**Comment by fellahst** [comment]
Updated [Distribution metadata guideline](https://doi-do.github.io/dcat-us/#distribution-guideline) addressing this issue.
