### ISSUE TITLE
It's unclear how exactly Distribution's 'access rights' property interacts with 'license' and 'rights' (as well as 'accessRestriction', 'useRestriction', and 'cuiRestriction')

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#177]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.3](https://doi-do.github.io/dcat-us/#distribution-access-rights) Distribution's _**access rights**_ property

**Issue:**

- **Substantive Comment**: It's unclear how exactly this interacts with 'license' and 'rights' (as well as 'accessRestriction', 'useRestriction', and 'cuiRestriction'). There's some documentation in DCAT 3.0 related to how some of the fields work together, but it's unclear whether DCAT-US 3.0 is aligned here.

- **Rationale**: Clarity on documenting legal metadata would be helpful.

- **Proposed Disposition:** Clarification of which fields are appropriate in which circumstances.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by hkdctol** [comment]
P1 for discussion since it wasn't clear to me either

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.

**Comment by mrratcliffe** [comment]
+1
