### ISSUE TITLE
Distribution's byte size property is defined as a decimal, and the example shows a value with a partial byte

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#178]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.3](https://doi-do.github.io/dcat-us/#distribution-byte-size) Distribution's _**byte size**_ property

**Issue:**

- **Substantive Comment**: This field is defined as a decimal, and the example shows a value with a partial byte, but we aren't familiar with cases where files are actually measured in partial bytes. DCAT 3.0 recommends values have the non-negative integer type, and it isn't clear why being able to specify a partial byte would be useful.

- **Rationale**: Consistency with the definitions/usage notes in DCAT 3.0 is important for interoperability.

- **Proposed Disposition:** Changing the type to be more consistent with DCAT 3.0 and general practice, or (if that isn't feasible) an explanation for why a decimal type is used.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by ShaferAC** [comment]
+1

**Comment by mrratcliffe** [comment]
+1
