### ISSUE TITLE
Conforms to field--set values

### ISSUE THREAD

**Issue by hkdctol** [DOI-DO/dcat-us#18]
Bringing in old issue -- should conforms to field have common values? 

See https://github.com/project-open-data/project-open-data.github.io/issues/497

**Comment by TDabolt** [comment]
P1

**Comment by fellahst** [comment]
Thank you for highlighting the importance of establishing a registry of common values for the `dcterms:conformsTo` property. We acknowledge the challenge posed by the vast number of standards datasets may adhere to and understand the need for a curated set of well-known standards to streamline and standardize this aspect of data interoperability.

Moving forward into the implementation phase, our focus will be on developing a comprehensive registry that provides clear and accessible references to recognized standards. This initiative aims to ensure uniformity and clarity in dcterms:conformsTo entries, facilitating data harmonization across various systems and regions. Collaboration with international standards bodies and community feedback will be integral to this process.
