### ISSUE TITLE
Fix usage note for Distribution's conformsTo property and provide more clarity on documenting format metadata would be helpful.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#180]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.3](https://doi-do.github.io/dcat-us/#distribution-conforms_to) Distribution's _**conformsTo**_ property

**Issue:**

- **Substantive Comment**: The usage note says "This property refers to a page or document about this Data Service," which doesn't seem to make sense for this field. We presume that this is a placeholder that was copied/pasted and never replaced with the correct content.

- **Rationale**: Clarity on documenting format metadata would be helpful.

- **Proposed Disposition:** Replacement or clarification of the sentence in question.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by fellahst** [comment]
- Modified title "linked schemas" to "conforms to"
- Fixed usage note
- Added clarification note
- Updated JSON-LD

**Comment by fellahst** [comment]
Do we want to constraint cardinality to 0..1 (used in DCAT US 1,1) instead of 0..n. Do we have use cases for multiple standards for a single distribution ?

**Comment by ShaferAC** [comment]
+1; It might be beneficial to have the cardinality as 0...n in case there are distribution methods that utilize multiple standards.

**Comment by mrratcliffe** [comment]
+1 I agree with Allison's comment above... beneficial to have cardinality as 0...n

**Comment by fellahst** [comment]
Cardinality for [dcterms:conformsTo](https://doi-do.github.io/dcat-us/#distribution-conforms_to) remains to 0..n
