### ISSUE TITLE
Explanation of how to document multiple underlying formats or media types for Distribution that are packaged within a single file.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#182]
**Name:** Carrie Comstock

**Affiliation:** USEPA Office of Research and Development (ORD), Cummings.Carrie@EPA.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.18.3](https://doi-do.github.io/dcat-us/#distribution-media-type) Distribution's _**mediaType**_ property

**Issue:**

- **Substantive Comment**: There doesn't seem to be a way to indicate multiple underlying formats or media types in cases where files of different formats or media types are packaged in a single file (such as a ZIP or TAR file).

- **Rationale**: Some distributions will be packages that contain files in different formats or media types, and it would be useful to be able to document all of them.

- **Proposed Disposition:** Explanation of how to document multiple underlying formats or media types that are packaged within a single file.

Original email submission: 
[USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13430798/USEPA-ScienceHub-FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by sofianef** [comment]
This issue is very similar to #170. Candidate for duplicate ticket.

**Comment by fellahst** [comment]
Duplicated with #170
