### ISSUE TITLE
Lacking the diagram "The following diagram captures the relationship between DCAT and DCAT-US "

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#184]
**Name:** Brianna Key

**Affiliation:** NOAA, brianna.key@noaa.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [Section 3](https://doi-do.github.io/dcat-us/#conformance-to-dcat-3)

**Issue:**

- **Administrative Comment**: Lacking the diagram "The following diagram captures the relationship between DCAT and DCAT-US "

- **Proposed Disposition:** Add the diagram

Original email submission: 
[NOAA_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_BKey.xlsx](https://github.com/DOI-DO/dcat-us/files/13517567/NOAA_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix_BKey.xlsx)

**Comment by hkdctol** [comment]
P1 agree a diagram would be helpful

**Comment by fellahst** [comment]
DIagrams for core classes and supported classes have been added in the specification
