### ISSUE TITLE
Promoting a single license that may not be appropriate for many use cases, while ignoring other licenses that may be applicable, should be avoided in the usage guidance.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#185]
**Name:** Susan Allen

**Affiliation:** USPTO, susan.allen@uspto.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [9. License and rights statements ](https://www.w3.org/TR/vocab-dcat-3/#Class:Role) Role Class

**Issue:**

- **Critical Comment**: Point taken that machine-readable licenses are useful for interoperability. The "note" states that "it is recommended to use…such as those defined by  Creative Commons." This recommendation to use CC licenses is at odds with the statement that implementers should seek legal advice. There are several issues: 1) CC licenses generally are not recommended for "data" - several "open data" licenses have been developed to address this; 2) CC licenses only work if the datasets consist entirely of content created by the author (i.e. the federal agency is not in a position to apply a CC license to someone else's materials); and 3) CC licenses themselves are not interoperable: there are problems combining CC-BY with CC-BY-NC. It is advisable to strike the reference to a particular standard license and instead consider building out more comprehensive guidance about machine readable licenses and considerations about what license type may be best applicable. For federal materials created through extramural research, there may be a distinct set of licenses (e.g. a "federal purpose" license) that should be considered. It can also be made more clear how the licenses relate to the use restrictions (e.g. a CC-BY-NC) has a "use restriction" of non-commercial use. There is a similar category of "federal purposes" or "government use" restrictions. 

- **Rationale**: Promoting a single license that may not be appropriate for many use cases, while ignoring other licenses that may be applicable, should be avoided in the usage guidance.

- **Proposed Disposition:** Strike language recommending Creative Commons licenses (but retain reference to "IRIs" . Strike reference to "interoperability" and insert "transparency" or "machine readability". Clarify the connection between licenses, legal, and userestriction [(5.38)](https://doi-do.github.io/dcat-us/#properties-for-use_restriction).

Original email submission: 
[USPTO_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13517597/USPTO_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by hkdctol** [comment]
P1 and requires additional discussion

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.

**Comment by mrratcliffe** [comment]
+1
