### ISSUE TITLE
As use restrictions are often the inverse of permissions (licenses), consider revising the usage guidelines for licenses, legal, and use restrictions.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#186]
**Name:** Susan Allen

**Affiliation:** USPTO, susan.allen@uspto.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [5.38 UseRestriction](https://doi-do.github.io/dcat-us/#properties-for-use_restriction) [5.31 Program](https://doi-do.github.io/dcat-us/#properties-for-program)

**Issue:**

- **Substantive Comment**: As use restrictions are often the inverse of permissions (licenses), consider revising the usage guidelines for licenses, legal, and use restrictions.

- **Rationale**: Avoidance of legal liability; confusing and conflcting statements about use. 

- **Proposed Disposition:** Significantly revise the usage guidance for legal, licenses, and userestrictions. 

Original email submission: 
[USPTO_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13517597/USPTO_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by TDabolt** [comment]
We appreciate your suggestion and will be discussing ways to improve clarity and ease implementation.  We welcome specific changes in the current documentation to improve clarity and reduce confusion.

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata) in usage guideline has been added in the specification. This section will need to be reviewed by legal experts.

**Comment by mrratcliffe** [comment]
+1
