### ISSUE TITLE
Support the inclusion of known identifiers

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#187]
**Name:** Susan Allen

**Affiliation:** USPTO, susan.allen@uspto.gov

**Type of issue:** Schema, Editorial

Section # / Table #: [6.1.3 Identifier Resolution services](https://doi-do.github.io/dcat-us/#identifier-resolution-services) 

**Issue:**

- **Substantive Comment**: Support the inclusion of known identifiers. However, there are many more that may be relevant (e.g. ISNI in addition to ORCID), and interoperable. Consider establishing more thorough guidance surrounding identifiers. 

Original email submission: 
[USPTO_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx](https://github.com/DOI-DO/dcat-us/files/13517597/USPTO_FAIRness.Project.-.DCAT-US-3-AP.-.Comment.Review.Matrix.xlsx)

**Comment by TDabolt** [comment]
P2 - potentially modify language. "In the digital realm, ensuring consistent and persistent access to resources is paramount. Identifier Resolution Services play a crucial role in achieving this by providing unique and persistent identifiers for various digital objects and entities. This section delves into several prominent services, detailing their functions and significance in the broader digital ecosystem."  = add follow on text = This is not an exhaustive list and is included as examples.  (or something along those lines"

**Comment by fellahst** [comment]
Added sentence : "Please note that this is not an exhaustive list but rather a selection of examples intended to illustrate the diversity and importance of such services" in  [Identifier Resolution services ](https://doi-do.github.io/dcat-us/#identifier-resolution-services) section.

**Comment by mrratcliffe** [comment]
+1
