### ISSUE TITLE
Dataset property summary table incomplete

### ISSUE THREAD

**Issue by hmaier-fws** [DOI-DO/dcat-us#188]
_This information will help the Core Team resolve issues with the draft DCAT3-US application profile.  So we can track all issues, please submit different issues in separate issue tickets. The Core Team will review and adjudicate the submitted issue and provide comments on this ticket indicating steps taken to address the issue as submitted._

**Name:**  Hilmar Maier

**Affiliation:** U.S. Fish and Wildlife Service

**Type of issue:** Editorial

**Issue:**

The Dataset property summary table [5.16 Dataset](https://doi-do.github.io/dcat-us/#properties-for-dataset) seem to be incomplete. For example, the summary table does not contain an entry for [Property: spatial resolution](https://doi-do.github.io/dcat-us/#dataset-hasQualityMeasurement) ("quality measurement" links here), [type](https://doi-do.github.io/dcat-us/#dataset-type), or [usage note](https://doi-do.github.io/dcat-us/#dataset-usage-note).

I have not performed an exhaustive comparison of the table and the body of the document so there may be more inconsistencies.

**Recommended change(s):**

  - List all dataset properties described in the document in the dataset summary table
  - Ensure the property name listed in the table match the property name as described in the document

**Comment by TDabolt** [comment]
Good catch Helmar.  Will address pending resources
p-3

**Comment by fellahst** [comment]
Fixed and checked. Modified vann:usageNote to skos:scopeNote based on https://github.com/w3c/dxwg/issues/233
