### ISSUE TITLE
Loosen limit on text for rights field

### ISSUE THREAD

**Issue by hkdctol** [DOI-DO/dcat-us#19]
The "rights" field currently has a character limit, which prevents fully documenting certain issues.

See discussion at https://github.com/project-open-data/project-open-data.github.io/issues/490

**Comment by fellahst** [comment]
There is no limit on the [attributionText](https://doi-do.github.io/dcat-us/#rights-statement-attributionText) of [RightsStatement](https://doi-do.github.io/dcat-us/#properties-for-rights-statement).
