### ISSUE TITLE
References to "data.resources.gov"

### ISSUE THREAD

**Issue by hkdctol** [DOI-DO/dcat-us#190]
Looks like examples such as https://doi-do.github.io/dcat-us/#properties-for-access_restriction refer to eventually schema or controlled vocabulary on "resources.data.gov" but are written "data.resources.gov" -- also should make clear that these links do no yet exist.

**Comment by TDabolt** [comment]
P1 - Concur

**Comment by fellahst** [comment]
All references to data.resources.gov have been renamed to resources.data.gov to be compatible with the web site url

**Comment by mrratcliffe** [comment]
+1

**Comment by jbrown-xentity** [comment]
This was not addressed, only the human readable references.
There are still 50 instances of data.resources.gov links in the repository in various locations: https://github.com/search?q=repo%3ADOI-DO%2Fdcat-us%20data.resources.gov&type=code
This will lead to bad conformance of standards and usage. Please re-open this issue and fix issues.
Also curious as to what the plan is for this release; many of these links (even when the root URL is fixed) do not lead to a valid webpage. Is it intended that this documentation will be released on resources.data.gov at the various endpoints, and these links will become valid?
