### ISSUE TITLE
Fix normative versus informative reference in specification

### ISSUE THREAD

**Issue by fellahst** [DOI-DO/dcat-us#193]
In several sections of the DCAT-US specification, references that should be classified as normative (essential and mandatory for the implementation of the standard) are currently listed or treated as informative (supplementary and non-essential).
Conversely, certain informative references, which provide additional context or clarification, appear to be mistakenly classified as normative.

Remediation:

- Conduct a thorough review of the specification to correctly classify and label each reference as either normative or informative.
- Ensure that all normative references are indeed integral to the implementation and understanding of the DCAT-US specification.
- Update the document to clearly differentiate between these two categories of references, possibly with distinct sections or annotations.

**Comment by TDabolt** [comment]
Agree this needs to be done

**Comment by fellahst** [comment]
Fixed. Also resolved broken references and resolution of references when page is loaded the first time.

**Comment by mrratcliffe** [comment]
+1
