### ISSUE TITLE
Require standard DATE fields

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#20]
**Creator Name:** : Adirenne Truex
**Creator Affiliation:** : U.S. Fish & Wildlife Service

## Requirement(s)

Require these standard DATE fields:
- `dateYear` Field as 4-digit number `YYYY`;   
- `dateMonth` Field as 2-digit number `MM`;
-  `dateDay` Field as 2-digit number `DD`  (default is 00).

to allow download of data files which can incorporate these three fields into the file name, for example:        `YYYYMMDD_<author>_<subject/title>`

## Problem Statement

**Description**:  All DOI agencies which get litigated must regularly produce hundreds to thousands of documents and datasets to the courts as an Administrative Record (AR) for each. Files related to litigation must be in DATE order, both in the Index as required by the Courts and the Dept. of Justice and as listed in the computer folders of the files that are provided as part of the AR.  All must be delivered by court-ordered dates.  Each document or project file in the AR must be indexed (Excel) and include the Date, Author, Description and a hyperlink, and the files must be in Date order in the folders, for the required BATE-STAMP for every file.   

Using a full DATE at the beginning of filenames starting: `YYYYMMDD` ensures all files will list in proper order in computer folders, thus providing extreme efficiency and meeting Court and DOJ requirements for DOI AR’s. 

(BATE stamping consecutively numbers every page of every document for the entire AR, in the order in which files list within each folder A-Z or 0-9). 

Nearly all bureaus are litigated, and most must produce an Administrative Record which is compiled by program employees involved in the case topic, with assistance from a single Litigation Coordinator if one exists, with federal Solicitors review. 

To discover, review, process, Index, and finally Bate-stamp the large amount of documents required for AR’s and meet court-ordered due dates, agency decision files, drafts and other supporting documents must be named consistently, in this format with the full DATE first to allow Indexing and Bate-stamping in file DATE order: 

`<YYYYMMDD>_<AUTHOR>_<TITLE or SUBJECT>.<ext>`

1. efficiently discover and collect needed documents. 
2. effectively review the project timeline documents by following their DATE order. 
3. automatically list/index all AR files in DATE order in the required format. 
4. automatically properly Bate-stamp all AR files in the AR folders in the same order as the Index. 

Additionally, it will: 
- facilitate discovery by employees searching files within specific date-ranges; 
- facilitate review of documents downloaded with this filename format to quickly discover potentially missing documents related to court cases or other.   

Currently, employees have no required file-naming conventions making discovery of needed chronological documents for court cases exceedingly time-consuming.  Important documents may easily be missed which would otherwise support the federal position. 

When Court deadlines are missed or case Administrative Records are not complete or well-described, agencies are more likely to lose their case, thus costing each program. 

**Stakeholders affected – Target Audience Value-Added:** 
- All DOI depts which are required by courts and the Dept. of Justice to provide an Administrative Record Index and Bate-stamped files in DATE-order. 
- All employees involved in document discovery for AR’s, FOIA or other needs - Public or internal.  
- Litigation Coordinators, Project leads, all employees assigned to compile Administrative Records, who must be able to easily find, download, organize, review and certify court records are complete. 

## Target Audience / Stakeholders

**Requirement/Impact to:**  
Developers/Designers of Federal datasets. 

**Stakeholders**  
- User 1.  Any DOI Bureaus, Departments and programs that get litigated. 
- User 2.  Metadata developers and metadata extractors. 
- User 3.  Program leads, administrative assistants, Litigation teams/coordinators. 
- User 4.  Program budgets - Financial savings in personnel time and court outcomes.  

## Intended Uses / Use Cases

- **Use 1.** Improved fulfillment of FOIA and Litigation requirements.  
- **Use 2:** Expedited review of  thousands of document records to meet court deadlines. 
- **Use 3.** Efficient discovery and identification of federal decision files and project decision chronology. 
- **Use 4.** Research and improved discovery for future employees to find and review past decisions over time (ex Endangered Species Act reviews and related decision documents). 
- **Use 5.** Provide for the ability to download and rename files to a standard naming convention for consistent organization of computer libraries in all DOI programs. 

## Existing Approaches

Currently whomever is assigned to compile an AR will receive hundreds to thousands of poorly named documents and **must re-name each and every one to this format**:  

**`YYYYMMDD_AUTHOR_SUBJECT/TITLE`**

Alternatively, a hyperlink to each document will be imported into an Excel column using a third-party purchased tool, and the compiler will have to **open each document using the hyperlink to extract by hand the DATE, the AUTHOR and the TITLE or Subject** if it can be determined. 

Employee leads on oft-litigated topics come and go, and with no Data Management nor File Management requirements, documents both draft and final are currently very poorly named and placed usually wherever the employee chose to work. If documents are not OCR-scanned for text recognition then it is impossible to locate them through searches.  

## Additional context, comments, or links

There is little guidance for Employees trying to properly compile DOI’s defenses in court cases, and most are not equipped with the proper tools to do so. Instructions come directly from agency Solicitors and the Department of Justice. It is a dire need to provide basic Database Fields that will help the entire process by simply being able to download documents from federal data collections so the files can be named with their full date when downloaded.   

Currently, needed metadata is either not collected in Microsoft documents, or not systematically retrievable and there are no provided tools to extract what does exist that may be useful.  Adobe Acrobat DC is the only program provided that can collect MS Outlook metadata, and that is only if collected from MS Outlook email program as an Adobe Portfolio.

**Comment by fellahst** [comment]
### Addressing Standard Date Field Requirements:

Regarding your requirement for a standardized date field format to facilitate data file management and legal documentation processes, the current data representation in DCAT, based on widely adopted XML Schema data types like `xsd:date`, `xsd:dateTime`, `xsd:gYear`, may not directly accommodate the specific format (YYYYMMDD) you outlined. This format is quite application/domain-specific and may not favor interoperability in a broader context.

### Recommendation:

While the DCAT standard aims for broad interoperability and flexibility, it might not align with the very specific file naming and ordering requirements for legal and administrative records as described. For your specific needs, a custom solution that integrates the required date format into file naming for legal documentation purposes might be necessary. This could involve developing a system or tool tailored to the unique requirements of the U.S. Fish & Wildlife Service and similar agencies within the DOI, which is out of scope for this effort.  It is essential to balance the need for specific data formats for legal and administrative purposes with the broader goal of data interoperability and accessibility within the DOI and public domains.

**Comment by TDabolt** [comment]
Thank you for the suggestion.  Your comment was considered and file naming conventions are out of scope for this specific effort.
