### ISSUE TITLE
Make our open data sets compatible with Data.gov and other online harvesting or searching tools

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#21]
**Creator Name:** Erin Elzi, Lindsay Goldstein
**Creator Affiliation:** Digital Services Specialist, Lindsay.goldstein@onrr.gov and Erin.elzi@onrr.gov

## Requirement(s)

Provide an easy-to-use, flexible, and specific schema that makes our open data sets compatible with data.gov and other online harvesting or searching tools,  and can be used to increase the SEO.

## Problem Statement

No problems to report,  but would utilize a specific metadata schema if required and available. 

## Target Audience / Stakeholders

- User 1: Question Answerers
- User 2: Domain Learners
- User 3: Agenda Supporter
- User 4: Storytellers 

## Intended Uses / Use Cases

- Use 1. Increase the findability of our datasets 
- Use 2. Increase the compatibility of our datasets
- Use 3. increase the findability of specific data points

**Comment by fellahst** [comment]
Thank you for reaching out regarding the implementation of a metadata schema for your open data sets. We recommend adopting the DCAT-US 3.0 schema, which represents a significant upgrade from the DCAT-US 1.1 version, aligning with the latest DCAT-3 standards already supported by data.gov.

### Advantages of Upgrading to DCAT-US 3.0:

- Alignment with DCAT-3: DCAT-US 3.0 is designed to be in sync with DCAT-3, ensuring advanced compatibility and functionality. This alignment facilitates seamless integration with platforms like data.gov.
- Enhanced User Experience and SEO: The upgraded schema offers improved ease of use, flexibility, and a specific structure that is conducive to better SEO, making your datasets more discoverable and accessible.
- Collaborative Development: The development of DCAT-US 3.0 is conducted in collaboration with participants from data.gov, incorporating their inputs to ensure the schema is well-tuned for interoperability and user needs.

Although you have not reported any specific problems, transitioning to DCAT-US 3.0 should be considered a proactive step to stay aligned with the latest data cataloging standards and to enhance the visibility of your datasets. If you encounter any challenges or have questions during this transition, we are here to provide the necessary support and guidance.

We are committed to assisting you in leveraging the full potential of DCAT-US 3.0 for your data publication and discoverability goals.

**Comment by mrratcliffe** [comment]
+1
