### ISSUE TITLE
SOLVED - Maintain a current list of federal ArcGIS server addresses

### ISSUE THREAD

**Issue by Jelfff** [DOI-DO/dcat-us#22]
For 5+ years I have curated a list of 3,000+ addresses for ArcGIS servers at all levels of government, from federal to local.  Each week my code scans each address.  An exception report is reviewed by hand and any bad links are either fixed or flagged.  An updated list is published as a PDF, txt and csv file each week, usually on Wednesday.  

Since this **unique work** has a large benefit for anyone seeking spatial government data, it seems reasonable that **I should be paid for doing this**.

Open PDF: https://mappingsupport.com/p/surf_gis/list-federal-state-county-city-GIS-servers.pdf

Joseph Elfelt
Redmond, WA
https://mappingsupport.com

**Comment by fellahst** [comment]
Out of scope for this effort
