### ISSUE TITLE
Metadata tag for policy dependencies (DEPENDSON)

### ISSUE THREAD

**Issue by basilwhite** [DOI-DO/dcat-us#23]
**Basil White** 
**Office of Enterprise Integration, Department of Veterans Affairs** 

## Requirement(s)

Include a property DEPENDSON that indicates how requirements depend on other requirements for delivery, e.g.,: 
- Public Law and US Code that DEPENDSON Agency directives 
- President's Management Agenda goal that DEPENDSON Agency Strategic Plan objectives
- Agency performance and evaluation plans that DEPENDSON Federal operations and programs as per the Evidence Act and OMB M-19-23
- Evidence Act and OMB A-11 compliance that DEPENDSON Evidence Act Capacity Assessments and budget evidence submissions

## Problem Statement

* The Foundations for Evidence Based Policymaking Act requires Agencies to plan to develop a Learning Agenda.
* The Government Performance Results Act as summarized in OMB A-123, requires that "Federal leaders and managers are responsible for...a governance structure defined through...sources, including laws...Executive directives and Agency policies." 
* This structure, the "Federal Governance Structure (FGS)", includes various types of governance including laws, regulations, policies, strategies, OMB memoranda, and Executive Orders.
* The FGS is a network of governance relationships enforced by Executive Orders, OMB memoranda, and Public Laws, including the Evidence Act, GPRA and GPRAMA. The FGS includes links to public sources of governance titles, and all FGS entries are available to the public.
* Federal planners and policymakers do not have access to the FGS. As a result, new policies and plans do not benefit from a systemic awareness of interdependencies across policies, plans, regulations, Executive Orders and Public Laws.
* Several Agencies are collaborating on a relational database to provide access to the FGS, to help planners and policymakers:
** understand and communicate how their plans, policies and performance metrics contribute to the FGS;
** increase program value, efficiency and effectiveness based on FGS interdependencies; and
** use the structure as a basis of evidence to improve the FGS, including evidence-based policymaking, strategic planning, performance metrics, legislative ingest, budget proposals and legislative proposals

## Target Audience / Stakeholders

* User 1. Developers and managers of Federal governance collections, e.g., Agency policies and performance measures
* User 2. Researchers who track and report Agency compliance with Public Laws, US Code, Executive Orders and OMB guidance
* User 3. Analysts who recommend policy, program and strategic changes based on new Federal governance
* User 4. Federal leaders who use goverance interdependencies as a basis of evidence for policymaking and planning
* User 5. Federal and library metadata experts, to map governance titles in the FGS database to other collections
* User 5. Application Programming Interface (API) developers, to query and present FGS titles in their interfaces
* User 6. Budget developers, to explain how budget lines support delivery of Federal mandates and priorities
* User 7. Developers of legislative proposals, to provide evidence of how a legislative change supports mandates and priorities in the FGS,

## Intended Uses / Use Cases

* Use 1. Create DEPENDSON relationships between titles in governance collections*
* Use 2. Sort/query governance collections based on interdependencies*
* Use 3. Present queries as basis of evidence for strategic communications on Agency delivery of goals, performance, accountability and compliance*
* Use 4. Present queries as basis of evidence for policymaking, planning, performance metrics, legislative ingest and legislative proposals*
* Use 5. Sort/query database for delivery and compliance across multiple Agencies for discrete mandates*

## Additional context, comments, or links

Academic publications, trade articles, live browsable dataset, training videos, support - https://community.max.gov/x/fwoDTQ

**Comment by fellahst** [comment]
This is out of scope for this specification

**Comment by TDabolt** [comment]
@fellahst Pls add to the response The linkage between data products and data sets back to the underlying law, regulation or government wide policy is an important consideration consistent with the Evidence Act.  Within current resource constraints this issue is out of scope however maybe re-opened in future updates.

**Comment by fellahst** [comment]
Final response: This is out of scope for this specification. The linkage between data products and data sets back to the underlying law, regulation or government wide policy is an important consideration consistent with the Evidence Act. Within current resource constraints this issue is out of scope however maybe re-opened in future updates.
