### ISSUE TITLE
Identify the following data assets (and potential new data fields for the following data assets)

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#24]
**Creator Name:** Ling(Jenny) Shi
**Creator Affiliation:** Computer scientist, ling.shi@sba.gov, SBA

## Requirement(s)

Identify the following data assets(add potential new data fields for the following data assets)

1. priority data assets
2. Covid-related data assets
3. data assets that support Artificial Intelligence research
4. high-value geospatial data act investment-related data assets
5. data assets that relate to interagency wildland fire fuels data management

## Problem Statement

FDS Action Plan requires the identification of those 5 data assets. But Current CDI(Comprehensive Data Inventory metadata document does not clearly identify if the assets are belonging to those 5 data assets and didn’t provide options and measurements to let agencies mark it.

## Target Audience / Stakeholders

Target Audience:

- Data Consumers: include Covid Data Consumers, Geospatial data act users, Wildland fuels data Consumers,
- Compliance officers
- Users/builders of AI models –this target audience is especially for data assets that support AI research

## Intended Uses / Use Cases

- Know which assets in the CDI are priority data assets 
- Identify Covid-related assets within the CDI
- Know which assets support AI research use cases 
- Identify assets that are high-value geospatial data act related 
- Know which assets pertain to wildland fire fuels data management.

## Attachments
[DCAT-US-3-Requirements_SBA.docx](https://github.com/DOI-DO/dcat-us/files/11909591/DCAT-US-3-Requirements_SBA.docx)

**Comment by fellahst** [comment]
These requirements are addressed in [Resource Classification Guideline ](https://doi-do.github.io/dcat-us/#resource-classification) section in the specification
