### ISSUE TITLE
Public Dataset Determination

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#25]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd - determination made that dataset is public)*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
Whether the data asset is a public data asset that has been or could be made available as an open Government data asset, given the considerations in Section VI above, and the date, if available, of the determination  

## Problem Statement
Title II of the Open Data Act says that by default, data should be made public, however there are many instances were agency datasets may contain CUI, be deliberative or otherwise constrained from publication.  The process/decisionmakers involved in that determination, along with the date of determination would be good to have documented for auditing purposes

## Target Audience / Stakeholders
Data owners, auditors

## Intended Uses / Use Cases
Documenting when, how, and by whom a determination was made to make the dataset public

## Additional context, comments, or links
Driver: 44 U.S.C. § 3511(a)(2)(A)(iii)"

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.

**Comment by TDabolt** [comment]
Also flag for implementation documentation and discussion
