### ISSUE TITLE
Machine Learning: Associated tasks

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#27]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd associated ml tasks)*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
relevant/appropriate ml tasks, i.e. classification 

## Problem Statement
Identifying what kinds of analyses would be relevant or appropriate for the dataset.  Example:  UCI ML Repository

## Target Audience / Stakeholders
Data Scientists

## Intended Uses / Use Cases
Example:  Dataset could be used for ML classification and segmentation

## Additional context, comments, or links
Supports AI Executive Order 13859

**Comment by fellahst** [comment]
WE decided to keep the dcat-us:purpose with a ltteral range as there are not many purpose taxonomies available out there.
