### ISSUE TITLE
Data Dictionary / Attribute Characteristics

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#28]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd attribute characteristics)*
Priority: *Medium*
Element Description / Requirement / Recommendation
element types - categorical, integer, real etc)

## Problem Statement
Provide data dictionary, and identify data element types.   Example:  UCI ML Repository

## Target Audience / Stakeholders
Public, data scientists

## Additional context, comments, or links
Supports AI Executive Order 13859

**Comment by fellahst** [comment]
Use the property dcat-us:describedBy pointing to a dcat:Distribution. See also discussion  in #138
