### ISSUE TITLE
DOI for Scientific Citation

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#29]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd citation)*
Priority: *Medium*
Element Description / Requirement / Recommendation
citation (If applicable) - can this be constructed for display from existing elements, with dataset identifier DOI (if available) 

## Problem Statement
Provides a means for citing the dataset if used in a scientific journal.  Recommend using a versioned DOI   Example:  UCI ML Repository

## Target Audience / Stakeholders
Researchers

## Intended Uses / Use Cases
Provides a consistent way for the dataset to be referenced in research. 

## Existing Approaches
Versioned DOI

**Comment by fellahst** [comment]
This requirement has been addressed. See [Related Resources](https://doi-do.github.io/dcat-us/#related-resources) usage guideline section.

**Comment by mrratcliffe** [comment]
+1
