### ISSUE TITLE
Determine whether program/bureau codes are necessary in federal schema

### ISSUE THREAD

**Issue by hkdctol** [DOI-DO/dcat-us#3]
- Hyon Kim - Data.gov - GSA
- Program and bureau codes are currently required fields in the DCAT US 1.1 federal schema
- Program code list has not been maintained and used
- Unclear status of bureau code as far as OMB use/management

Need to determine status/use/need of these codes and if not required, remove as required fields. Or if there's an alternative that is a more current/widely known and used list, adopt that.

**Comment by TDabolt** [comment]
See other ticket for discussion on an approach to handle "agency" codes which balances consistency w/ flexibility in maintenance.  Upper most level - Department / Agency should be a controlled vocabulary.  Sub-level entities should be maintained at the Department / Agency level as distinct vocabularies.  Discuss and demonstrate approach in implementation documentation

**Comment by fellahst** [comment]
The property has been deprecated. See https://github.com/DOI-DO/dcat-us/issues/110

**Comment by fellahst** [comment]
The property [programCode](https://resources.data.gov/resources/dcat-us/#programCode) and [bureauCode](https://resources.data.gov/resources/dcat-us/#bureauCode)   have been deprecated in DCAT-US. See #110.
