### ISSUE TITLE
Influential Data tag

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#30]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd - Influential)*
Priority: *High*
Element Description / Requirement / Recommendation
Tag for identifying that this dataset was used for agency decisionmaking.  required

## Problem Statement
Required per M-19-15

## Target Audience / Stakeholders
Public, Agency decisionmakers

## Intended Uses / Use Cases
Identifying 'Influential Data' used for agency decisionmaking

## Additional context, comments, or links
Required: OMB Memorandum M-19-15, Improving Implementation of the 763 Information Quality Act (Apr. 12, 2019)

**Comment by fellahst** [comment]
I suggest to use dcat:keyword with well-defined keyword defined by a specific community. See [Resource Classification](https://doi-do.github.io/dcat-us/#resource-classification)
