### ISSUE TITLE
Data Quality / Missing Data

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#31]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd data quality - missing values)*
Priority: *Medium*
Element Description / Requirement / Recommendation
dataset has missing values

## Problem Statement
Inform users as to whether the dataset contains missing values.  Example:  UCI ML Repository

## Target Audience / Stakeholders
Data scientists

## Intended Uses / Use Cases
Alerts data users to missing values, which may break some algorithms

## Additional context, comments, or links
Supports AI Executive Order 13859

**Comment by fellahst** [comment]
### Recommendation for Representing Missing Values in Datasets:

To address the requirement of informing users about missing values in datasets, it is recommended to use the `dqv:QualityMeasurement `property from the Data Quality Vocabulary (DQV). This approach aligns with the guidelines of documenting data quality within the DCAT framework.

### Implementing dqv:QualityMeasurement for Missing Values:

`dqv:QualityMeasurement`: Utilize this property to specifically indicate and quantify the presence of missing values in a dataset. This quantitative measure can detail the extent or percentage of missing data, offering a clear understanding of the dataset's completeness.
The use of  `dqv:QualityMeasurement` allows for a structured and standardized way to represent this aspect of data quality, making it both machine-readable and easily interpretable by data scientists and other users. You can find more details in [usage guideline for data quality](https://doi-do.github.io/dcat-us/#data-quality) in the specification.
