### ISSUE TITLE
Dataset Characteristics

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#32]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd dataset characteristics)*
Priority: *Medium*
Element Description / Requirement / Recommendation
Type of dataset (i.e. multivariate tabular, etc)  optional

## Problem Statement
Inform users on what kind of dataset it is

## Target Audience / Stakeholders
Public, data scientists

## Additional context, comments, or links
Supports AI Executive Order 13859

**Comment by fellahst** [comment]
See usage of `dcterm:type` in [Resource Classification](https://doi-do.github.io/dcat-us/#resource-classification) usage guideline
