### ISSUE TITLE
Identification of High Priority Dataset for Release

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#33]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd -identification of priority dataset for release)*
Priority: *High*
Element Description / Requirement / Recommendation
Agency Open Data Plans shall identify as priority data assets any data asset for which disclosure would be in the public interest, and establish a plan to evaluate each priority data asset for disclosure on the Federal Data Catalogue as a public data asset.

## Problem Statement
Requirement to identify priority datasets, could be done via metadata element and aggregated for Open Data Plan

## Target Audience / Stakeholders
Public, data owners, auditors

## Intended Uses / Use Cases
Meet open data requirements

## Additional context, comments, or links
44 U.S.C. § 3506(b)(2)(B)(v); see also 44 U.S.C. § 3511(b)

**Comment by fellahst** [comment]
Suggest to use one of the classifiers documented in [Resource Classification](https://doi-do.github.io/dcat-us/#resource-classification)
