### ISSUE TITLE
Quantify number of instances in dataset

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#35]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd number of instances in dataset)*
Priority: *Low*
Element Description / Requirement / Recommendation
Record count optional

## Problem Statement
Useful to capture and document internally for tracking changes over time to a dataset, or for flagging an anomaly, for example if feature count suddenly drops.  However, also informative if published  Example:  UCI ML Repository

## Target Audience / Stakeholders
Public, data owners, data scientists

## Additional context, comments, or links
Supports AI Executive Order 13859

**Comment by fellahst** [comment]
## Recommendation for Documenting Record Counts in Datasets:

To address the requirement for capturing and documenting the number of instances or record counts in datasets, it is recommended to leverage both provenance information as outlined in DCAT-US and the `dqv:QualityMeasurement` property from the[ Data Quality Vocabulary (DQV)](https://www.w3.org/TR/vocab-dqv/).

### Implementation Suggestions:

#### Utilizing Provenance Information:

Provenance metadata in DCAT-US can be used to document historical changes and updates to a dataset. This includes tracking changes in the dataset's size or record count over time, thereby aiding in anomaly detection or internal tracking.
The provenance information can include timestamps and descriptions of updates, providing a clear history of how the dataset has evolved. More details can  be found in [provenance metadata usage guideline](https://doi-do.github.io/dcat-us/#provenance-metadata).

### Employing dqv:QualityMeasurement for Record Counts:

`dqv:QualityMeasurement` can be used to quantify the current number of records or instances in a dataset. This approach offers a standardized, machine-readable method to represent the dataset's size.
Recording this metric as a quality measurement facilitates easy identification of significant changes or anomalies in the dataset's size, which can be crucial for data scientists and other stakeholders. More details can  be found in [quality data usage guideline](https://doi-do.github.io/dcat-us/#data-quality).
