### ISSUE TITLE
Link to reference on ML applications

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#36]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd references - ml)*
Priority: *Medium*
Element Description / Requirement / Recommendation
Link to documentation on AI/Machine Learning applications optional

## Problem Statement
This may more ideally link to a Model Card relating to the dataset

## Target Audience / Stakeholders
Data scientists

## Intended Uses / Use Cases
Provides context on how the dataset is used in machine learning

## Additional context, comments, or links
Supports AI Executive Order 13859

**Comment by fellahst** [comment]
In light of the aim to maintain simplicity and generality in the DCAT-US specification, leveraging the existing properties of [dcterms:description](https://doi-do.github.io/dcat-us/#dataset-description) and [dcat-us:purpose](https://doi-do.github.io/dcat-us/#dataset-purpose) is a prudent approach to address the requirements of determining a dataset's potential for reuse and its applicability. See also  #56
