### ISSUE TITLE
Reference papers / journal articles citing the dataset

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#37]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd references - papers citing this dataset)*
Priority: *Medium*
Element Description / Requirement / Recommendation
reference type / citation / paper citing doi (If applicable)

## Problem Statement
References, broken out separately from other cited references.  This would be where dataset owners could cite where their datasets are being used and cited in research

## Target Audience / Stakeholders
Data owners, researchers, public

## Intended Uses / Use Cases
Provides context and examples of how the dataset is being used in the wild.  Example:  UCI ML Repository

## Additional context, comments, or links
Supports AI Executive Order 13859

**Comment by fellahst** [comment]
This requirement has been addressed. See [Related Resources](https://doi-do.github.io/dcat-us/#related-resources) usage guideline section.
