### ISSUE TITLE
Peer Review documentation

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#38]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd references - peer review)*
Priority: *Medium*
Element Description / Requirement / Recommendation
Link to documentation on peer review - suggest required-if-applicable if dataset used for agency decisionmaking

## Problem Statement
Make documentation on  Peer Review findable, in compliance with IQA and M-19-15

## Target Audience / Stakeholders
Public, Agency decisionmakers, auditors

## Intended Uses / Use Cases
Provides insight into data quality and how the dataset was evaluated.

## Existing Approaches
Currently ad-hoc, by program

## Additional context, comments, or links
OMB Memorandum M-19-15

**Comment by fellahst** [comment]
This requirement has been addressed. See [Related Resources](https://doi-do.github.io/dcat-us/#related-resources) usage guideline section.
