### ISSUE TITLE
Reference QAPP Documentation

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#39]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd references - QAPP)*
Priority: *Low*
Element Description / Requirement / Recommendation
Link to QAPP (where applicable)

## Problem Statement
Make documentation available on what the QA process was for validating the data.  This is required by IQA and M-19-15

## Target Audience / Stakeholders
Public, Agency decisionmakers, auditors

## Intended Uses / Use Cases
Provides insight into data quality and how the dataset was evaluated.

## Existing Approaches
Currently ad-hoc, by program

## Additional context, comments, or links
EPA requires that all environmental data used in decision making be supported by an approved Quality Assurance Project Plan (QA Project Plan).  ORD also requires QAPPs.
This requirement is defined in EPA Order 5360.1 A2 (EPA 2000), Policy and Program Requirements for the Mandatory Agency-wide Quality System, for EPA organizations. Non-EPA organizations funded by EPA are required to develop a QA Project Plan through:
48 CFR 46, for contractors;
40 CFR 30, 31, and 35

**Comment by fellahst** [comment]
This requirement is addressed by using related resources properties. See [Related Resources](https://doi-do.github.io/dcat-us/#related-resources) usage guideline section.
