### ISSUE TITLE
License field - permit something other than a URL

### ISSUE THREAD

**Issue by hkdctol** [DOI-DO/dcat-us#4]
- Hyon Kim - Data.gov - GSA
- Current schema only permits a URL in the license field
- Data.gov team has heard from agencies that they require flexibility - putting in text in this field rather than URL for one license

Consider this in the broader look at the license field - whether there needs to be an option other than a pick list of licenses with associated URLs.

**Comment by hkdctol** [comment]
Adding a reference from https://github.com/project-open-data/project-open-data.github.io/issues/537

**Comment by fellahst** [comment]
This requirement has been addressed in the specification by introducing the class[ dcterms:LicenseDocument](https://doi-do.github.io/dcat-us/#properties-for-license-document).

**Comment by hkdctol** [comment]
I'd like discussion at next meeting on how this works on tailoring license terms
