### ISSUE TITLE
Guidance on rights and access to data

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#40]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd references - rights/access reference)*
Priority: *High*
Element Description / Requirement / Recommendation
Information and guidance on who may access sensitive data and process for access.  Recommend standardizing for some of these where applicable, i.e.  FOIA, or Evidence Act Title III process for sharing sensitive statistical data   Recommend required-if-applicable based on accesslevel and rights

## Problem Statement
Provide clear details on business rules and process for how the dataset can be accessed, if it contains sensitive data.  This should also be tied into the Secure Data Service effort under the CDO Council

## Target Audience / Stakeholders
Agency analysts

## Intended Uses / Use Cases
Helps to facilitate access to sensitive and non-public datasets.

## Existing Approaches
Varies by program

## Additional context, comments, or links
Supports Evidence Act

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.
