### ISSUE TITLE
Usage and Access Metrics

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#41]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *(tbd usage/access metrics)*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
number of hits, dynamic or frequently refreshed optional

## Problem Statement
Identify popular datasets, useful in business case for data investments and other uses.  Example:  UCI ML Repository

## Target Audience / Stakeholders
Data owners

## Intended Uses / Use Cases
Helps to provide insight into data usage to help guide further investments, curation and improvements to the dataset

## Existing Approaches
Varies by program

## Additional context, comments, or links
Supports AI Executive Order 13859

**Comment by fellahst** [comment]
Thank you for your submission regarding the addition of usage/access metrics for datasets within the EPA, as per your requirement for tracking the number of hits or interactions with datasets.

In response to your need to identify popular datasets, which is crucial for business cases and data investment decisions, we suggest representing these metrics using the Data Quality Vocabulary [dqv:QualityMeasurement](https://doi-do.github.io/dcat-us/#properties-for-quality-measurement) . This approach is in line with the DCAT-US 3.0 specification and provides a standardized way to measure and report dataset usage metrics.

It's important to note that while [dqv:QualityMeasurement](https://doi-do.github.io/dcat-us/#properties-for-quality-measurement)  allows for the representation of these metrics, the actual tracking and population of this data should be managed by the catalog provider, not necessarily by the producer of the data. This ensures consistency and accuracy in reporting across different datasets and programs.

For more detailed information on implementing dqv:QualityMeasurement in your context, please refer to the relevant sections of the DCAT-US 3.0 specification [dqv:QualityMeasurement](https://doi-do.github.io/dcat-us/#properties-for-quality-measurement) which can be assigned to [dcat:Dataset](https://doi-do.github.io/dcat-us/#dataset-hasQualityMeasurement),[dcat:DataService](https://doi-do.github.io/dcat-us/#data-service-hasQualityMeasurement) . This will guide you in structuring these metrics in a way that aligns with the DCAT standard and supports the objectives outlined in AI Executive Order 13859.

We believe this approach will effectively address your needs for insights into data usage, aiding in decision-making for data curation and investment.

**Comment by mrratcliffe** [comment]
+1; Agree that tracking and population of the data should be managed by the catalog provider.
