### ISSUE TITLE
Update DCAT describedBy

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#42]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *describedBy (DCAT-US)*
Priority: *Medium*
Element Description / Requirement / Recommendation
DCAT-US specifies a link to a data catalog.  Recommend required-if-applicable based on usg:ml-training-data flag To support ML, recommend that the referenced data catalog provides robust data on data element types, i.e. categorical/continuous variables, missing values, et cetera

## Problem Statement
Need insight into datasets and datatypes for analysis, whether categorical values, continuous values, whether the column or records have missing values or other things that need to be loaded and interpreted properly for analysis

## Target Audience / Stakeholders
Data scientists

## Intended Uses / Use Cases
Help facilitate understanding of the dataset and how it should be treated for analysis

## Additional context, comments, or links
Supports AI Executive Order 13859

**Comment by fellahst** [comment]
`dcat-us:describedBy` has been updated to accept a dcat-Distribution to well-known or future data dictionary standard. See rationale and discussion in #138
