### ISSUE TITLE
FITARA: Investment ID

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#43]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *primaryITInvestmentUII*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
Make required - Data acquisition and development needs to be tracked as an IT Asset

## Problem Statement
FITARA requires data acquisition and development to be tracked as an IT asset

## Target Audience / Stakeholders
Programs, auditors, OMB

## Intended Uses / Use Cases
Tracking expenditures related to data assets

## Additional context, comments, or links
FITARA Requirement; Managing Data as a Strategic Asset

**Comment by fellahst** [comment]
See #5 . The property has been deprecated in DCAT-US 3.0
