### ISSUE TITLE
Enhancement to DCAT 'references'

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#44]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *references*
Priority: *Medium*
Element Description / Requirement / Recommendation
Currently is just a comma-separated list of URLs, example:
`{""references"":[""http://www.agency.gov/legumes/legumes_data_documentation.html"",""http://www.agency.gov/fruits/fruit_data_documentation.html""]}`
It would be good to be able to break these out and highlight them, for example a link to a tutorial on how to use the data.  A good example of this is found in the AWS Registry of Open Data.
```
{
  ""references"": [
    {
      ""dataset_reference"": {
        ""Title"": ""Dataset Reference"",
        ""URL"": ""https://www.epa.gov/dmapdata/datasetxxx/dataset_reference.html"",
        ""AuthorName"": ""Joe Dataowner""
      }
    },
    {
      ""access_reference"": {
        ""Title"": ""Access Guide for Geomorphology Data"",
        ""URL"": ""https://www.epa.gov/dmapdata/datasetxxx/access_reference.html""
      }
    },
    {
      ""peer_review"": {
        ""URL"": ""https://www.epa.gov/dmapdata/datasetxxx/peer_review.html""
      }
    },
    {
      ""ml_reference"": ""https://www.epa.gov/dmapdata/datasetxxx/ml_reference.html""
    },
    {
      ""Tutorials"": {
        ""Title"": ""Tutorial for Use of Geomorphology Data"",
        ""URL"": ""https://www.epa.gov/dmapdata/datasetxxx/dataset_tutorial.html"",
        ""AuthorName"": ""Joe Dataowner"",
        ""AuthorURL"": ""https://www.epa.gov/ord/geomorpholab.html"",
        ""Services"": [
          ""s3"",
          ""ec2"",
          ""sagemaker""
        ]
      }
    }
  ]
}

```
## Problem Statement
Many different types of references might be associated with a data asset, for example one might be a document describing how the dataset was developed, another might be a usage guide or tutorial, and so on.  It would be good to be able to highlight the different types of documents and artifacts associated with a dataset to aid in access, understanding and use of the data

## Target Audience / Stakeholders
Public, data scientists

## Intended Uses / Use Cases
Improve access, understanding and use of the data

## Existing Approaches
The AWS Registry of Open Data has some examples of how this can be done, underlying it is a yaml schema

## Additional context, comments, or links
Supports AI Executive Order 13859, provides additional clarity and improvements in presentation

**Comment by fellahst** [comment]
This requirement has been addressed. See [Related Resources](https://doi-do.github.io/dcat-us/#related-resources) usage guideline section.
