### ISSUE TITLE
Associated Journal Article

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#45]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - associated journal article title*
Priority: *Medium*
Element Description / Requirement / Recommendation
* differentiate from dataset title

## Problem Statement
Crosswalk data elements from ORD Scientific Data Management Plan

## Target Audience / Stakeholders
Researchers, Data Scientists

## Intended Uses / Use Cases
Capture and convey information from Scientific Data Management Plans

## Additional context, comments, or links
EPA ORD Scientific Data Management Plans

**Comment by fellahst** [comment]
This requirement has been addressed. See [Related Resources](https://doi-do.github.io/dcat-us/#related-resources) usage guideline section.
