### ISSUE TITLE
Description of Scientific Project associated with the dataset

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#46]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - associated ORD project description*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
* differentiate from other description fields

## Problem Statement
Crosswalk data elements from ORD Scientific Data Management Plan

## Target Audience / Stakeholders
Researchers, Data Scientists

## Intended Uses / Use Cases
Capture and convey information from Scientific Data Management Plans

## Additional context, comments, or links
EPA ORD Scientific Data Management Plans

**Comment by mrratcliffe** [comment]
+1
