### ISSUE TITLE
Character Encoding

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#47]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - attachments character encoding*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
maybe default to UTF-8

## Problem Statement
Describe character encoding used in dataset

## Additional context, comments, or links
Bagit spec https://tools.ietf.org/html/rfc8493

**Comment by fellahst** [comment]
Requirement has been addressed in https://doi-do.github.io/dcat-us/#character_encoding

See also https://github.com/DOI-DO/dcat-us/issues/170#issuecomment-1865269400
