### ISSUE TITLE
Author Approval Certification

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#48]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - author approval*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
Certification that all authors have approved release (maybe with a date field)

## Problem Statement
Verify and validate that requisite approvals for release have been obtained.

## Additional context, comments, or links
EPA ORD Scientific Data Management Plans

**Comment by fellahst** [comment]
Recommanded Solution: Use DCAT3 [prov:qualifiedAttribution](https://doi-do.github.io/dcat-us/#catalog-qualifiedAttribution) with role specified in controlled vocabulary (e.g., "releaseApprover")

**Comment by mrratcliffe** [comment]
+1
