### ISSUE TITLE
Archive Profile Identifier

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#49]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - bagit profile identifier*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
BagIt-Profile-Identifier
Definition: An HTTP URI that identifies the BagIt Profile. The Archive Center will provide this identifier to the donor organization.
Data type: Locally controlled, temporary URL: “https://gist.githubusercontent.com/HaSistrunk/65d59e558c436b9d934d98fd8fb0f575/raw/097f2c96c27b1e67a173c6c390458a981ffdbd83/organizational-bag-profile.json”
Obligation: Required
Repeatability: No
Examples:
“https://standards.rockarch.org/bagit/organizational-bag-profile.json”
“http://rockarch.org/bagitprofiles/bag-profile.json”

## Problem Statement
Potential addition - some orgs use BagIt for packaging and archival of data

## Target Audience / Stakeholders
Data Owners, Records Management, Public 

## Intended Uses / Use Cases
Incorporate BagIt metadata

## Existing Approaches
BagIt metadata

## Additional context, comments, or links
Bagit spec https://tools.ietf.org/html/rfc8493

**Comment by fellahst** [comment]
See https://github.com/DOI-DO/dcat-us/issues/170#issuecomment-1865269400
