### ISSUE TITLE
Delete Investment Identifier field

### ISSUE THREAD

**Issue by hkdctol** [DOI-DO/dcat-us#5]
- Hyon Kim - Data.gov - GSA
- There is a current optional field for investment ID https://resources.data.gov/resources/dcat-us/#primaryITInvestmentUII
- Usage notes say "Use to link a given dataset with its related IT Unique Investment Identifier, which can often be found in Exhibit 53 documents."

Unclear that this has ever been used. If it's not a necessary field, delete in an update.

**Comment by TDabolt** [comment]
Concur with Hyon let's depricate this field.

**Comment by fellahst** [comment]
The proposed property dcat-us:investment and dcat-us:Investment have been removed from the specification as the property [primaryITInvestmentUI](https://resources.data.gov/resources/dcat-us/#primaryITInvestmentUII)  in DCAT US 1.1 has not been used consistently.This property is deprecated in the new specification.
