### ISSUE TITLE
Checksum Algorithm

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#51]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - checksum algorithm*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
checksum algorithm used - sha256 or 512

## Problem Statement
Potential addition - some orgs use BagIt for packaging and archival of data; also other tools may generate checksums which can be used to verify data integrity

## Target Audience / Stakeholders
Data Owners, Records Management, Public 

## Intended Uses / Use Cases
Incorporate checksums where they exist

## Additional context, comments, or links
Bagit spec https://tools.ietf.org/html/rfc8493

**Comment by fellahst** [comment]
Requirement has been addressed in https://doi-do.github.io/dcat-us/#distribution-checksum

See also https://github.com/DOI-DO/dcat-us/issues/170#issuecomment-1865269400
