### ISSUE TITLE
Dataset Collaborators

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#52]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - collaborators*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
Good approach would be to have contact / fn as a multiple repeating field with contact/role

## Problem Statement
Better handling of point-of-contact information with roles

## Target Audience / Stakeholders
Public

## Intended Uses / Use Cases
Better approach for capturing and representing individuals involved in the data

## Existing Approaches
EPA Office of Research and Development Scientific Data Management Plan

## Additional context, comments, or links
EPA ORD Scientific Data Management Plans

**Comment by fellahst** [comment]
David,

Regarding your requirement to enhance point-of-contact information with roles, we recommend utilizing VCard properties as detailed in the DCAT-US 3.0 specification. For implementing contact information, kindly refer to the ["vcard:Contact"](https://doi-do.github.io/dcat-us/#properties-for-contact) section. Additionally, to add multiple contact points to your resources, see the guidelines under [Dataset:contactPoint](https://doi-do.github.io/dcat-us/#dataset-contact-point). This method effectively supports the representation of multiple contacts in EPA datasets.

**Comment by ShaferAC** [comment]
+1

**Comment by mrratcliffe** [comment]
+1
