### ISSUE TITLE
Data Collection Description

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#53]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - data collection*
Priority: *Medium*
Element Description / Requirement / Recommendation
Description of how data is collected

## Problem Statement
Explain how the data was collected.  Either provide as a narrative field or link to a reference document

## Target Audience / Stakeholders
Public, academia

## Intended Uses / Use Cases
Help explain how the data was collected or developed

## Existing Approaches
EPA Office of Research and Development Scientific Data Management Plan

## Additional context, comments, or links
EPA ORD Scientific Data Management Plans

**Comment by fellahst** [comment]
The DCAT-US 3.0 provides the property [dcterms:provenance](https://doi-do.github.io/dcat-us/#dataset-provenance) with range [dcterms:ProvenanceStatement](https://doi-do.github.io/dcat-us/#properties-for-provenance-statement). [rdfs:label](https://doi-do.github.io/dcat-us/#provenance-statement-label) on ProvenanceStatement should be used to capture narrative.
