### ISSUE TITLE
Data Retention Policy

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#54]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - data retention*
Priority: *Medium*
Element Description / Requirement / Recommendation
Describe the approach to data retention commensurate with journal article retention policies and record management? Include the expected period of time during which the data will be made accessible and, if different, the period of time during which the data will be retained by EPA.
* should be associated with a specific EPA records schedule (picklist) that are associated with business rules for archival etc.

## Problem Statement
Indicate or link to records schedule associated with the dataset

## Target Audience / Stakeholders
Data Owners, Records Management, Public 

## Intended Uses / Use Cases
Provides insights into business rules for records retention and disposition for the dataset

## Existing Approaches
EPA Office of Research and Development Scientific Data Management Plan

## Additional context, comments, or links
EPA ORD Scientific Data Management Plans

**Comment by fellahst** [comment]
The requirement for adding a data retention element to the DCAT-US specification, aligned with EPA policies, necessitates a clear use case definition and assessment of its impact on stakeholders for effective implementation.
