### ISSUE TITLE
Data Reuse - Intendent Purpose Guidance

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#55]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - data reuse*
Priority: *High*
Element Description / Requirement / Recommendation
Some types of research data, such as trend data, historical data, and national survey data, can be reused by other researchers to conduct different analyses. Are your research data unique? What is the potential for reuse? Who is likely to use your research data in the future? Include information on known users and potential users beyond your team. 

## Problem Statement
Helps to guide analysts with regard to suitability to intended purpose

## Target Audience / Stakeholders
Data scientists, public, researchers

## Intended Uses / Use Cases
Helps users understand whether the dataset has broad applicability and reuse potential or if it is very narrow and unique in scope.

## Existing Approaches
EPA Office of Research and Development Scientific Data Management Plan

## Additional context, comments, or links
EPA ORD Scientific Data Management Plans

**Comment by fellahst** [comment]
Understood. In light of the aim to maintain simplicity and generality in the DCAT-US specification, leveraging the existing properties of [dcterms:description](https://doi-do.github.io/dcat-us/#dataset-description) and [dcat-us:purpose](https://doi-do.github.io/dcat-us/#dataset-purpose) is a prudent approach to address the requirements of determining a dataset's potential for reuse and its applicability.

**Comment by TDabolt** [comment]
In addition to @fellahst recommendation - look at the proposed approach in the profile for how we address FCSM statistical recommendations
