### ISSUE TITLE
Description of how data is used

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#56]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - data use*
Priority: *Medium*
Element Description / Requirement / Recommendation
Description of how data is used in research

## Problem Statement
Helps to explain appropriate applications for the data

## Target Audience / Stakeholders
Data scientists, public, researchers

## Intended Uses / Use Cases
Explain appropriate and useful use cases for the data

## Existing Approaches
EPA Office of Research and Development Scientific Data Management Plan

## Additional context, comments, or links
EPA ORD Scientific Data Management Plans

**Comment by fellahst** [comment]
Understood. In light of the aim to maintain simplicity and generality in the DCAT-US specification, leveraging the existing properties of [dcterms:description](https://doi-do.github.io/dcat-us/#dataset-description) and [dcat-us:purpose](https://doi-do.github.io/dcat-us/#dataset-purpose) is a prudent approach to address the requirements of determining a dataset's potential for reuse and its applicability.
