### ISSUE TITLE
File Checksum Value

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#57]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - file checksum*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
checksum for files (automatically generated)

## Problem Statement
Potential addition - some orgs use BagIt for packaging and archival of data; also other tools may generate checksums which can be used to verify data integrity

## Target Audience / Stakeholders
Data Owners, Records Management, Public 

## Intended Uses / Use Cases
Incorporate checksums where they exist

## Additional context, comments, or links
Bagit spec https://tools.ietf.org/html/rfc8493

**Comment by fellahst** [comment]
For the requirement to include file checksums in the DCAT-US specification, it is recommended to use the [spdx:Checksum](https://doi-do.github.io/dcat-us/#properties-for-checksum) property from the Software Package Data Exchange (SPDX) vocabulary. This property can be implemented alongside the [dcat:Distribution](https://doi-do.github.io/dcat-us/#properties-for-distribution) class. The [spdx:Checksum ](https://doi-do.github.io/dcat-us/#properties-for-checksum) includes two sub-properties: [spdx:algorithm](https://doi-do.github.io/dcat-us/#checksum-algorithm), specifying the algorithm used for the checksum (e.g., SHA-256), and [spdx:checksumValue](https://doi-do.github.io/dcat-us/#checksum-checksumValue), providing the actual checksum value. By integrating spdx:Checksum with dcat:Distribution, you can effectively capture and communicate the data integrity and authenticity details of the distributed files in the catalog.
