### ISSUE TITLE
Master ID

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#59]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - master ID*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
Bag-Group-Identifier
Definition: A unique identifier for the entire set of bags to which this bag belongs.
Purpose: Provide an identifier to logically group multi-bag transfers.
Data type: String
Obligation: Optional
Repeatability: No
Examples:
“xOmy5”
“AnnualReports”
“Group1”

## Problem Statement
Potential addition - some orgs use BagIt for packaging and archival of data

## Target Audience / Stakeholders
Data Owners, Records Management, Public 

## Intended Uses / Use Cases
Incorporate BagIt metadata

## Existing Approaches
BagIt metadata

## Additional context, comments, or links
Bagit spec https://tools.ietf.org/html/rfc8493

**Comment by fellahst** [comment]
Understood. In response to the requirement for a "master ID" or "Bag-Group-Identifier," the recommendation is to embed the BagIt document within the distribution package of the dataset. This approach allows for the inclusion of the Bag-Group-Identifier and other BagIt metadata directly within the dataset's packaging, without necessitating a modification to the DCAT-US specification.

### Recommendation:

- Utilize the dcat:Distribution class to incorporate the BagIt document. This ensures that the Bag-Group-Identifier and other relevant metadata are part of the dataset's distribution package.
- This method maintains the integrity and organization of the dataset and its associated metadata, aligning with best practices for data management and archival, especially for internal agency applications.

Embedding the BagIt document within the dcat:Distribution package effectively addresses the need for a master ID while keeping the DCAT-US specification streamlined and focused
