### ISSUE TITLE
Don't require one data.json file

### ISSUE THREAD

**Issue by hkdctol** [DOI-DO/dcat-us#6]
Hyon Kim
Data.gov
GSA

## Requirement(s)

This is more of a guidance issue than a strict schema issue.

## Problem Statement

Original open data guidance required agencies to have one data.json
While most agencies have followed this, there are some agencies that required multiple data.json for various reasons
Large data.json has been problematic for Data.gov harvester (NASA, NOAA, etc.)

## Target Audience / Stakeholders

This has been an issue for both agencies and the Data.gov catalog. Instead of as a complete catalog, allow piecemeal if needed.

**Comment by fellahst** [comment]
RDF's flexible and distributed nature makes it suitable for breaking down catalogs into multiple files and easy to aggregate. Data is represented as subject-predicate-object triples, with each triple storable in separate files, enabling modularization and independent management of catalog portions. Unique identifiers (URIs) link related triples across files, facilitating aggregation, integration, and navigation of metadata. RDF's decentralized structure supports scalability, efficient querying, and data merging, making it well-suited for handling large catalogs spread across multiple files.

**Comment by hkdctol** [comment]
The comment meaning that recommended schema will make it easy to spread across multiple files, if that's what makes it easier for the agency and Data.gov as the harvester/aggregator?

**Comment by TDabolt** [comment]
Recommend flagging this for implementation discussion.  The requirement isn't a requirement of the profile itself it's referencing the interchange of record sets (could be partial or entire) between catalogs / inventories.
