### ISSUE TITLE
Multipart Dataset - Part Count

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#60]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - part count*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
Bag-Count
Definition: Two numbers separated by ‘of’, in particular, ‘N of T’, where T is the total number of bags in a group of bags and N is the ordinal number within the group; if T is not known, specify it as ‘?’ (question mark).
Purpose: Allows donors to split large bags into multiple parts that can be reassembled later.
Data type: String
Obligation: Optional
Repeatability: No
Examples:
“1 of 2”
“4 of 4”
“3 of ?”

## Problem Statement
Potential addition - some orgs use BagIt for packaging and archival of data

## Target Audience / Stakeholders
Data Owners, Records Management, Public 

## Intended Uses / Use Cases
Incorporate BagIt metadata

## Existing Approaches
BagIt metadata

## Additional context, comments, or links
Bagit spec https://tools.ietf.org/html/rfc8493

**Comment by fellahst** [comment]
See reply in #170.
