### ISSUE TITLE
Payload Stream Count

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#61]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - stream count*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
Payload-Oxum
Definition: The “octetstream sum” of the payload, namely, a two-part number of the form OctetCount.StreamCount, where OctetCount is the total number of octets (8-bit bytes) across all payload file content and StreamCount is the total number of payload files. Payload-Oxum should be included in bag-info.txt.
Purpose: Payload-Oxum is intended for machine consumption.
Data type: OctetCount.StreamCount
Obligation: Required
Repeatability: No
Examples:
“279164409832.1198”

## Problem Statement
Potential addition - some orgs use BagIt for packaging and archival of data

## Target Audience / Stakeholders
Data Owners, Records Management, Public 

## Intended Uses / Use Cases
Incorporate BagIt metadata

## Existing Approaches
BagIt metadata

## Additional context, comments, or links
Bagit spec https://tools.ietf.org/html/rfc8493

**Comment by fellahst** [comment]
This issue is addressed with the introduction of the [dcat:byteSize](https://doi-do.github.io/dcat-us/#distribution-byte-size) proposed element. The concept of "Payload-Oxum," as defined in the ticket, aligns closely with the purpose of dcat:byteSize.

**Comment by TDabolt** [comment]
Concur with @fellahst 
Recommend closing the issue.
