### ISSUE TITLE
Contact Info - Supervisor

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#62]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd - supervisor*
Priority: *Medium*
Element Description / Requirement / Recommendation
Good approach would be to have contact / fn as a multiple repeating field with contact/role

## Problem Statement
Better handling of point-of-contact information with roles

## Target Audience / Stakeholders
Public

## Intended Uses / Use Cases
Better approach for capturing and representing individuals involved in the data

## Existing Approaches
EPA Office of Research and Development Scientific Data Management Plan

## Additional context, comments, or links
EPA ORD Scientific Data Management Plans

**Comment by fellahst** [comment]
Duplicated with #52
