### ISSUE TITLE
CUI Protocols

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#63]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *tbd (access) - CUI protection*
Priority: *Low - primarily for internal agency applications*
Element Description / Requirement / Recommendation
Description of how CUI will be protected

## Problem Statement
Should document handling protocols for data containing CUI, whether entire dataset is to be redacted, or specific fields, whether obfuscation/fuzzing/masking or withholding of specific columns/rows/data elements must be cone and business rules for data protection

## Target Audience / Stakeholders
Data owners, auditors, data analysts

## Intended Uses / Use Cases
Improve understanding / automation / business rules for handling of data by downstream systems and data users

## Additional context, comments, or links
EPA ORD Scientific Data Management Plans

**Comment by fellahst** [comment]
Requirement is addressed by introducing the class [dcat-us:CuiRestriction](http://127.0.0.1:5501/docs/index.html#properties-for-cui_restriction)

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.
