### ISSUE TITLE
Machine Learning:  Training Data

### ISSUE THREAD

**Issue by DruidSmith** [DOI-DO/dcat-us#64]
**Creator Name:  David G Smith - smith.davidg@epa.gov**
**Creator Affiliation:  US Environmental Protection Agency**

## Requirement(s)
Proposed Element: *usg:ml-training-data (DCAT-US)*
Priority: *Medium*
Element Description / Requirement / Recommendation
ML Repository:  Tag for identifying/filtering/exposing machine learning training data.  Recommend required-if-applicable status

## Problem Statement
Identify datasets used in ML as part of AI/ML inventory

## Target Audience / Stakeholders
Public, data scientists

## Intended Uses / Use Cases
Help understand data used in machine learning, help guide downstream users with regard to datasets already used in ML.  Should be combined with documenting datasets with respect to how ML training data was prepared, for example if the dataset contains synthetic data, if features were boosted, encoded, et cetera.

## Additional context, comments, or links
Supports AI Executive Order 13859

**Comment by fellahst** [comment]
The [prov:wasDerivedFrom](https://www.w3.org/TR/prov-o/#wasDerivedFrom) property is sufficiently generic to address the requirement of identifying datasets used in machine learning. This approach provides a broad yet effective means for tagging and tracing the origins of ML training data, aligning well with the goals of AI Executive Order 13859 and catering to the diverse needs of our target audiences, including data scientists and the general public.

**Comment by TDabolt** [comment]
Response meets the current requirement.  The potential alignment of the AI Inventory requirements with Data Inventory requirements should be flagged for OMB follow up in the implementation phase.
