### ISSUE TITLE
Include a property field that indicates the shareability status

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#66]
**Creator Name:** Helene Rice, Lisette Montalvo, Lisa Mavrogianis
**Creator Affiliation:** U.S. Department of Veterans Affairs

## Requirement(s)

Recommend including a property field that indicates the shareability status that comprises **only two indicators** for simplicity and compliance:
1.  **Not shareable/Restricted (Privacy, Privileged, or Deliberative data and information).** This should be the default to protect Veteran information; and
2. **Shareable/Not restricted.** For all others including everything published on an Open Data site

**However, per DCAT-US-3 meta data should always address:**

The following are some of the key requirements and related aspects that DCAT-US should fulfill:
1. Interoperability: DCAT-US should provide a common language for describing data catalogs that enables interoperability between different agencies and systems.
2. Usability: DCAT-US should provide clear and unambiguous definitions for all metadata elements to ensure that users can easily understand and find the data they need.
3. Extensibility: DCAT-US should allow for the inclusion of additional metadata properties beyond the core set of elements provided by the specification.
4. Accessibility: DCAT-US should include metadata to describe the accessibility of datasets, including any restrictions or access limitations.
5. Provenance: DCAT-US should include metadata to describe the provenance of datasets, including information about the source of the data, any transformations or manipulations performed, and any quality control processes.
6. Versioning: DCAT-US should provide support for versioning of datasets, enabling users to track changes and updates to datasets over time.
7. Metadata about data: DCAT-US should include information about the data itself, including the format, size, and structure of the dataset.

**_POC for questions: Thomas Elwell (VBA)_**

## Problem Statement

?

## Target Audience / Stakeholders

Concur in principle with the above and we note that audiences will include both data custodians and consumers encompassing an array of capacities (i.e., Federal agencies, academia, private industry, etc.) that are authorized to access the dataset referenced by the metadata. Thereby promoting usability and shareability of datasets and transparency.

## Intended Uses / Use Cases

Same as #4  

## Existing Approaches - *Optional*

As an optional field, concur. 

## Additional context, comments, or links - *Optional*

Original Email Submission:
[VBA Input RE DCAT-US-3-Requirements edits.docx](https://github.com/DOI-DO/dcat-us/files/11909561/VBA.Input.RE.DCAT-US-3-Requirements.edits.docx)

**Comment by sofianef** [comment]
IM Team was notified that VA would like to rescind this submission and wish to use this new requirements request instead (See #89)

**Comment by sofianef** [comment]
IM Team was notified that VA would like to rescind this submission and wish to use this new requirements request instead (See #89)

**Comment by fellahst** [comment]
Rescinded
