### ISSUE TITLE
Supply the following metadata elements: Geographic Bounding Box, Temporal Extent, Spatial Representation type, Lineage, Data Quality, Constraints

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#67]
**Creator Name:** Joshua Linard
**Creator Affiliation:** Geospatial Information Officer Joshua.linard@hq.doe.gov, Department of Energy 

## Requirement(s)

The DCAT-US profile should supply the following metadata elements: 
- Geographic Bounding Box: spatial extent of dataset using minimum and maximum coordinates for latitude and longitude  
- Temporal Extent: specifies how much time a data is valid for 
- Spatial Representation type: method used to represent geographic information in the data set 
- Lineage: specifies an application’s source data, transformations, and input/out specifications 
- Data Quality: defined based on the assumption that there is geographic truth to compare with a dataset 
- Constraints: restrictions imposed on a model to maintain data integrity  

## Problem Statement

As DCAT-US is a metadata standard used for describing datasets on the web, it is more general, providing metadata elements that are applicable to any type of dataset such as title, description, keyword, publisher etc. The standards should more closely reflect ISO 19115, ISO 19139, and FDGC standards to be more specific to geospatial metadata standards 

## Target Audience / Stakeholders

The target audience are stakeholders of the DOE geospatial community.  

## Intended Uses / Use Cases

Provide a collaborative, structured, and empowered DOE geospatial community producing, using, and sharing quality, curated geospatial data to ensure advanced, innovative solutions in support of the nation's security, energy-independence, and environmental stewardship, with a consistent reference for engaging with stakeholders across the DOE and throughout the organizational hierarchy.  

## Existing Approaches - *Optional*

ISO 19115, ISO 19139 

## Additional context, comments, or links - *Optional*

[ArcGIS](https://www.arcgis.com/index.html)
[FDGC](https://fgdc.gov/)

Original Email Submission:
[DCAT-US-3-Requirements_June_27_2023.docx](https://github.com/DOI-DO/dcat-us/files/11909600/DCAT-US-3-Requirements_June_27_2023.docx)

**Comment by fellahst** [comment]
All these requirements have been addressed in the latest version of the specification
