### ISSUE TITLE
Dataset to Journal Article Relationship

### ISSUE THREAD

**Issue by bguidry-cgi** [DOI-DO/dcat-us#68]
**Creator Name:** Maxwell Felsher felsher.max@epa.gov / Brennan Guidry guidry.brennan@epa.gov
**Creator Affiliation:** US Environmental Protection Agency

## Requirement(s)

Enable users to indicate the specific journal article/publication supported by a particular dataset. 

## Problem Statement

Currently, users are unable to indicate the specific journal article or publication that a dataset supports, beyond adding links in the "References" section (which does not provide context).

## Target Audience / Stakeholders

Analyst, Reviewer

## Intended Uses / Use Cases

 Allow users to clearly indicate the use/impact of the dataset and show connectivity with the resulting publication

## Existing Approaches - *Optional*

Users may add links in the "References" section, but this approach doesn't indicate the relationship of the linked reference.

**Comment by fellahst** [comment]
This requirement has been addressed by introducing 'dcterms:isReferencedBy' and 'foaf:Document' in the profile. See [Related Resources](https://doi-do.github.io/dcat-us/#related-resources) usage guideline section
