### ISSUE TITLE
"Modified" Field Clarification

### ISSUE THREAD

**Issue by bguidry-cgi** [DOI-DO/dcat-us#69]
**Creator Name:** Maxwell Felsher felsher.max@epa.gov / Brennan Guidry guidry.brennan@epa.gov
**Creator Affiliation:** US Environmental Protection Agency

## Requirement(s)

Clarify the definition of the required “Modified” field. 

## Problem Statement

It is unclear what this field is referring to (e.g., last substantive change to the data file, the last change of any sort to the data file, etc.). Since it is required, the data entered by users is not consistent.

## Target Audience / Stakeholders

Analyst, Reviewer

## Intended Uses / Use Cases

Facilitate more accurate and consistent data entry

## Existing Approaches - *Optional*

Because this is a required field, users complete the "Modified" field according to their own definition of what "modified" means

**Comment by fellahst** [comment]
DCAT 3 defines dct:modified on a resource as the most recent date on which the catalog entry was changed, updated or modified. The value of this property indicates a change to the actual resource, not a change to the catalog record. An absent value MAY indicate that the resource has never changed after its initial publication, or that the date of last modification is not known, or that the resource is continuously updated. 
This property MUST only be set if the distributions (the actual data) that the Dataset describes have been updated after it has been issued. In this case the property MUST contain the date of the last update. That way a person or institution using the data for an analysis or application will know when to update the report or application on their side.

**Comment by TDabolt** [comment]
@fellahst insert link in response for dct:modified .  We should review documentation to make sure it's clear and addresses the concern.
