### ISSUE TITLE
Unique ID - should it require a URI?

### ISSUE THREAD

**Issue by hkdctol** [DOI-DO/dcat-us#7]
Hyon Kim
Data.gov
GSA

## Requirement(s)

Current DCAT US 1.1 requires each dataset to have a unique ID, the ID is to be unique across the agency’s catalog and remain fixed
The notes for this field state It is highly recommended that a [URI (preferably an HTTP URL)](http://tools.ietf.org/html/rfc3986#section-1.1.3) be used to provide a globally unique identifier.

## Target Audience / Stakeholders

Stakeholders are agencies and users of federal data

## Additional context, comments, or links - *Optional*

Question for the metadata schema update -- should the schema REQUIRE a URI? This would have many benefits, but also have resource implications.

**Comment by hkdctol** [comment]
Cross referencing an issue from Project Open Data repository at https://github.com/project-open-data/project-open-data.github.io/issues/627

**Comment by hkdctol** [comment]
Also referencing https://github.com/project-open-data/project-open-data.github.io/issues/614

**Comment by fellahst** [comment]
Kim,

Thank you for your inquiry about the unique identifier requirements in the DCAT-US specification. You are correct in noting that DCAT-US mandates that each resource, be it a dataset, data service, data series, or catalog, must be identified by a URI. This requirement is enforced through the SHACL (Shapes Constraint Language) profile, ensuring strict adherence to the standard.

The use of URIs as unique identifiers for each resource aligns with the broader principles of data management and interoperability. By enforcing this through the SHACL profile, DCAT-US 3.0 ensures that resources are not only uniquely identifiable but also easily accessible and linkable across different systems and platforms.

This approach underlines the commitment to creating a standardized, interoperable, and FAIR-compliant data ecosystem, enhancing the usability and effectiveness of federal data resources.

Please refer the usage guideline [Deferenceable Identifiers](https://doi-do.github.io/dcat-us/#deferenceable-identifiers ) in the specification for more details. 
If you have any further questions or require additional guidance on implementing this aspect of the DCAT-US 3.0 specification, please feel free to reach out.

**Comment by ShaferAC** [comment]
+1

**Comment by mrratcliffe** [comment]
+1
