### ISSUE TITLE
Multiple Files Associated w/ a Dataset

### ISSUE THREAD

**Issue by bguidry-cgi** [DOI-DO/dcat-us#70]
**Creator Name:** Maxwell Felsher felsher.max@epa.gov / Brennan Guidry guidry.brennan@epa.gov
**Creator Affiliation:** US Environmental Protection Agency

## Requirement(s)

Provide clarity on when it is appropriate to list multiple data files in a dataset as multiple entries in the "Distribution" section.

## Problem Statement

Examples provided in the schema seem to indicate that listing multiple entries in the "Distribution" section is used for different formats for the same data, and it is unclear what is expected for multiple data files in a single dataset.

## Target Audience / Stakeholders

Data Analysts

## Intended Uses / Use Cases

Clarify use and intent of the "Distribution" section for listing multiple files attached to a Dataset.

## Existing Approaches - *Optional*

We list multiple data files in a single dataset as multiple entries in the "Distribution" section

**Comment by fellahst** [comment]
Updated [Distribution metadata guideline](https://doi-do.github.io/dcat-us/#distribution-guideline) addressing this issue.
