### ISSUE TITLE
Metadata links to the "original" (complete/authoritative/operational) metadata for a data asset

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#73]
**Creator Name:** John Davidson 
**Creator Affiliation:** Contractor, Department of the Interior/ CDO

## Requirement(s)

Metadata must support the ability to explicitly reference or cite a downloadable instance of the "original" or more complete, authoritative, or supplemental metadata document for a Dataset. The reference/citation must also specify the schema standard (e.g., CSDGM, ISO 19115) and mime type/format (e.g., XML) of the cited "original" metadata document.

## Problem Statement

1. The DCAT vocabulary does not support all the metadata detail that legacy standards such as FGDC CSDGM or ISO 19115-1/2/3 standards do.
2. Operationally, metadata for datasets have been captured and maintained for many years using, for example, FGDC CSDGM or ISO 19115-1/2/3 schema. These metadata continue to be the primary metadata record maintained along with referenced dataset asset.
 
## Target Audience / Stakeholders

*User 1.*  Producers of data and metadata
*User 2.*  Developers of software applications for creating/updating and searching/accessing metadata
*User 3.*  Data consumers who need to see, for example, fully documented lineage and provenance or the methodology for ensuring quality of the dataset in order to determine its fitness for use.

## Intended Uses / Use Cases

*UC-01.* Once discovered, access the full metadata record for the dataset in order to determine it's suitability for use.

## Existing Approaches - *Optional*

The "DOI Profile of DCAT-US 1.1" specifies that reference to "original" metadata is on `$.dataset. distribution` where:
*  `$.dataset. distribution.title` must be literally "Original Metadata”
* `$.dataset. distribution.downloadURL`  must be specified
* `$.dataset. distribution.mediaType` must be set (e.g., “text/xml”)
* `$.dataset. distribution.conformsTo` must be specified (e.g., for CSDGM, “http://www.fgdc.gov/schemas/metadata”)

## Additional context, comments, or links - *Optional*

A requirement of the DOI's  "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by fellahst** [comment]
The DCAT-US 3.0 profile introduces a new [dcat-us:metadataDistribution](https://doi-do.github.io/dcat-us/#dataset-metadataDistribution) property  on `dcat:Dataset` with range  `dcat:Distribution` class with properties mandatory properties:
- dcat:downloadURL
- dcterms:title
- dcat: mediaType - the encoding of the source metadata (e.g., XML, JSON, other)
- dcterms: conformsTo - reference to schema specification/ standard for the source metadata
