### ISSUE TITLE
Metadata supports human-readable ‘liability’ statement/ disclaimer for the data.

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#74]
**Creator Name:** John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

Metadata supports human-readable ‘liability’ statement/ disclaimer for the data (i.e., a statement of liability assumed by the distributor of the data). 

## Existing Approaches - *Optional*

* The DOI's "Application Profile of DCAT-US 1.1" metadata specifies mandatory property `$.dataset.liability` (multiplicity:1, range: string)
* See FGDC CSDGM "distribution liability" (`distliab`)

## Additional context, comments, or links - *Optional*

A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by fellahst** [comment]
Response to the Requirement for a Human-Readable 'Liability' Statement in Metadata:

In response to the requirement for including a human-readable 'liability' statement in the metadata, we have introduced a new property and class in the DCAT-US profile:

- **New Property: [dcat-us:liabilityStatement](https://doi-do.github.io/dcat-us/#dataset-liability_statement)**
- **Associated Class:[dcat-us:LiabilityStatement](https://doi-do.github.io/dcat-us/#properties-for-liability_statement)**

This enhancement ensures that liability information associated with datasets is clearly articulated and accessible within the metadata, providing legal clarity and transparency for data distributors and users alike.

**Comment by TDabolt** [comment]
Flag for discussion.  The proposed solution meets the requirement however is there a legal basis for needing a liability statement?

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.
