### ISSUE TITLE
Metadata must indicate the lifecycle state of dataset  

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#75]
**Creator Name:**  John Davidson
**Creator Affiliation:**  Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)
Metadata must indicate the lifecycle state of dataset e.g., planned, approved, published, in-maintenance, and specifically whether it is decommissioned/ archived/ deleted.

## Problem Statement

* Data/metadata producers need to indicate the lifecycle state of a dataset
* Data consumers need to know the lifecycle state of a dataset 

## Target Audience / Stakeholders

*User 1*. Producer of the data/metadata
*User 2*. Data Steward for the data/metadata
*User 3*. Consumer of the data/metadata
 
## Intended Uses / Use Cases

1. UC01. Data consumer wants to determine availability of the dataset, specifically whether it has been archived, decommissioned, or otherwise superseded.
2. UC02. Data producer needs to indicate that the lifecycle state of a dataset has changed to "decomissioned" and is no longer valid or available online.

## Existing Approaches - *Optional*
 
* See FGDC CSDGM `$.idinfo.status.progress`  (Domain: "Complete" "In work" "Planned")
* See ISO 19115-1 "MD_ProgressCode" (completed, historicalArchive, obsolete, onGoing, planned, required, underDevelopment, final, pending, retired, superseded, tentative, valid, accepted, notAccepted, withdrawn, proposed, deprecated)

## Additional context, comments, or links - *Optional*

A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by fellahst** [comment]
The requirement to indicate the lifecycle state of a dataset is addressed using the [adms:status](https://doi-do.github.io/dcat-us/#dataset-status) property in DCAT. This property is applicable to dcat:Dataset, dcat:Distribution, and dcat:DataService. It allows data/metadata producers to specify the current state of a dataset, such as whether it's in development, published, or decommissioned. Data consumers can then use this information to understand the dataset's availability and relevance.
