### ISSUE TITLE
Datasets must be findable when a user searches on either the full, official name of the agency that produced the dataset or a common alternative name or the abbreviations

### ISSUE THREAD

**Issue by mrratcliffe** [DOI-DO/dcat-us#76]
**Creator Name: Mchael Ratcliffe 
**Creator Affiliation: Census Bureau

## Requirement(s)

Datasets must be findable when a users searches on either the full, official name of the agency that produced or a common alternative or an abbreviation.

## Problem Statement

*Mandatory statement of the current situation, including:*

Federal agencies may be referred to by official name (e.g., Bureau of the Census), a common alternative (e.g., Census Bureau), or an abbreviation (e.g., BOC). If a metadata record contains one version of the name (official or alternative) or the abbreviation and the system cannot link between official name, alternative, and abbreviation when each appears in a metadata record, then a user's search may not return all datasets produced by the agency. Metadata records may include the agency's official name, common alternative, or abbreviation, but not all possible iterations.  

Stakeholders experiencing problem: Bureau of Economic Analysis (BEA) staff reported that if one searches on "Bureau of Economic Analysis" it is not listed. BEA is.

Agency staff preparing metadata should be able to provide the official name, common alternative, and abbreviation. Alternatively, these could be autogenerated from a crosswalk and populated in the metadata entry regardless of what the publisher provides.

## Target Audience / Stakeholders

User 1.  Data providers/publishers
User 2.  Consumers of DataServices/APIs
User 3.  Metadata experts, when mapping other metadata standards to DCAT
User 4.  Web developers, when developing apps on a DCAT-oriented backend
User 5.  Data Consumers/Producers in the Statistical Domain

**Comment by fellahst** [comment]
Micheal,

To address your concern about the findability of datasets across different naming conventions for federal agencies, the DCAT-US 3.0 specification's approach to representing organizations is key. Here's a breakdown of the strategy using **org:Organization** and related properties to ensure datasets are discoverable under various agency names and abbreviations:

- Use Recognized URL Identifiers: Implement well-known URL identifiers for organizations, preferably those managed by a government registry. This ensures clear and consistent identification of organizations across catalog resources.
- Ensure Consistency with *foaf:name*: Use **foaf:name** to provide a consistent, recognizable name for the organization, maintaining a uniform identity across different platforms.
- Enhance Discoverability with **skos:prefLabel**: Utilize **skos:prefLabel** for the primary, legally recognized name of the agency. This ensures the organization is easily discoverable and identifiable in various search scenarios.
- Accommodate Variations with **skos:altLabel**: Incorporate **skos:altLabel** for alternative names, including trading names, colloquial names, or common alternatives. This enhances searchability and user-friendliness by recognizing various naming conventions.
- Provide Abbreviations with **skos:notation**: Use **skos:notation** to document any abbreviations, acronyms, or codes associated with the agency. This aids users in recognizing and associating the organization with its commonly used abbreviations.
- Represent Hierarchy with **org:subOrganizationOf**: Optionally, employ **org:subOrganizationOf** to depict hierarchical relationships within the organization, offering a structured view of its different layers and sub-entities.

The usage guideline sections [Deferenceable Identifiers](https://doi-do.github.io/dcat-us/#deferenceable-identifiers) and  [Organization](https://doi-do.github.io/dcat-us/#organization) provide more details with examples. 

By adhering to these guidelines when employing **org:Organization** in the DCAT-US 3.0 framework, federal agencies can ensure their datasets are easily findable regardless of whether users search using the official name, a common alternative, or an abbreviation. This approach aligns with the need for unambiguous identification and effective data discoverability within the federal data ecosystem.

**Comment by ShaferAC** [comment]
+1; 

Might be beneficial to include guidance for which elements to include values in for agency name coverage/findability for the users, like you did in comment above. That way folks can ensure they build this into their practice when creating their metadata.

**Comment by mrratcliffe** [comment]
+1; 
Agree with Allison's (ShaferAC) comment above.
@fellahst Thanks for the detailed response.

**Comment by TDabolt** [comment]
Approach meets the requirement.  We should flag this as part of the implementation strategy so that key parties understand the recommended solution and understand how it could be implemented and maintained.
