### ISSUE TITLE
Metadata must provide a dataset's provenance

### ISSUE THREAD

**Issue by mrratcliffe** [DOI-DO/dcat-us#78]
**Creator Name: Michael Ratcliffe
**Creator Affiliation: Census Bureau

## Requirement(s)
Metadata must provide the provenance/source(s) for the dataset. 

Provide information about the origin and/or source of the data set in order for data consumers to make a well-informed assessment of fitness for use for the intended analysis or operation. This could be the originating organization(s) and datasets used to produce the published dataset. It could the census or survey by which data were collected and used to create the published dataset. 

Example 1: Census Bureau population estimates dataset: provenance/source(s): State vital records (births, deaths), Internal Revenue Service tax returns.
Example 2: Housing characteristics: provenance/source: Bureau of the Census, American Community Survey.

## Problem Statement
If data consumers do not know the provenance/source(s) of a dataset and its contents, their ability to fully assess fitness for use and authoritativeness of the data is constrained.  

## Target Audience / Stakeholders

User 1.  Providers/publishers of datasets.
User 2.  Data Consumers/Producers 

## Intended Uses / Use Cases

Use 1. Know the source(s) of information contained in a dataset.
Use 2. Query/search the data catalog for datasets based on provenance/sources.
Use 3. Locate datasets derived from the same source.

**Comment by fellahst** [comment]
The requirement is addressed in the DCAT-US profile. See [Provenance Metadata usage guideline](https://doi-do.github.io/dcat-us/#provenance-metadata)
