### ISSUE TITLE
Include a property related to cybersecurity and privacy considerations for the data

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#79]
**Creator Name:** Victoria Pillitteri
**Creator Contact Information:** victoria.pillitteri@nist.gov
**Creator Affiliation:** NIST 

## Requirement(s)

Include a property related to cybersecurity and privacy considerations for the data.

## Problem Statement

Currently, in DCAT-US Schema v1.1, cybersecurity (“security”) and privacy are mentioned only in the accessLevel (“public”, “restricted public”, “non-public”) and rights fields (allows for string if accessLevel is “restricted public” or “non-public” on why it was categorized as such). Given the importance of cybersecurity and privacy of federal information, there is an opportunity to provide additional guidance and information about the dataset.   

For example, include additional guidance for the “rights” field to identify the information type(s) (see NIST Special Publication 800-60, Vol 2), the impact levels of information for confidentiality, integrity and availability (see NIST Federal Information Processing Standard (FIPS) 199, Standards for Security Categorization of Federal Information and Information Systems). 

Alternatively, consider adding a field for “cybersecurity impact levels” (requirements to identify confidentiality, integrity and availability impact) and “information type.” 

## Target Audience / Stakeholders

<Please complete this section> 

## Intended Uses / Use Cases

Assist information and system owners to more easily determine the security categorization of the data and the system in which the data resides.  

## Additional context, comments, or links - *Optional*

Original Email Submission:
[DCAT-US-3-Requirements-Template-NIST-cybersecurity.docx](https://github.com/DOI-DO/dcat-us/files/11923218/DCAT-US-3-Requirements-Template-NIST-cybersecurity.docx)

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.

**Comment by TDabolt** [comment]
An alternative approach is to require stewards to identify the C/I/A with high medium or low consistent with FIPS 199/200.  Requires discussion

**Comment by mrratcliffe** [comment]
+1
