### ISSUE TITLE
Describe references

### ISSUE THREAD

**Issue by katucker** [DOI-DO/dcat-us#8]
**Creator Name:** Keith Tucker
**Creator Affiliation:** Department of Education

## Requirement(s)

Add a text description to the URLs list in the references property.

## Problem Statement

The version 1.1 DCAT-US schema includes a property named "references" for listing a set of related documentation for a dataset. The implementation consists of only a list or URLs. As a result, end users do not know the nature of a reference document unless they access the document at the provided URL.

## Target Audience / Stakeholders

User 1. Provider of Dataset catalogs
User 2. Consumer of Datasets

## Intended Uses / Use Cases

- Use 1. Specify reference documents for a Dataset, and describe what the reference document contains,
- Use 2. Peruse the list of reference document descriptions and select the associated URL for a document of interest.

## Additional context, comments, or links

The model associated with a dataset has a dedicated property, so the URL provided in that property can be reliably labeled as pointing to a data dictionary. Other documentation to associate with a dataset, such as data notes, format revision descriptions, or developer guides, need to be described in order for end users to understand their context.

This requirement could be realized by an implementation such as the following:

```
"references": [
  {
    "description": "Data Notes",
    "url": "https://example.gov/dataset/datanotes.txt"
  },
  {
    "description": "Analysis Guide:,
    "url": "https://example.gov/dataset/analysis.md"
  }
]
```

**Comment by torrin47** [comment]
Examples of other types of useful references were discussed here:
Alternate metadata reference: https://github.com/project-open-data/project-open-data.github.io/issues/308
and here:
Original data source: https://github.com/project-open-data/project-open-data.github.io/issues/393
These could reasonably be included in the references array, provided there was a clear way to parse for each type of reference - so perhaps in addition to the text description suggested above (which is desperately needed) a reference_type field with a consistent domain might help?

**Comment by fellahst** [comment]
This requirement has been addressed. See [Related Resources](https://doi-do.github.io/dcat-us/#related-resources) usage guideline section.
