### ISSUE TITLE
Applicability of the Confidential Information Protection and Statistical Efficiency Act (CIPSEA) to the dataset. 

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#80]
**Creator Name:**  Nikolaos Ipiotis, HHS Chief Data Officer with support from the HHS Metadata Standards Work Group
**Creator Contact Information:** HHS Chief Data Officer, DGB@hhs.gov 
**Creator Affiliation:** Office of the Chief Information Officer/Office of the Chief Data Officer

## Requirement(s)

Add a metadata element to indicate the applicability of the Confidential Information Protection and Statistical Efficiency Act (CIPSEA) to the dataset.   

Value set: 
* Yes
* No determination
* Not applicable

## Problem Statement

Problem description:  Dataset owners need to alert potential dataset users of restrictions on the use of the dataset.  Dataset users need to be informed of the potential limitations on the use of the dataset. 

Stakeholders Experiencing the problem: 
* Dataset owners 
* Dataset users 

Stakeholder expectations:  CIPSEA applicability to datasets should be visible to users of the data inventory. 

## Target Audience / Stakeholders

* Dataset owners 
* Dataset users 

## Intended Uses / Use Cases

* Use 1. Dataset owners can communicate the applicability of CIPSEA restrictions 
* Use 2. Dataset users can be aware of CIPSEA restrictions. 

## Existing Approaches - *Optional*

N/A

## Additional context, comments, or links - *Optional*

The HHS Metadata Standard is undergoing revision and the information provided in this document may change as the revision process moves forward. 

Original Email Submission:
[DCAT-US-3-Requirements_HHS_CIPSEA.docx](https://github.com/DOI-DO/dcat-us/files/11923257/DCAT-US-3-Requirements_HHS_CIPSEA.docx)

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.
