### ISSUE TITLE
Add a metadata element to indicate the scope of the population covered by the dataset. 

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#81]
**Creator Name:** Nikolaos Ipiotis, HHS Chief Data Officer with support from the HHS Metadata Standards Work Group
**Creator Contact Information:** HHS Chief Data Officer, DGB@hhs.gov 
**Creator Affiliation:** Office of the Chief Information Officer/Office of the Chief Data Officer 

## Requirement(s)

Add a metadata element to indicate the scope of the population covered by the dataset.  

Value set: 
-  Full Population 
- Sub-Population 
- Population Sample 
- Other with text field

## Problem Statement

Problem description:  Dataset users need to understand the population coverage associated with a dataset.    

Stakeholders Experiencing the problem: 

- Dataset owners 
- Dataset users 

Stakeholder expectations:  Users of the data inventory will be made aware of the population coverage of the dataset.

## Target Audience / Stakeholders

- Dataset owners 
- Dataset users 

## Intended Uses / Use Cases

Use 1. Dataset users can be made aware of the population coverage of the dataset.   

## Existing Approaches - *Optional*

N/A

## Additional context, comments, or links - *Optional*

The HHS Metadata Standard is undergoing revision and the information provided in this document may change as the revision process moves forward. 

Original Email Submission: [DCAT-US-3-Requirements_HHS_Data Breadth.docx](https://github.com/DOI-DO/dcat-us/files/11923278/DCAT-US-3-Requirements_HHS_Data.Breadth.docx)

**Comment by fellahst** [comment]
It is not clear what population means in this ticket. Does it mean stakeholders, audience for the dataset ?
