### ISSUE TITLE
Provide a data element to allow users to indicate the types of Diversity, Equity, Inclusion, and Access (DEIA) data that are included in the dataset. 

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#82]
**Creator Name:** Nikolaos Ipiotis, HHS Chief Data Officer with support from the HHS Metadata Standards Work Group
**Creator Contact Information:** HHS Chief Data Officer, DGB@hhs.gov 
**Creator Affiliation:**  Office of the Chief Information Officer/Office of the Chief Data Officer 

## Requirement(s)

Provide a data element to allow users to indicate the types of Diversity, Equity, Inclusion, and Access (DEIA) data that are included in the dataset.   

Value set: 
- Race 
- Ethnicity 
- Race/Ethnicity 
- Sex 
- Gender identity 
- Sexual orientation 
- Age 
- First generation professionals 
- First generation college students 
- Pregnancy and pregnancy-related conditions 
- Limited English proficiency 
- Former incarceration 
- Military 
- Military spouses 
- Religious affiliation 
- Persons with disabilities 
- Persons who live in rural areas or underserved urban areas 
- Country of origin 
- Immigration status 
- Other with a linked text field 

## Problem Statement

Problem description:  Data users increasingly want to be able to identify datasets that can support analyses related to DEIA. The current DCAT specification would capture a free text tag that does not support a controlled vocabulary and would result in datasets being missed or misidentified as having DEIA data.   

Stakeholders Experiencing the problem: 

- Dataset users 
- Data-sharing leaders 

Stakeholder expectations:  Data users want ready access to complete and accurate search results to identify datasets with DEIA data.  Data-sharing leaders want to have accurate data for analysis of the availability and sharing of DEIA data.  

## Target Audience / Stakeholders

- Dataset users 
- Data-sharing leaders 

## Intended Uses / Use Cases

Use 1. Dataset users have access to complete and accurate information on datasets that include DEIA data.  Data-sharing managers can analyze the availability and sharing of datasets with DEIA data.   

## Existing Approaches - *Optional*

DCAT does not current implement a controlled vocabulary for DEIA data.  The only way to capture this is through the use of free text tag fields.   

## Additional context, comments, or links - *Optional*

The HHS Metadata Standard is undergoing revision and the information provided in this document may change as the revision process moves forward. 

Original Email Submission: 
[DCAT-US-3-Requirements_HHS_DEIA Data Elements.docx](https://github.com/DOI-DO/dcat-us/files/11923300/DCAT-US-3-Requirements_HHS_DEIA.Data.Elements.docx)

**Comment by fellahst** [comment]
Thank you for your email regarding the inclusion of a data element for Diversity, Equity, Inclusion, and Access (DEIA) in datasets within the DCAT-US specification. While the need to accurately identify and categorize DEIA-related data is acknowledged, it is essential to note that the development of domain-specific controlled vocabularies falls outside the purview of the DCAT-US specification. The primary focus of DCAT-US is to establish and maintain cross-domain controlled vocabularies. The responsibility for creating and managing specific vocabularies, such as those related to DEIA, rests with the respective communities or sectors. These groups are best positioned to understand and define their unique data categorization needs. As such, stakeholders like dataset users and data-sharing leaders in the DEIA domain are encouraged to develop a controlled vocabulary that meets their specific needs while ensuring compatibility and integration with the broader DCAT framework.

**Comment by mrratcliffe** [comment]
+1
