### ISSUE TITLE
Expand Fields for Points for Contact

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#84]
**Creator Name:** Nikolaos Ipiotis, HHS Chief Data Officer with support from the HHS Metadata Standards Work Group
**Creator Contact Information:** HHS Chief Data Officer, DGB@hhs.gov 
**Creator Affiliation:** Office of the Chief Information Officer/Office of the Chief Data Officer

## Requirement(s)

Update the current fields associated with data owner, contact person, and affiliated to distinguish the following fields: 
- First name 
- Last name 
- Email 
- Phone number 

## Problem Statement

Problem description:  Current DCAT data elements do not allow for separate fields for first and last name and do not have consistent fields for each point of contact.   Distinguishing first and last name fields is consistent with current data management practices.

Stakeholders Experiencing the problem: 
- Dataset owners 
- Dataset users 
- Data inventory managers 

Stakeholder expectations:  Data users and data inventory managers. want ready access to current contact information for datasets.   

## Target Audience / Stakeholders

- Dataset owners 
- Dataset users 
- Data inventory managers 

## Intended Uses / Use Cases

Use 1. Dataset users and data inventory managers will have access to correct and usable information for dataset points of contact.  receive targeted and appropriate responses to data inventory queries. 

## Existing Approaches - *Optional*

The current DCAT specification does not provide distinct fields for first and last name and does not support consistent information for all points of contact.

## Additional context, comments, or links - *Optional*

The HHS Metadata Standard is undergoing revision and the information provided in this document may change as the revision process moves forward. 

Original Email Submission: 
[DCAT-US-3-Requirements_HHS_Expansion of Fields for Points of Contact.docx](https://github.com/DOI-DO/dcat-us/files/11923337/DCAT-US-3-Requirements_HHS_Expansion.of.Fields.for.Points.of.Contact.docx)

**Comment by torrin47** [comment]
This discussion about VCard properties also relates to other discussions (#94) about persistent identifiers. The VCard schema does support the [inclusion of a UID](https://www.w3.org/TR/vcard-rdf/#d4e592) such as [an ORCID](https://info.orcid.org/documentation/integration-guide/orcid-and-persistent-identifiers/) but it's buried pretty deeply in the RDF documentation, which means it would be easy to overlook and omit. Might it be worthwhile to include this in the [list of optional parameters](https://doi-do.github.io/dcat-us/#properties-for-contact) for DCAT-US 3.0 along with an example as a way of endorsing and encouraging use of persistent identifiers?

**Comment by ShaferAC** [comment]
+1; Agree with including UID for contact as an optional parameter as well.

**Comment by mrratcliffe** [comment]
+1; I also agree with including UID for contact as an optional parameter.

**Comment by fellahst** [comment]
Added field [vcard:hasUID](https://doi-do.github.io/dcat-us/#contact-has_uid) in Contact
