### ISSUE TITLE
Provide a data element to allow users to indicate the types of Social Determinants of Health (SDOH) data that are included in the dataset.

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#85]
**Creator Name:** Nikolaos Ipiotis, HHS Chief Data Officer with support from the HHS Metadata Standards Work Group
**Creator Contact Information:** HHS Chief Data Officer, DGB@hhs.gov 
**Creator Affiliation:**  Office of the Chief Information Officer/Office of the Chief Data Officer 

## Requirement(s)

Provide a data element to allow users to indicate the types of Social Determinants of Health (SDOH) data that are included in the dataset.   

Value set: 
- Financial insecurity 
- Material hardship 
- Employment status 
- Educational attainment 
- Stress 
- Depression 
- Physical activity 
- Alcohol use 
- Social connection and isolation 
- Exposure to violence 
- Intimate partner violence 
- Elder abuse 
- Food insecurity 
- Housing stability/instability 
- Homelessness 
- Inadequate housing 
- Transportation insecurity 
- Health literacy 
- Health insurance coverage status 
- Medical cost burden 
- Activities of daily living 
- Other with a linked text field 

## Problem Statement

Problem description:  Data users increasingly want to be able to identify datasets that can support analyses related to SDOH. The current DCAT specification would capture as a free text tag that does not support a controlled vocabulary and would result in datasets being missed or misidentified as having SDOH data.

Stakeholders Experiencing the problem: 

- Dataset users 
- Data-sharing leaders 

Stakeholder expectations:  Data users want ready access to complete and accurate search results to identify datasets with SDOH data.  Data-sharing leaders want to have accurate data for analysis of the availability and sharing of SDOH data.  

## Target Audience / Stakeholders

- Dataset users 
- Data sharing leaders 

## Intended Uses / Use Cases

Use 1. Dataset users have access to complete and accurate information on datasets that include SDOH data.  Data sharing managers can analyze the availability and sharing of datasets with SDOH data.   

## Existing Approaches - *Optional*

DCAT does not current implement a controlled vocabulary for SDOH data.  The only way to capture this is through the use of free text tag fields.   

## Additional context, comments, or links - *Optional*

The HHS Metadata Standard is undergoing revision and the information provided in this document may change as the revision process moves forward. 

Original Email Submission:
[DCAT-US-3-Requirements_HHS_SDOH Data Elements.docx](https://github.com/DOI-DO/dcat-us/files/11923358/DCAT-US-3-Requirements_HHS_SDOH.Data.Elements.docx)

**Comment by fellahst** [comment]
Thank you for your email and the suggestion to include a data element for indicating the types of Social Determinants of Health (SDOH) in datasets. While recognizing the importance of this, it's important to clarify that crafting domain-specific controlled vocabularies is out of the scope of the DCAT-US specification. The focus during the implementation phase is on defining cross-domain controlled vocabularies. It is the responsibility of each specific community, such as health and human services, to define their own vocabularies that cater to their unique needs and contexts. In the case of SDOH, stakeholders such as dataset users and data-sharing leaders are encouraged to develop and adopt a specific controlled vocabulary (using SKOS) that aligns with their requirements and integrates effectively with the broader DCAT framework.

**Comment by mrratcliffe** [comment]
+1
