### ISSUE TITLE
SORN Reference

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#86]
**Creator Name:** Nikolaos Ipiotis, HHS Chief Data Officer with support from the HHS Metadata Standards Work Group
**Creator Contact Information:** HHS Chief Data Officer, DGB@hhs.gov 
**Creator Affiliation:** Office of the Chief Information Officer/Office of the Chief Data Officer

## Requirement(s)

Add a metadata element to indicate if the system that generated the dataset is designated as a system of records under the Privacy Act of 1974, and provide the URL to the System of Records Notice (SORN) related to this dataset. 

## Problem Statement

Problem description:  Dataset owners need to alert potential dataset users that the system that generated the dataset is a system of record.  Dataset users need to be able to access information on the SORN associated with the dataset. 

Stakeholders Experiencing the problem: 
- Dataset owners 
- Dataset users 

Stakeholder expectations:  Users of the data inventory will be made aware that the dataset is derived from a designated system of record and be able to access the SORN associated with the dataset. 

## Target Audience / Stakeholders

- Dataset owners 
- Dataset users 

## Intended Uses / Use Cases

- Use 1. Dataset owners can communicate that the dataset is derived from a system of record.  
- Use 2. Dataset users can access the SORN associated with the dataset.   

## Existing Approaches - *Optional*

N/A 

## Additional context, comments, or links - *Optional*

The HHS Metadata Standard is undergoing revision and the information provided in this document may change as the revision process moves forward. 

Original Email Submission: 
[DCAT-US-3-Requirements_HHS_SORN.docx](https://github.com/DOI-DO/dcat-us/files/11923379/DCAT-US-3-Requirements_HHS_SORN.docx)

**Comment by fellahst** [comment]
For the sake of simplicity and avoid add too many properties in the profile, we recommend to use prov:isDerivedFrom property. See [provenance metadata](https://doi-do.github.io/dcat-us/#detailed-data-lineage) section

**Comment by mrratcliffe** [comment]
+1
