### ISSUE TITLE
Coverage and completeness indicators for data elements contained in a statistical datastet.

### ISSUE THREAD

**Issue by mrratcliffe** [DOI-DO/dcat-us#88]
Creator Name: Michael Ratcliffe 
Creator Affiliation: Census Bureau

## Requirement(s)

Metadata for a statistical dataset must provide measures indicating the coverage and completeness for data elements contained in the dataset. Consumers need to know whether a dataset offers universal coverage (e.g., all housing units in the nation) or partial coverage (e.g., number of households in sample). Metadata must also indicate how the extent of coverage and completeness was determined/measured.

- Example 1:  Decennial census dataset contains demographic data for the total US population. Data derived from responses collected from n number of households in the 50 states and DC. Coverage and completeness of the decennial census was measured through the Post Enumeration Survey which indicated x% net coverage error.
- Example 2: Dataset contains characteristics for all retail establishments in the nation. Universe of businesses in dataset includes all business contained in administrative records provided by federal agency responsible for tracking businesses. 
- Example 3: Dataset contains estimates of demographic characteristics for the total population of a county based on survey responses from a sample of n number of households. 
- Example 4: Microdata for 80,000 households in sample nationwide for survey. 

## Problem Statement

In order to adequately determine a statistical dataset's fitness for use, consumers need information about the coverage and completeness of the dataset, including the highest level of geography (nation, state, county, city). To the extent possible, consumers also need to know how the extent of coverage and completeness was determined and measured. 

## Target Audience / Stakeholders

User 1.  Producers of datasets
User 2.  Consumers of data

## Intended Uses / Use Cases

Use 1. Know extent to which a dataset covers the universe of all data elements/phenomena being measured and from which data are collected.
Use 2. Faciltate search/query for datasets of specific levels of coverage and/or completeness.
Use 3. Assess fitness for use prior to accessing dataset.

**Comment by fellahst** [comment]
### Solution Using DQV for Coverage and Completeness in Statistical Datasets:

To address this requirement from the Census Bureau regarding metadata for statistical datasets, the [Data Quality Vocabulary (DQV)](https://www.w3.org/TR/vocab-dqv/) can be effectively used to represent coverage and completeness measures. DQV provides a structured framework to articulate these aspects in metadata, enhancing the dataset's transparency and usability.

### Implementation Strategy with DQV:

#### Utilizing `dqv:QualityMeasurement` for Coverage and Completeness:

Employ `dqv:QualityMeasurement` to quantify the coverage and completeness of data elements within the dataset. For instance, indicating the percentage of the total population covered, the extent of business universe included, or the sample size of surveyed households.
This measurement can also include metadata about the methods used to determine these figures, like referencing the Post Enumeration Survey in the case of census data.

#### Documenting Coverage Details with `dqv:Metric`:

Define specific `dqv:Metric` instances that correspond to coverage and completeness measures. These metrics could represent various aspects like net coverage error, sample size, or the universe of entities included in the dataset.
Link these metrics with the respective `dqv:QualityMeasurement` instances to provide a clear and standardized representation of how coverage and completeness are quantified.

#### Describing Coverage and Completeness at Different Geographic Levels:

Metadata can detail coverage and completeness at various geographic levels (nation, state, county, city) using a combination of `dqv:QualityMeasurement` and relevant `dqv:Metric` instances.

This approach should enable users to understand the scope and granularity of the dataset, aiding in assessing its suitability for specific applications.
