### ISSUE TITLE
Align the DCAT-US-3 metadata schema with the ISO 19115, Coordinate a common vocabulary for federal/state/county/country/city datasets, and Recommend including a property field that indicates the shareability status 

### ISSUE THREAD

**Issue by sofianef** [DOI-DO/dcat-us#89]
**Creator Name:** Veteran Affairs
**Creator Contact Information:** Lisa Mavrogianis, Open Data Lead, Lisa.Mavrogianis@va.gov 
**Creator Affiliation:**  Office of Enterprise Integration, Data Governance, and Analytics 

## Requirement(s)

- Align the DCAT-US-3 metadata schema with the ISO 19115 geospatial metadata standard.  ISO 191** series of standards are endorsed by the Federal Geographic Data Committee and Federal agencies are encouraged to transition to ISO metadata as their agencies are able to do so. 
- Coordinate a common vocabulary with a definition for key terms across the federal, state, county, and city data sets. 
- Recommend including a property field that indicates the shareability status that comprises only two indicators for simplicity and compliance: 
     1. Not shareable/Restricted (Privacy, Privileged, or Deliberative data and information). This should be the default to protect Veteran information; and  
     2. Shareable/Not restricted.  For all others including everything published on an Open Data site. 

However, per DCAT-US-3 metadata should always address: 

The following are some of the key requirements and related aspects that DCAT-US should fulfill: 

1. Interoperability: DCAT-US should provide a common language for describing data catalogs that enables interoperability between different agencies and systems. 
2. Usability: DCAT-US should provide clear and unambiguous definitions for all metadata elements to ensure that users can easily understand and find the data they need. 
3. Extensibility: DCAT-US should allow for the inclusion of additional metadata properties beyond the core set of elements provided by the specification. 
4. Accessibility: DCAT-US should include metadata to describe the accessibility of datasets, including any restrictions or access limitations. 
5. Provenance: DCAT-US should include metadata to describe the provenance of datasets, including information about the source of the data, any transformations or manipulations performed, and any quality control processes. 
6. Versioning: DCAT-US should provide support for versioning of datasets, enabling users to track changes and updates to datasets over time. 
7. Metadata about data: DCAT-US should include information about the data itself, including the format, size, and structure of the dataset. 

## Problem Statement

- Prior to publication and sharing of geospatial data, applications, and services, all Veteran Health Agency users are required to format metadata using the ISSO 19115 standard. 
- Ensuring that DCAT and ISSO 19115 are aligned eliminates the need for additional metadata conversions when sharing to other open data platforms 
- There are likely many instances where Federal agencies use a similar term, but the term may or not have the same definition, so it becomes confusing to join data across the federal government or other publishing entities. 
- Using Data.Gov, the definition of the term “Veteran” across all the entities publishing data is not clear. For instance, does Veteran mean someone who served in US Public Health Service?

## Target Audience / Stakeholders

- User 1.  Providers of geospatial data, applications and services that are shared on the Geospatial Platform (GeoPlatform) or other open data platforms 
- User 2.  Consumers of the data and services 
- The target audience would be any consumer of datasets whether through download or through an API and the providers of the data sets. 
- Concur in principle with the above and we note that audiences will include both data custodians and consumers encompassing an array of capacities (i.e., Federal agencies, academia, private industry, etc.)  that are authorized to access the dataset referenced by the metadata. Thereby promoting usability and shareability of datasets and transparency. 

## Intended Uses / Use Cases

Use 1: 
- Format metadata once for distribution using multiple spatial data platforms 
- Common key terms utilized a taxonomy referenced in the metadata and available for one to read the term definition. 

Use 2: Discoverable by international users 

## Existing Approaches - *Optional*

Concur with keeping this as an optional field 

## Additional context, comments, or links - *Optional*

> These requirements request deprecates the (now rescinded) ticket of #66 

For more information, see [Geospatial Metadata — Federal Geographic Data Committee (fgdc.gov)](https://www.fgdc.gov/metadata).

The term Veteran is defined in Title 38 U.S.C.  It is understandable if a publisher reports about self-identified Veterans, but it needs to be clear if the data publisher supplied a definition for Veteran.  Veteran is being used as an example of a common term without a readily available definition, but there are likely many of these terms found throughout the US Open Data Initiative.

Original Email Submission:
[DCAT-US-3-Requirements-Consolidated Responses (VA).docx](https://github.com/DOI-DO/dcat-us/files/11923490/DCAT-US-3-Requirements-Consolidated.Responses.VA.docx)

**Comment by fellahst** [comment]
The requirements for aligning DCAT-US-3 metadata schema with the ISO 19115 geospatial metadata standard and other key aspects have been effectively addressed by introducing additional legal metadata properties, as detailed in the [Legal Metadata Usage Guideline](https://doi-do.github.io/dcat-us/#legal-metadata)

**Comment by mrratcliffe** [comment]
+1
