### ISSUE TITLE
DCAT US 3 Requires a Property That Specifies Data Roles

### ISSUE THREAD

**Issue by gwenmitchell** [DOI-DO/dcat-us#90]
**Creator Name:** Meika Ungricht
**Creator Affiliation:** Board of Governors of the Federal Reserve System – Office of the Chief Data Officer

## Requirement(s)

Include a property that indicates the various functions performed by the responsible parties (roles), including creator/originator, data sponsor/owner, data steward/custodian, metadata steward, business data steward, technical data steward, etc.   

## Problem Statement

DCAT US does not provide a property that allows the assignment of data governance roles and responsibilities to each data asset as required by our data governance policy.  Further, DCAT US does not have an approach for distinguishing a creator of a data asset from publisher(s) of the same data asset.  Our data consumers require this distinction. 

## Target Audience / Stakeholders

User 1.  Providers of Data Service Catalogs
User 2.  Internal Consumers of Data Services/APIs
User 3.  Metadata experts, when mapping other metadata standards to DCAT
User 4.  Web developers, when developing apps on a DCAT-oriented backend
User 5.  External Consumers of Data Services/APIs

## Intended Uses / Use Cases

Use 1. Know who is accountable for data assets using information that persists with the data.
Use 2. Know who has responsibility for executing the various tasks that provide for the data asset's fitness for use.
Use 3. Know the originator versus the publisher(s) a data asset. 

## Existing Approaches - *Optional*

See https://standards.iso.org/iso/19115/resources/Codelists/gml/CI_RoleCode.xml for examples of values for "role."

## Additional context, comments, or links - *Optional*

DCAT 3.0 should be the basis for core (required by all enterprise data assets), common, and unique metadata fields.  DCAT 3.0 is used widely – it is the basis of DCAT AP, which is used by European data producing agencies, as an example. It is mapped to Dublin Core, which is another major standard. Also, conforming with DCAT 3.0, the US will be able to establish a case for having DCAT-US added as an officially recognized schema derived from the main DCAT and be listed in the W3C. Currently DCAT-US is not listed there, which makes it seem less rigorous than other versions of DCAT, such as DCAT-AP, which is officially listed in the w3.

**Comment by gwenmitchell** [comment]
@fellahst I would add the label "citation" as well.  The request for "creator" vs "publisher" roles came from our Research Library for the specific purpose of citing sources of data.

**Comment by fellahst** [comment]
Meika,

Thank you for your comprehensive issue submission regarding the need for properties that indicate the various functions performed by responsible parties in the context of data governance. Your detailed analysis of the current limitations within DCAT US 1.1, especially concerning the distinction between creators, publishers, and various stewardship roles, is insightful and highlights a significant gap in our current data governance framework.

We acknowledge the importance of your requirement to include a property that identifies different roles such as creator/originator, data sponsor/owner, data steward/custodian, metadata steward, business data steward, and technical data steward. This need aligns with the objective of enhancing clarity and accountability in data asset management.

In response to your problem statement and intended use cases, we recommend the following approach:

- **Support for DCAT 3 qualifiedAttribution (prov:Attribution) as Optional**: We propose the adoption of DCAT 3's qualifiedAttribution property, based on the prov:Attribution model, as an optional property. This will allow for the assignment of data governance roles and responsibilities to each data asset, providing the required flexibility and specificity.

- **Use of Established Community Taxonomies for Roles**: To address the issue of distinguishing between the creator and the publisher of a data asset, as well as other roles, we suggest utilizing established community taxonomies. Specifically, the [ISO CI_RoleCode](https://standards.iso.org/iso/19115/resources/Codelists/gml/CI_RoleCode.xml) codelist, as found at ISO CI_RoleCode, offers a comprehensive set of values for role designation, ensuring consistency and clarity.

- **Emphasis on DCAT 3.0 Conformance**: Aligning with DCAT 3.0 as the basis for core, common, and unique metadata fields will not only streamline our standards with global practices but also enhance the credibility and rigor of DCAT-US. This alignment is crucial for DCAT-US to be recognized and listed in the W3C, similar to DCAT-AP.

You can find more information in the current specification in DCAT-US 3.0 usage guideline section [Resource Attribution](https://doi-do.github.io/dcat-us/#resource-attributions). 

We believe that these recommendations will significantly address the concerns raised in your issue submission. They will enhance the clarity, accountability, and usability of data assets, catering to the diverse needs of data service catalog providers, internal and external data service consumers, metadata experts, and web developers.

We look forward to further discussions on this proposal and are open to any additional suggestions or clarifications you might have.

**Comment by ShaferAC** [comment]
+1

**Comment by mrratcliffe** [comment]
+1
