### ISSUE TITLE
Provide explicit links or citations to data dictionary or schema documentation for dataset resources

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#91]
**Creator Name:** John Davidson
**Creator Affiliation:**  Contract, Department of the Interior/OCIO/CDO

## Requirement(s)

Support links/ citations to the data dictionary or schema documentation for the dataset and its distributions. (e.g.,  see POD  ‘describedBy’ and ‘describedByType’ fields) .

## Problem Statement

Data dictionary or schema (logical, conceptual, physical) provide details and context enabling FAIR (findable, accessible, interoperable, and reuseable) data.

## Target Audience / Stakeholders

**User1:** Data consumers/analysts

## Intended Uses / Use Cases

**Use Case 1:** As data analyst/consumer, I want to find datasets having physical or derived or categorized "measures" of a particular phenomena (e.g., water salinity, population density, etc) in order to determine its relevance for my needs.
**Use Case 2:** As a data analyst/consumer, I want to more precisely understand what a dataset represents and how it represents the phenomena of interst so that I can to determine: a) its fitness for my use,  b) how to reuse it, and/or c) how to transform the data into a form I can use.

## Existing Approaches - *Optional*

URL to the data dictionary for the dataset. Note that documentation other than/in addtion to a data dictionary can be referenced using Related Documents (references). This element must be paired with `Data Dictionary Type`  to indicate the representation (format) of the resource.

## Additional context, comments, or links - *Optional*
A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by mrratcliffe** [comment]
+1
