### ISSUE TITLE
Metadata records should have globally unique, persistent identifiers

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#94]
**Creator Name:** John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

According to FAIR principles, like with Dataset resources, metadata resources must also have an identifier that is globally unique and persistent.

## Problem Statement

Metadata is a resource and must be uniquely, unambiguously referenceable.

## Existing Approaches - *Optional*

Consider use of ISO 19115 style `metadataIdentifier` field.

**Comment by fellahst** [comment]
John,

Thank you for highlighting the importance of ensuring that metadata resources have globally unique and persistent identifiers, in accordance with FAIR principles. Your consideration of using an ISO 19115 style metadataIdentifier field is an insightful approach.

In the DCAT-US specification framework, it is imperative that each metadata resource, just like datasets, data services, and data series, is assigned a unique and persistent identifier. This practice aligns with the core FAIR principles, aiming to make metadata uniquely and unambiguously referenceable. Such standardization enhances the overall reliability and interoperability of data management systems.

For the DCAT-US framework, we recommend employing RDF URI identifiers for metadata resources. This method, analogous to utilizing JSON-LD `@id` on referenceable resources, ensures that each metadata item is distinctively identifiable across the web, thereby improving the management and accessibility of metadata.

Key aspects addressing your requirements in the DCAT-US 3.0 specification include:

- Providing usage guidance on [Deferrable Identifiers](https://doi-do.github.io/dcat-us/#deferenceable-identifiers), ensuring that each metadata resource adheres to identification standards akin to other data resources, maintaining uniformity and interoperability within the data catalog.
- Introduction of [adms:Identifier](https://doi-do.github.io/dcat-us/#properties-for-identifier) for a more structured approach to identifiers.
- Utilization of [dcterms:identifier](https://doi-do.github.io/dcat-us/#dataset-identifier) for simpler identifier formats (such as ISO 191115 identifiers)

These enhancements in the DCAT-US 3.0 specification are designed to meet your requirements effectively, ensuring adherence to the latest standards and practices in digital data management.

**Comment by ShaferAC** [comment]
+1

**Comment by mrratcliffe** [comment]
+1
