### ISSUE TITLE
Specify access and use constraints on dataset resources including CUI controls

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#95]
**Creator Name:** John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

1. Ability for metadata to distinguish “access” and “use” constraints on a dataset including support for CUI controls (categories and dissemination controls).
2. The types of access and use constraints are grounded to concepts defined/ distinguished in controlled vocabularies (e.g., [NARA CUI categories](https://www.archives.gov/cui/registry/category-list), [NARA category markings](https://www.archives.gov/cui/registry/category-marking-list) lists) and [NARA limited dissemination controls](https://www.archives.gov/cui/registry/limited-dissemination).

**NOTE**: These are distinctly different properties than the meaning and use of the POD `accessLevel` and `rights` fields and DCAT3 `accessRights` property
**NOTE**: These fields must only be used to specify _constraints/ restrictions_ on the dataset, _not that the dataset is unconstrained/ free for use and access._ The latter must be also be specified using, for example, `license` or other DCAT constructs.

## Problem Statement
DCAT3 defines `dcterms:rights` and `dct:accessRights` but their range is `string` (i.e., ambiguous, not machine-understandable). Specific types/categories of restrictions for use and access must instead be specified by terms defined in controlled vocabularies.

## Existing Approaches - *Optional*
* DCAT3 `dcterms:rights`, `dcterms:accessRights`, `dcat:license` properties and Open Digital Rights Language (ODRL)  `hasPolicy` expressions.
* ISO 19115 **MD_LegalConstraints** distinguishes between "access" and "use" constraints.
* NARA CUI controls:
   * [NARA CUI categories](https://www.archives.gov/cui/registry/category-list)
   * [NARA category markings](https://www.archives.gov/cui/registry/category-marking-list)
   * [NARA limited dissemination controls](https://www.archives.gov/cui/registry/limited-dissemination).

## Additional context, comments, or links - *Optional*
 
A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by mrratcliffe** [comment]
+1
