### ISSUE TITLE
Indicate a license under which the dataset resource is published

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#96]
**Creator Name:**  John Davidson
**Creator Affiliation:**  Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

Metadata must indicate the specific ‘license’ (a legal document) under which the dataset resource is made available. The field must be grounded to a controlled vocabulary of recognized/ authoritative licenses. This also includes “non-licenses” i.e., datasets that are in the public domain, free, and whose use and access is unrestricted.

## Problem Statement

“Public domain" has long been used to label Government-produced content, which is not subject to copyright and is freely available for use with no requirements for attribution and no limitations on reuse. Technically “Public Domain” is not a license, but an indication of the absence of any license and its associated requirements or limitations. Public data that are produced solely by the government, and contain no contributed data from non-federal collaborators, must be given either a Public Domain or CCO 1.0 Universal license. The Government legally cannot constrain or place conditions upon the use of solely government-produced data using any other license. 

Per Title 17 of U.S. Copyright Law:
> “A work of the United States Government is a work prepared by an officer or an employee of the United States Government as part of that person’s official duties... Copyright protection under [Title 17] is not available for any works of the United States Government.” 

## Additional context, comments, or links - *Optional*

A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by fellahst** [comment]
See usage of dcterms:license in  [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata) in usage guideline .
