### ISSUE TITLE
Indicate a copyright notification for dataset resources

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#97]
**Creator Name:**  John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

1. Metadata must be able to indicate a copyright statement for Catalog, Distribution, _and_ Dataset resources.
2. Multiplicity of `dcterms:rights` must be `0..*` (not limited to max 1)

## Problem Statement

While DCAT3 guidance is to use `dct:rights` for copyright statements (https://www.w3.org/TR/vocab-dcat-3/#license-rights), there are three blocking limitations:
1. DCAT3 says "use [dcterms:rights](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/rights) for all the other types of rights statements - those which are not covered by dcterms:license and dcterms:accessRights, such as copyright statements."
2. The DCAT-AP 2.1.1 profile limits use of `dcterms:rights` to only Catalogue and Distribution classes
3. The DCAT-AP 2.1.1 spec limits the multiplicity to `0..1` (max 1). 

**Implications:**
1. Requirement is to ascribe copyright to the dataset resource itself (not just the Catalogue or the dataset's Distributions)
2. DCAT-AP limits multiplicity of `dcterms:rights` to max 1. Since `dcterms:rights` can be used for copyright and "all other types of rights statements"not coved by license or accessRights, then more than one rights statement must be supported on any given dataset resource (e.g., a copyright statement and other additional rights statements) .

## Existing Approaches - *Optional*

DCAT3 guidance is to use `dct:rights` for copyright statements (https://www.w3.org/TR/vocab-dcat-3/#license-rights) but this is flawed as explained in "Problem Statement" above.

## Additional context, comments, or links - *Optional*

A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by fellahst** [comment]
This requirement is addressed in the DCAT-US profile. See  [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline

**Comment by mrratcliffe** [comment]
+1
