### ISSUE TITLE
Provide human-readable, informative explanation/ clarification for how/ why a dataset is restricted

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#98]
**Creator Name:** John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

Support a free-text ‘rights` field to allow human-readable, informative explanation/ clarification/ guidance for why a dataset is restricted for use or access. 

NOTE: This should NOT be conflated with POD `usageNotes`, ‘accessLevel’, ‘liability’, ‘accessConstraints’, ‘useConstraints’, copyright, or other fields stipulating constraints (e.g.,’CUI’). This field only provides a human-readable, possibly nuanced, explanation for those constraints unambiguously indicated in other fields.

## Additional context, comments, or links - *Optional*
A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by fellahst** [comment]
A [section for legal metadata ](https://doi-do.github.io/dcat-us/#legal-metadata)in usage guideline has been added in the specification. This section can be used as starting point for discussion and review by legal experts.
