### ISSUE TITLE
Establish and use a controlled vocabulary of USG organizations and suborganizations and bureau-codes.

### ISSUE THREAD

**Issue by johnd-im** [DOI-DO/dcat-us#99]
**Creator Name:** John Davidson
**Creator Affiliation:** Contractor, Department of the Interior/OCIO/CDO

## Requirement(s)

Identify USG organizations with a standard identification scheme that guarantees the unique, persistent, resolvable, unambiguous, machine-understandable characteristics of the identifier. All organizations referenced in the metadata must constently use the organization identifiers of the controlled vocabulary.

NOTE: this field should reference an established controlled vocabulary of USG organizations. 
NOTE: Standardize in a controlled vocabulary the range of the DCAT 1.1. `bureaucode` fields for use when referencing a USG organization; 
• delegate to departments to designate and manage their “intra” bureau suborgs
• all bureaus follow the same identifier scheme (pattern)
• bureau codes must be persistent (all identifiers must be unique for all time) e.g., even after a reorganization the legacy identifiers never go away.

## Additional context, comments, or links - *Optional*

A requirement of the DOI's "Application Profile of DCAT-US 1.1" metadata specification.

**Comment by TDabolt** [comment]
I concur with the recommended approach which balances consistency with flexibility, along with a best practice.

**Comment by fellahst** [comment]
We concur with the necessity of implementing controlled vocabularies for organizations in the DCAT-US specification, a task identified as critical and set to be explored during the implementation phase. This approach aims to standardize the identification of US Government organizations using a unique, persistent, resolvable, and unambiguous identification scheme. Such a scheme will not only enhance the clarity and consistency across datasets but also ensure historical integrity, even in cases of organizational changes. This is in alignment with the requirements of the DOI's "Application Profile of DCAT-US 1.1" metadata specification, ensuring that all organizations referenced in the metadata consistently utilize identifiers from the controlled vocabulary, thereby facilitating easier use and integration.
